// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `abnf` language (Augmented Backus-Naur Form).
Language buildAbnf() {
  final m0 = Language(name: 'Augmented Backus-Naur Form');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode();
  m0
    ..illegal = RegexSource('[!@#\$^&\',?+~`|:]')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'ALPHA',
          'BIT',
          'CHAR',
          'CR',
          'CRLF',
          'CTL',
          'DIGIT',
          'DQUOTE',
          'HEXDIG',
          'HTAB',
          'LF',
          'LWSP',
          'OCTET',
          'SP',
          'VCHAR',
          'WSP',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..scope = ScopeName('operator')
    ..match = RegexSource('=\\/?');
  m2
    ..scope = ScopeName('attribute')
    ..match = RegexSource('^[a-zA-Z][a-zA-Z0-9-]*(?=\\s*=)');
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m10, m11];
  m4
    ..scope = ScopeName('symbol')
    ..match = RegexSource('%b[0-1]+(-[0-1]+|(\\.[0-1]+)+)?');
  m5
    ..scope = ScopeName('symbol')
    ..match = RegexSource('%d[0-9]+(-[0-9]+|(\\.[0-9]+)+)?');
  m6
    ..scope = ScopeName('symbol')
    ..match = RegexSource('%x[0-9A-F]+(-[0-9A-F]+|(\\.[0-9A-F]+)+)?');
  m7
    ..scope = ScopeName('symbol')
    ..match = RegexSource('%[si](?=".*")');
  m8
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m12]
    ..frozen = true;
  m9
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m10
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m11
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m12
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  return m0;
}
