// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `accesslog` language (Apache Access Log).
Language buildAccesslog() {
  final m0 = Language(name: 'Apache Access Log');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode();
  m0..contains = [m1, m2, m3, m4, m5, m6, m7];
  m1
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}(:\\d{1,5})?\\b',
    )
    ..relevance = 5;
  m2
    ..className = ScopeName('number')
    ..begin = RegexSource('\\b\\d+\\b')
    ..relevance = 0;
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource(
      '"(?:GET|POST|HEAD|PUT|DELETE|CONNECT|OPTIONS|PATCH|TRACE)',
    )
    ..end = RegexSource('"')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'GET',
          'POST',
          'HEAD',
          'PUT',
          'DELETE',
          'CONNECT',
          'OPTIONS',
          'PATCH',
          'TRACE',
        ],
        fromList: true,
      ),
    ])
    ..illegal = RegexSource('\\n')
    ..relevance = 5
    ..contains = [m8];
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('\\[\\d[^\\]\\n]{8,}\\]')
    ..illegal = RegexSource('\\n')
    ..relevance = 1;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\]')
    ..illegal = RegexSource('\\n')
    ..relevance = 0;
  m6
    ..className = ScopeName('string')
    ..begin = RegexSource('"Mozilla\\/\\d\\.\\d \\(')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..relevance = 3;
  m7
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..relevance = 0;
  m8
    ..begin = RegexSource('HTTP\\/[12]\\.\\d\'')
    ..relevance = 5;
  return m0;
}
