// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `ada` language (Ada).
Language buildAda() {
  final m0 = Language(name: 'Ada', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abort',
          'else',
          'new',
          'return',
          'abs',
          'elsif',
          'not',
          'reverse',
          'abstract',
          'end',
          'accept',
          'entry',
          'select',
          'access',
          'exception',
          'of',
          'separate',
          'aliased',
          'exit',
          'or',
          'some',
          'all',
          'others',
          'subtype',
          'and',
          'for',
          'out',
          'synchronized',
          'array',
          'function',
          'overriding',
          'at',
          'tagged',
          'generic',
          'package',
          'task',
          'begin',
          'goto',
          'pragma',
          'terminate',
          'body',
          'private',
          'then',
          'if',
          'procedure',
          'type',
          'case',
          'in',
          'protected',
          'constant',
          'interface',
          'is',
          'raise',
          'use',
          'declare',
          'range',
          'delay',
          'limited',
          'record',
          'when',
          'delta',
          'loop',
          'rem',
          'while',
          'digits',
          'renames',
          'with',
          'do',
          'mod',
          'requeue',
          'xor',
          'parallel',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['True', 'False'], fromList: true),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('--')
    ..end = RegexSource('\$')
    ..contains = [m10, m11];
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m12];
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('\'.\'');
  m4
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '\\b(\\d(_|\\d)*#\\w+(\\.\\w+)?#([eE][-+]?\\d(_|\\d)*)?|\\d(_|\\d)*(\\.\\d(_|\\d)*)?([eE][-+]?\\d(_|\\d)*)?)',
    )
    ..relevance = 0;
  m5
    ..className = ScopeName('symbol')
    ..begin = RegexSource('\'[A-Za-z](_?[A-Za-z0-9.])*');
  m6
    ..className = ScopeName('title')
    ..begin = RegexSource(
      '(\\bwith\\s+)?(\\bprivate\\s+)?\\bpackage\\s+(\\bbody\\s+)?',
    )
    ..end = RegexSource('(is|\$)')
    ..keywords = RawKeywords([
      (scope: null, words: ['package', 'body'], fromList: false),
    ])
    ..excludeBegin = true
    ..excludeEnd = true
    ..illegal = RegexSource('\\{\\}%#\'"');
  m7
    ..begin = RegexSource(
      '(\\b(with|overriding)\\s+)?\\b(function|procedure)\\s+',
    )
    ..end = RegexSource('(\\bis|\\bwith|\\brenames|\\)\\s*;)')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'overriding',
          'function',
          'procedure',
          'with',
          'is',
          'renames',
          'return',
        ],
        fromList: false,
      ),
    ])
    ..returnBegin = true
    ..contains = [m1, m13, m9, m14];
  m8
    ..className = ScopeName('type')
    ..begin = RegexSource('\\b(sub)?type\\s+')
    ..end = RegexSource('\\s+')
    ..keywords = RawKeywords([
      (scope: null, words: ['type'], fromList: false),
    ])
    ..excludeBegin = true
    ..illegal = RegexSource('\\{\\}%#\'"');
  m9
    ..begin = RegexSource('\\s+:\\s+')
    ..end = RegexSource('\\s*(:=|;|\\)|=>|\$)')
    ..illegal = RegexSource('\\{\\}%#\'"')
    ..contains = [m15, m16, m17];
  m10
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m11
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m12
    ..begin = RegexSource('""')
    ..relevance = 0;
  m13
    ..className = ScopeName('title')
    ..begin = RegexSource('(\\bwith\\s+)?\\b(function|procedure)\\s+')
    ..end = RegexSource('(\\(|\\s+|\$)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..illegal = RegexSource('\\{\\}%#\'"');
  m14
    ..className = ScopeName('type')
    ..begin = RegexSource('\\breturn\\s+')
    ..end = RegexSource('(\\s+|;|\$)')
    ..keywords = RawKeywords([
      (scope: null, words: ['return'], fromList: false),
    ])
    ..excludeBegin = true
    ..excludeEnd = true
    ..endsParent = true
    ..illegal = RegexSource('\\{\\}%#\'"');
  m15
    ..beginKeywords = 'loop for declare others'
    ..endsParent = true;
  m16
    ..className = ScopeName('keyword')
    ..beginKeywords =
        'not null constant access function procedure in out aliased exception';
  m17
    ..className = ScopeName('type')
    ..begin = RegexSource('[A-Za-z](_?[A-Za-z0-9.])*')
    ..endsParent = true
    ..relevance = 0;
  return m0;
}
