// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `autoit` language (AutoIt).
Language buildAutoit() {
  final m0 = Language(name: 'AutoIt', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode();
  m0
    ..illegal = RegexSource('\\/\\*')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'ByRef',
          'Case',
          'Const',
          'ContinueCase',
          'ContinueLoop',
          'Dim',
          'Do',
          'Else',
          'ElseIf',
          'EndFunc',
          'EndIf',
          'EndSelect',
          'EndSwitch',
          'EndWith',
          'Enum',
          'Exit',
          'ExitLoop',
          'For',
          'Func',
          'Global',
          'If',
          'In',
          'Local',
          'Next',
          'ReDim',
          'Return',
          'Select',
          'Static',
          'Step',
          'Switch',
          'Then',
          'To',
          'Until',
          'Volatile',
          'WEnd',
          'While',
          'With',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'Abs',
          'ACos',
          'AdlibRegister',
          'AdlibUnRegister',
          'Asc',
          'AscW',
          'ASin',
          'Assign',
          'ATan',
          'AutoItSetOption',
          'AutoItWinGetTitle',
          'AutoItWinSetTitle',
          'Beep',
          'Binary',
          'BinaryLen',
          'BinaryMid',
          'BinaryToString',
          'BitAND',
          'BitNOT',
          'BitOR',
          'BitRotate',
          'BitShift',
          'BitXOR',
          'BlockInput',
          'Break',
          'Call',
          'CDTray',
          'Ceiling',
          'Chr',
          'ChrW',
          'ClipGet',
          'ClipPut',
          'ConsoleRead',
          'ConsoleWrite',
          'ConsoleWriteError',
          'ControlClick',
          'ControlCommand',
          'ControlDisable',
          'ControlEnable',
          'ControlFocus',
          'ControlGetFocus',
          'ControlGetHandle',
          'ControlGetPos',
          'ControlGetText',
          'ControlHide',
          'ControlListView',
          'ControlMove',
          'ControlSend',
          'ControlSetText',
          'ControlShow',
          'ControlTreeView',
          'Cos',
          'Dec',
          'DirCopy',
          'DirCreate',
          'DirGetSize',
          'DirMove',
          'DirRemove',
          'DllCall',
          'DllCallAddress',
          'DllCallbackFree',
          'DllCallbackGetPtr',
          'DllCallbackRegister',
          'DllClose',
          'DllOpen',
          'DllStructCreate',
          'DllStructGetData',
          'DllStructGetPtr',
          'DllStructGetSize',
          'DllStructSetData',
          'DriveGetDrive',
          'DriveGetFileSystem',
          'DriveGetLabel',
          'DriveGetSerial',
          'DriveGetType',
          'DriveMapAdd',
          'DriveMapDel',
          'DriveMapGet',
          'DriveSetLabel',
          'DriveSpaceFree',
          'DriveSpaceTotal',
          'DriveStatus',
          'EnvGet',
          'EnvSet',
          'EnvUpdate',
          'Eval',
          'Execute',
          'Exp',
          'FileChangeDir',
          'FileClose',
          'FileCopy',
          'FileCreateNTFSLink',
          'FileCreateShortcut',
          'FileDelete',
          'FileExists',
          'FileFindFirstFile',
          'FileFindNextFile',
          'FileFlush',
          'FileGetAttrib',
          'FileGetEncoding',
          'FileGetLongName',
          'FileGetPos',
          'FileGetShortcut',
          'FileGetShortName',
          'FileGetSize',
          'FileGetTime',
          'FileGetVersion',
          'FileInstall',
          'FileMove',
          'FileOpen',
          'FileOpenDialog',
          'FileRead',
          'FileReadLine',
          'FileReadToArray',
          'FileRecycle',
          'FileRecycleEmpty',
          'FileSaveDialog',
          'FileSelectFolder',
          'FileSetAttrib',
          'FileSetEnd',
          'FileSetPos',
          'FileSetTime',
          'FileWrite',
          'FileWriteLine',
          'Floor',
          'FtpSetProxy',
          'FuncName',
          'GUICreate',
          'GUICtrlCreateAvi',
          'GUICtrlCreateButton',
          'GUICtrlCreateCheckbox',
          'GUICtrlCreateCombo',
          'GUICtrlCreateContextMenu',
          'GUICtrlCreateDate',
          'GUICtrlCreateDummy',
          'GUICtrlCreateEdit',
          'GUICtrlCreateGraphic',
          'GUICtrlCreateGroup',
          'GUICtrlCreateIcon',
          'GUICtrlCreateInput',
          'GUICtrlCreateLabel',
          'GUICtrlCreateList',
          'GUICtrlCreateListView',
          'GUICtrlCreateListViewItem',
          'GUICtrlCreateMenu',
          'GUICtrlCreateMenuItem',
          'GUICtrlCreateMonthCal',
          'GUICtrlCreateObj',
          'GUICtrlCreatePic',
          'GUICtrlCreateProgress',
          'GUICtrlCreateRadio',
          'GUICtrlCreateSlider',
          'GUICtrlCreateTab',
          'GUICtrlCreateTabItem',
          'GUICtrlCreateTreeView',
          'GUICtrlCreateTreeViewItem',
          'GUICtrlCreateUpdown',
          'GUICtrlDelete',
          'GUICtrlGetHandle',
          'GUICtrlGetState',
          'GUICtrlRead',
          'GUICtrlRecvMsg',
          'GUICtrlRegisterListViewSort',
          'GUICtrlSendMsg',
          'GUICtrlSendToDummy',
          'GUICtrlSetBkColor',
          'GUICtrlSetColor',
          'GUICtrlSetCursor',
          'GUICtrlSetData',
          'GUICtrlSetDefBkColor',
          'GUICtrlSetDefColor',
          'GUICtrlSetFont',
          'GUICtrlSetGraphic',
          'GUICtrlSetImage',
          'GUICtrlSetLimit',
          'GUICtrlSetOnEvent',
          'GUICtrlSetPos',
          'GUICtrlSetResizing',
          'GUICtrlSetState',
          'GUICtrlSetStyle',
          'GUICtrlSetTip',
          'GUIDelete',
          'GUIGetCursorInfo',
          'GUIGetMsg',
          'GUIGetStyle',
          'GUIRegisterMsg',
          'GUISetAccelerators',
          'GUISetBkColor',
          'GUISetCoord',
          'GUISetCursor',
          'GUISetFont',
          'GUISetHelp',
          'GUISetIcon',
          'GUISetOnEvent',
          'GUISetState',
          'GUISetStyle',
          'GUIStartGroup',
          'GUISwitch',
          'Hex',
          'HotKeySet',
          'HttpSetProxy',
          'HttpSetUserAgent',
          'HWnd',
          'InetClose',
          'InetGet',
          'InetGetInfo',
          'InetGetSize',
          'InetRead',
          'IniDelete',
          'IniRead',
          'IniReadSection',
          'IniReadSectionNames',
          'IniRenameSection',
          'IniWrite',
          'IniWriteSection',
          'InputBox',
          'Int',
          'IsAdmin',
          'IsArray',
          'IsBinary',
          'IsBool',
          'IsDeclared',
          'IsDllStruct',
          'IsFloat',
          'IsFunc',
          'IsHWnd',
          'IsInt',
          'IsKeyword',
          'IsNumber',
          'IsObj',
          'IsPtr',
          'IsString',
          'Log',
          'MemGetStats',
          'Mod',
          'MouseClick',
          'MouseClickDrag',
          'MouseDown',
          'MouseGetCursor',
          'MouseGetPos',
          'MouseMove',
          'MouseUp',
          'MouseWheel',
          'MsgBox',
          'Number',
          'ObjCreate',
          'ObjCreateInterface',
          'ObjEvent',
          'ObjGet',
          'ObjName',
          'OnAutoItExitRegister',
          'OnAutoItExitUnRegister',
          'Ping',
          'PixelChecksum',
          'PixelGetColor',
          'PixelSearch',
          'ProcessClose',
          'ProcessExists',
          'ProcessGetStats',
          'ProcessList',
          'ProcessSetPriority',
          'ProcessWait',
          'ProcessWaitClose',
          'ProgressOff',
          'ProgressOn',
          'ProgressSet',
          'Ptr',
          'Random',
          'RegDelete',
          'RegEnumKey',
          'RegEnumVal',
          'RegRead',
          'RegWrite',
          'Round',
          'Run',
          'RunAs',
          'RunAsWait',
          'RunWait',
          'Send',
          'SendKeepActive',
          'SetError',
          'SetExtended',
          'ShellExecute',
          'ShellExecuteWait',
          'Shutdown',
          'Sin',
          'Sleep',
          'SoundPlay',
          'SoundSetWaveVolume',
          'SplashImageOn',
          'SplashOff',
          'SplashTextOn',
          'Sqrt',
          'SRandom',
          'StatusbarGetText',
          'StderrRead',
          'StdinWrite',
          'StdioClose',
          'StdoutRead',
          'String',
          'StringAddCR',
          'StringCompare',
          'StringFormat',
          'StringFromASCIIArray',
          'StringInStr',
          'StringIsAlNum',
          'StringIsAlpha',
          'StringIsASCII',
          'StringIsDigit',
          'StringIsFloat',
          'StringIsInt',
          'StringIsLower',
          'StringIsSpace',
          'StringIsUpper',
          'StringIsXDigit',
          'StringLeft',
          'StringLen',
          'StringLower',
          'StringMid',
          'StringRegExp',
          'StringRegExpReplace',
          'StringReplace',
          'StringReverse',
          'StringRight',
          'StringSplit',
          'StringStripCR',
          'StringStripWS',
          'StringToASCIIArray',
          'StringToBinary',
          'StringTrimLeft',
          'StringTrimRight',
          'StringUpper',
          'Tan',
          'TCPAccept',
          'TCPCloseSocket',
          'TCPConnect',
          'TCPListen',
          'TCPNameToIP',
          'TCPRecv',
          'TCPSend',
          'TCPShutdown,',
          'UDPShutdown',
          'TCPStartup,',
          'UDPStartup',
          'TimerDiff',
          'TimerInit',
          'ToolTip',
          'TrayCreateItem',
          'TrayCreateMenu',
          'TrayGetMsg',
          'TrayItemDelete',
          'TrayItemGetHandle',
          'TrayItemGetState',
          'TrayItemGetText',
          'TrayItemSetOnEvent',
          'TrayItemSetState',
          'TrayItemSetText',
          'TraySetClick',
          'TraySetIcon',
          'TraySetOnEvent',
          'TraySetPauseIcon',
          'TraySetState',
          'TraySetToolTip',
          'TrayTip',
          'UBound',
          'UDPBind',
          'UDPCloseSocket',
          'UDPOpen',
          'UDPRecv',
          'UDPSend',
          'VarGetType',
          'WinActivate',
          'WinActive',
          'WinClose',
          'WinExists',
          'WinFlash',
          'WinGetCaretPos',
          'WinGetClassList',
          'WinGetClientSize',
          'WinGetHandle',
          'WinGetPos',
          'WinGetProcess',
          'WinGetState',
          'WinGetText',
          'WinGetTitle',
          'WinKill',
          'WinList',
          'WinMenuSelectItem',
          'WinMinimizeAll',
          'WinMinimizeAllUndo',
          'WinMove',
          'WinSetOnTop',
          'WinSetState',
          'WinSetTitle',
          'WinSetTrans',
          'WinWait',
          'WinWaitActive',
          'WinWaitClose',
          'WinWaitNotActive',
        ],
        fromList: false,
      ),
      (
        scope: 'literal',
        words: ['True', 'False', 'And', 'Null', 'Not', 'Or', 'Default'],
        fromList: false,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7];
  m1..variants = [m8, m9, m10];
  m2..begin = RegexSource('\\\$[A-z0-9_]+');
  m3
    ..className = ScopeName('string')
    ..variants = [m11, m12];
  m4..variants = [m13, m14];
  m5
    ..className = ScopeName('meta')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'EndRegion',
          'forcedef',
          'forceref',
          'ignorefunc',
          'include',
          'include-once',
          'NoTrayIcon',
          'OnAutoItStartRegister',
          'pragma',
          'Region',
          'RequireAdmin',
          'Tidy_Off',
          'Tidy_On',
          'Tidy_Parameters',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m15, m16, m3, m1];
  m6
    ..className = ScopeName('symbol')
    ..begin = RegexSource('@[A-z0-9_]+');
  m7
    ..beginKeywords = 'Func'
    ..end = RegexSource('\$')
    ..illegal = RegexSource('\\\$|\\[|%')
    ..contains = [m17, m18];
  m8
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m19, m20]
    ..relevance = 0;
  m9
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#cs')
    ..end = RegexSource('#ce')
    ..contains = [m21, m22];
  m10
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#comments-start')
    ..end = RegexSource('#comments-end')
    ..contains = [m23, m24];
  m11
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m25];
  m12
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m26];
  m13
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b(0b[01]+)')
    ..relevance = 0
    ..frozen = true;
  m14
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m15
    ..begin = RegexSource('\\\\\\n')
    ..relevance = 0;
  m16
    ..beginKeywords = 'include'
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['include'], fromList: false),
    ])
    ..end = RegexSource('\$')
    ..contains = [m3, m27];
  m17
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z_]\\w*')
    ..relevance = 0
    ..className = ScopeName('title.function');
  m18
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m2, m3, m4];
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m21
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m22
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m23
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m24
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m25
    ..begin = RegexSource('""')
    ..relevance = 0;
  m26
    ..begin = RegexSource('\'\'')
    ..relevance = 0;
  m27
    ..className = ScopeName('string')
    ..variants = [m28, m29, m30];
  m28
    ..begin = RegexSource('<')
    ..end = RegexSource('>');
  m29
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m31];
  m30
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m32];
  m31
    ..begin = RegexSource('""')
    ..relevance = 0;
  m32
    ..begin = RegexSource('\'\'')
    ..relevance = 0;
  return m0;
}
