// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';
import 'package:hilite/src/callbacks.dart' as callbacks;

/// The `bash` language (Bash).
Language buildBash() {
  final m0 = Language(name: 'Bash', aliases: ['sh', 'zsh']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'if',
          'then',
          'else',
          'elif',
          'fi',
          'time',
          'for',
          'while',
          'until',
          'in',
          'do',
          'done',
          'case',
          'esac',
          'coproc',
          'function',
          'select',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['true', 'false'], fromList: true),
      (
        scope: 'built_in',
        words: [
          'break',
          'cd',
          'continue',
          'eval',
          'exec',
          'exit',
          'export',
          'getopts',
          'hash',
          'pwd',
          'readonly',
          'return',
          'shift',
          'test',
          'times',
          'trap',
          'umask',
          'unset',
          'alias',
          'bind',
          'builtin',
          'caller',
          'command',
          'declare',
          'echo',
          'enable',
          'help',
          'let',
          'local',
          'logout',
          'mapfile',
          'printf',
          'read',
          'readarray',
          'source',
          'sudo',
          'type',
          'typeset',
          'ulimit',
          'unalias',
          'set',
          'shopt',
          'autoload',
          'bg',
          'bindkey',
          'bye',
          'cap',
          'chdir',
          'clone',
          'comparguments',
          'compcall',
          'compctl',
          'compdescribe',
          'compfiles',
          'compgroups',
          'compquote',
          'comptags',
          'comptry',
          'compvalues',
          'dirs',
          'disable',
          'disown',
          'echotc',
          'echoti',
          'emulate',
          'fc',
          'fg',
          'float',
          'functions',
          'getcap',
          'getln',
          'history',
          'integer',
          'jobs',
          'kill',
          'limit',
          'log',
          'noglob',
          'popd',
          'print',
          'pushd',
          'pushln',
          'rehash',
          'sched',
          'setcap',
          'setopt',
          'stat',
          'suspend',
          'ttyctl',
          'unfunction',
          'unhash',
          'unlimit',
          'unsetopt',
          'vared',
          'wait',
          'whence',
          'where',
          'which',
          'zcompile',
          'zformat',
          'zftp',
          'zle',
          'zmodload',
          'zparseopts',
          'zprof',
          'zpty',
          'zregexparse',
          'zsocket',
          'zstyle',
          'ztcp',
          'chcon',
          'chgrp',
          'chown',
          'chmod',
          'cp',
          'dd',
          'df',
          'dir',
          'dircolors',
          'ln',
          'ls',
          'mkdir',
          'mkfifo',
          'mknod',
          'mktemp',
          'mv',
          'realpath',
          'rm',
          'rmdir',
          'shred',
          'sync',
          'touch',
          'truncate',
          'vdir',
          'b2sum',
          'base32',
          'base64',
          'cat',
          'cksum',
          'comm',
          'csplit',
          'cut',
          'expand',
          'fmt',
          'fold',
          'head',
          'join',
          'md5sum',
          'nl',
          'numfmt',
          'od',
          'paste',
          'ptx',
          'pr',
          'sha1sum',
          'sha224sum',
          'sha256sum',
          'sha384sum',
          'sha512sum',
          'shuf',
          'sort',
          'split',
          'sum',
          'tac',
          'tail',
          'tr',
          'tsort',
          'unexpand',
          'uniq',
          'wc',
          'arch',
          'basename',
          'chroot',
          'date',
          'dirname',
          'du',
          'echo',
          'env',
          'expr',
          'factor',
          'groups',
          'hostid',
          'id',
          'link',
          'logname',
          'nice',
          'nohup',
          'nproc',
          'pathchk',
          'pinky',
          'printenv',
          'printf',
          'pwd',
          'readlink',
          'runcon',
          'seq',
          'sleep',
          'stat',
          'stdbuf',
          'stty',
          'tee',
          'test',
          'timeout',
          'tty',
          'uname',
          'unlink',
          'uptime',
          'users',
          'who',
          'whoami',
          'yes',
        ],
        fromList: true,
      ),
    ], pattern: '\\b[a-z][a-z0-9._-]+\\b')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12];
  m1
    ..scope = ScopeName('meta')
    ..begin = RegexSource(
      '^#![ ]*\\/.*\\b(fish|bash|zsh|sh|csh|ksh|tcsh|dash|scsh)\\b.*',
    )
    ..end = RegexSource('\$')
    ..relevance = 10
    ..onBegin = callbacks.shebangOnBegin;
  m2
    ..scope = ScopeName('meta')
    ..begin = RegexSource('^#![ ]*\\/')
    ..end = RegexSource('\$')
    ..relevance = 0
    ..onBegin = callbacks.shebangOnBegin;
  m3
    ..className = ScopeName('function')
    ..begin = RegexSource('\\w[\\w\\d_]*\\s*\\(\\s*\\)\\s*\\{')
    ..returnBegin = true
    ..contains = [m13]
    ..relevance = 0;
  m4
    ..begin = RegexSource('\\\$?\\(\\(')
    ..end = RegexSource('\\)\\)')
    ..contains = [m14, m15, m12];
  m5
    ..scope = ScopeGroups({2: 'comment'})
    ..begin = null
    ..end = null
    ..contains = [m16, m17]
    ..match = RegexList(['(^|\\s)', '#.*\$']);
  m6
    ..begin = RegexSource('<<-?\\s*(?=\\w+)')
    ..starts = m18;
  m7..match = RegexSource('(\\/[a-z._-]+)+');
  m8
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m19, m12, m20];
  m9..match = RegexSource('\\\\"');
  m10
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m11..match = RegexSource('\\\\\'');
  m12
    ..className = ScopeName('variable')
    ..variants = [m21, m22];
  m13
    ..scope = ScopeName('title')
    ..begin = RegexSource('\\w[\\w\\d_]*')
    ..relevance = 0;
  m14
    ..begin = RegexSource('\\d+#[0-9a-f]+')
    ..className = ScopeName('number');
  m15
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m18..contains = [m23];
  m19
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m20
    ..className = ScopeName('subst')
    ..begin = RegexSource('\\\$\\(')
    ..end = RegexSource('\\)')
    ..contains = [m19, m8];
  m21..begin = RegexSource('\\\$[\\w\\d#@][\\w\\d_]*(?![\\w\\d])(?![\$])');
  m22
    ..begin = RegexSource('\\\$\\{')
    ..end = RegexSource('\\}')
    ..contains = [self, m24];
  m23
    ..begin = RegexSource('(\\w+)')
    ..end = RegexSource('(\\w+)')
    ..className = ScopeName('string')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m24
    ..begin = RegexSource(':-')
    ..contains = [m12];
  return m0;
}
