// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `cal` language (C/AL).
Language buildCal() {
  final m0 = Language(name: 'C/AL', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'div',
          'mod',
          'in',
          'and',
          'or',
          'not',
          'xor',
          'asserterror',
          'begin',
          'case',
          'do',
          'downto',
          'else',
          'end',
          'exit',
          'for',
          'local',
          'if',
          'of',
          'repeat',
          'then',
          'to',
          'until',
          'while',
          'with',
          'var',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['false', 'true'], fromList: false),
    ])
    ..illegal = RegexSource('\\/\\*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..match = RegexSource('[\\w]+(?=\\=)')
    ..scope = ScopeName('attribute')
    ..relevance = 0;
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m9];
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('(#\\d+)+');
  m4
    ..className = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?(DT|D|T)')
    ..relevance = 0;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m6
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m7
    ..match = RegexList([
      'OBJECT',
      '\\s+',
      '(?:Table|Form|Report|Dataport|Codeunit|XMLport|MenuSuite|Page|Query)',
      '\\s+',
      '\\d+',
      '\\s+(?=[^\\s])',
      '.*',
      '\$',
    ])
    ..relevance = 3
    ..scope = ScopeGroups({1: 'keyword', 3: 'type', 5: 'number', 7: 'title'});
  m8
    ..match = RegexList(['procedure', '\\s+', '[a-zA-Z_][\\w@]*', '\\s*'])
    ..scope = ScopeGroups({1: 'keyword', 3: 'title.function'})
    ..contains = [m10, m11, m12, m13];
  m9..begin = RegexSource('\'\'');
  m10
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'div',
          'mod',
          'in',
          'and',
          'or',
          'not',
          'xor',
          'asserterror',
          'begin',
          'case',
          'do',
          'downto',
          'else',
          'end',
          'exit',
          'for',
          'local',
          'if',
          'of',
          'repeat',
          'then',
          'to',
          'until',
          'while',
          'with',
          'var',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m2, m3, m6];
  m11
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m14, m15]
    ..frozen = true;
  m12
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [m16, m17]
    ..relevance = 0;
  m13
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\(\\*')
    ..end = RegexSource('\\*\\)')
    ..contains = [m18, m19]
    ..relevance = 10;
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m18
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m19
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  return m0;
}
