// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `clojure-repl` language (Clojure REPL).
Language buildClojureRepl() {
  final m0 = Language(name: 'Clojure REPL');
  final m1 = Mode(), m2 = Mode();
  m0..contains = [m1];
  m1
    ..className = ScopeName('meta.prompt')
    ..begin = RegexSource('^([\\w.-]+|\\s*#_)?=>')
    ..starts = m2;
  m2
    ..end = RegexSource('\$')
    ..subLanguage = SubLanguageName('clojure');
  return m0;
}
