// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `clojure` language (Clojure).
Language buildClojure() {
  final m0 = Language(name: 'Clojure', aliases: ['clj', 'edn']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode();
  m0
    ..illegal = RegexSource('\\S')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..scope = ScopeName('punctuation')
    ..match = RegexSource(',')
    ..relevance = 0;
  m2
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m11, m12, m13];
  m3
    ..scope = ScopeName('character')
    ..variants = [m14, m15, m16, m17];
  m4
    ..scope = ScopeName('regex')
    ..begin = RegexSource('#"')
    ..end = RegexSource('"')
    ..contains = [m18];
  m5
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..setJsNull(ModeKey.illegal)
    ..contains = [m18];
  m6
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m19, m20]
    ..relevance = 0;
  m7
    ..className = ScopeName('symbol')
    ..begin = RegexSource(
      '[:]{1,2}[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*',
    );
  m8
    ..begin = RegexSource(
      '\\[|(#::?[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*)?\\{',
    )
    ..end = RegexSource('[\\]\\}]')
    ..relevance = 0
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m21];
  m9
    ..scope = ScopeName('number')
    ..relevance = 0
    ..variants = [m22, m23, m24, m25, m26, m27];
  m10
    ..className = ScopeName('literal')
    ..begin = RegexSource('\\b(true|false|nil)\\b');
  m11
    ..beginKeywords = 'def defonce defprotocol defstruct defmulti defmethod defn- defn defmacro deftype defrecord'
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'def',
          'defonce',
          'defprotocol',
          'defstruct',
          'defmulti',
          'defmethod',
          'defn-',
          'defn',
          'defmacro',
          'deftype',
          'defrecord',
        ],
        fromList: false,
      ),
    ], pattern: '[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*')
    ..end = RegexSource('(\\[|#|\\d|"|:|\\{|\\)|\\(|\$)')
    ..contains = [m28, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m21];
  m12
    ..keywords = RawKeywords([
      (
        scope: 'built_in',
        words: [
          'def',
          'defonce',
          'defprotocol',
          'defstruct',
          'defmulti',
          'defmethod',
          'defn-',
          'defn',
          'defmacro',
          'deftype',
          'defrecord',
          'cond',
          'apply',
          'if-not',
          'if-let',
          'if',
          'not',
          'not=',
          '=|0',
          '<|0',
          '>|0',
          '<=|0',
          '>=|0',
          '==|0',
          '+|0',
          '/|0',
          '*|0',
          '-|0',
          'rem',
          'quot',
          'neg?',
          'pos?',
          'delay?',
          'symbol?',
          'keyword?',
          'true?',
          'false?',
          'integer?',
          'empty?',
          'coll?',
          'list?',
          'set?',
          'ifn?',
          'fn?',
          'associative?',
          'sequential?',
          'sorted?',
          'counted?',
          'reversible?',
          'number?',
          'decimal?',
          'class?',
          'distinct?',
          'isa?',
          'float?',
          'rational?',
          'reduced?',
          'ratio?',
          'odd?',
          'even?',
          'char?',
          'seq?',
          'vector?',
          'string?',
          'map?',
          'nil?',
          'contains?',
          'zero?',
          'instance?',
          'not-every?',
          'not-any?',
          'libspec?',
          '->',
          '->>',
          '..',
          '.',
          'inc',
          'compare',
          'do',
          'dotimes',
          'mapcat',
          'take',
          'remove',
          'take-while',
          'drop',
          'letfn',
          'drop-last',
          'take-last',
          'drop-while',
          'while',
          'intern',
          'condp',
          'case',
          'reduced',
          'cycle',
          'split-at',
          'split-with',
          'repeat',
          'replicate',
          'iterate',
          'range',
          'merge',
          'zipmap',
          'declare',
          'line-seq',
          'sort',
          'comparator',
          'sort-by',
          'dorun',
          'doall',
          'nthnext',
          'nthrest',
          'partition',
          'eval',
          'doseq',
          'await',
          'await-for',
          'let',
          'agent',
          'atom',
          'send',
          'send-off',
          'release-pending-sends',
          'add-watch',
          'mapv',
          'filterv',
          'remove-watch',
          'agent-error',
          'restart-agent',
          'set-error-handler',
          'error-handler',
          'set-error-mode!',
          'error-mode',
          'shutdown-agents',
          'quote',
          'var',
          'fn',
          'loop',
          'recur',
          'throw',
          'try',
          'monitor-enter',
          'monitor-exit',
          'macroexpand',
          'macroexpand-1',
          'for',
          'dosync',
          'and',
          'or',
          'when',
          'when-not',
          'when-let',
          'comp',
          'juxt',
          'partial',
          'sequence',
          'memoize',
          'constantly',
          'complement',
          'identity',
          'assert',
          'peek',
          'pop',
          'doto',
          'proxy',
          'first',
          'rest',
          'cons',
          'cast',
          'coll',
          'last',
          'butlast',
          'sigs',
          'reify',
          'second',
          'ffirst',
          'fnext',
          'nfirst',
          'nnext',
          'meta',
          'with-meta',
          'ns',
          'in-ns',
          'create-ns',
          'import',
          'refer',
          'keys',
          'select-keys',
          'vals',
          'key',
          'val',
          'rseq',
          'name',
          'namespace',
          'promise',
          'into',
          'transient',
          'persistent!',
          'conj!',
          'assoc!',
          'dissoc!',
          'pop!',
          'disj!',
          'use',
          'class',
          'type',
          'num',
          'float',
          'double',
          'short',
          'byte',
          'boolean',
          'bigint',
          'biginteger',
          'bigdec',
          'print-method',
          'print-dup',
          'throw-if',
          'printf',
          'format',
          'load',
          'compile',
          'get-in',
          'update-in',
          'pr',
          'pr-on',
          'newline',
          'flush',
          'read',
          'slurp',
          'read-line',
          'subvec',
          'with-open',
          'memfn',
          'time',
          're-find',
          're-groups',
          'rand-int',
          'rand',
          'mod',
          'locking',
          'assert-valid-fdecl',
          'alias',
          'resolve',
          'ref',
          'deref',
          'refset',
          'swap!',
          'reset!',
          'set-validator!',
          'compare-and-set!',
          'alter-meta!',
          'reset-meta!',
          'commute',
          'get-validator',
          'alter',
          'ref-set',
          'ref-history-count',
          'ref-min-history',
          'ref-max-history',
          'ensure',
          'sync',
          'io!',
          'new',
          'next',
          'conj',
          'set!',
          'to-array',
          'future',
          'future-call',
          'into-array',
          'aset',
          'gen-class',
          'reduce',
          'map',
          'filter',
          'find',
          'empty',
          'hash-map',
          'hash-set',
          'sorted-map',
          'sorted-map-by',
          'sorted-set',
          'sorted-set-by',
          'vec',
          'vector',
          'seq',
          'flatten',
          'reverse',
          'assoc',
          'dissoc',
          'list',
          'disj',
          'get',
          'union',
          'difference',
          'intersection',
          'extend',
          'extend-type',
          'extend-protocol',
          'int',
          'nth',
          'delay',
          'count',
          'concat',
          'chunk',
          'chunk-buffer',
          'chunk-append',
          'chunk-first',
          'chunk-rest',
          'max',
          'min',
          'dec',
          'unchecked-inc-int',
          'unchecked-inc',
          'unchecked-dec-inc',
          'unchecked-dec',
          'unchecked-negate',
          'unchecked-add-int',
          'unchecked-add',
          'unchecked-subtract-int',
          'unchecked-subtract',
          'chunk-next',
          'chunk-cons',
          'chunked-seq?',
          'prn',
          'vary-meta',
          'lazy-seq',
          'spread',
          'list*',
          'str',
          'find-keyword',
          'keyword',
          'symbol',
          'gensym',
          'force',
          'rationalize',
        ],
        fromList: false,
      ),
    ], pattern: '[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*')
    ..className = ScopeName('name')
    ..begin = RegexSource(
      '[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*',
    )
    ..relevance = 0
    ..starts = m13;
  m13
    ..endsWithParent = true
    ..relevance = 0
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m21];
  m14..match = RegexSource('\\\\o[0-3]?[0-7]{1,2}');
  m15..match = RegexSource('\\\\u[0-9a-fA-F]{4}');
  m16..match = RegexSource('\\\\(newline|space|tab|formfeed|backspace|return)');
  m17
    ..match = RegexSource('\\\\\\S')
    ..relevance = 0;
  m18
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m21
    ..begin = RegexSource(
      '[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*',
    )
    ..relevance = 0;
  m22..match = RegexSource('[-+]?0[xX][0-9a-fA-F]+N?');
  m23..match = RegexSource('[-+]?0[0-7]+N?');
  m24..match = RegexSource('[-+]?[1-9][0-9]?[rR][0-9a-zA-Z]+N?');
  m25..match = RegexSource('[-+]?[0-9]+\\/[0-9]+N?');
  m26
    ..match = RegexSource(
      '[-+]?[0-9]+((\\.[0-9]*([eE][+-]?[0-9]+)?M?)|([eE][+-]?[0-9]+M?|M))',
    );
  m27..match = RegexSource('[-+]?([1-9][0-9]*|0)N?');
  m28
    ..className = ScopeName('title')
    ..begin = RegexSource(
      '[#]?[a-zA-Z_\\-!.?+*=<>&\'][a-zA-Z_\\-!.?+*=<>&\'0-9/;:\$#]*',
    )
    ..relevance = 0
    ..excludeEnd = true
    ..endsParent = true;
  return m0;
}
