// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `csharp` language (C#).
Language buildCsharp() {
  final m0 = Language(name: 'C#', aliases: ['cs', 'c#']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode(),
      m37 = Mode(),
      m38 = Mode(),
      m39 = Mode(),
      m40 = Mode(),
      m41 = Mode(),
      m42 = Mode(),
      m43 = Mode(),
      m44 = Mode(),
      m45 = Mode(),
      m46 = Mode(),
      m47 = Mode(),
      m48 = Mode(),
      m49 = Mode(),
      m50 = Mode(),
      m51 = Mode(),
      m52 = Mode(),
      m53 = Mode(),
      m54 = Mode(),
      m55 = Mode(),
      m56 = Mode(),
      m57 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'base',
          'break',
          'case',
          'catch',
          'class',
          'const',
          'continue',
          'do',
          'else',
          'event',
          'explicit',
          'extern',
          'finally',
          'fixed',
          'for',
          'foreach',
          'goto',
          'if',
          'implicit',
          'in',
          'interface',
          'internal',
          'is',
          'lock',
          'namespace',
          'new',
          'operator',
          'out',
          'override',
          'params',
          'private',
          'protected',
          'public',
          'readonly',
          'record',
          'ref',
          'return',
          'scoped',
          'sealed',
          'sizeof',
          'stackalloc',
          'static',
          'struct',
          'switch',
          'this',
          'throw',
          'try',
          'typeof',
          'unchecked',
          'unsafe',
          'using',
          'virtual',
          'void',
          'volatile',
          'while',
          'add',
          'alias',
          'and',
          'ascending',
          'args',
          'async',
          'await',
          'by',
          'descending',
          'dynamic',
          'equals',
          'file',
          'from',
          'get',
          'global',
          'group',
          'init',
          'into',
          'join',
          'let',
          'nameof',
          'not',
          'notnull',
          'on',
          'or',
          'orderby',
          'partial',
          'record',
          'remove',
          'required',
          'scoped',
          'select',
          'set',
          'unmanaged',
          'value|0',
          'var',
          'when',
          'where',
          'with',
          'yield',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'byte',
          'char',
          'decimal',
          'delegate',
          'double',
          'dynamic',
          'enum',
          'float',
          'int',
          'long',
          'nint',
          'nuint',
          'object',
          'sbyte',
          'short',
          'string',
          'ulong',
          'uint',
          'ushort',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: ['default', 'false', 'null', 'true'],
        fromList: true,
      ),
    ])
    ..illegal = RegexSource('::')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('///')
    ..end = RegexSource('\$')
    ..contains = [m14, m15, m16]
    ..returnBegin = true;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m17, m18]
    ..frozen = true;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m19, m20]
    ..frozen = true;
  m4
    ..className = ScopeName('meta')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'if',
          'else',
          'elif',
          'endif',
          'define',
          'undef',
          'warning',
          'error',
          'line',
          'region',
          'endregion',
          'pragma',
          'checksum',
        ],
        fromList: false,
      ),
    ]);
  m5..variants = [m21, m22, m23, m24, m25, m26];
  m6
    ..className = ScopeName('number')
    ..variants = [m27, m28, m29]
    ..relevance = 0;
  m7
    ..beginKeywords = 'class interface'
    ..relevance = 0
    ..end = RegexSource('[{;=]')
    ..illegal = RegexSource('[^\\s:,]')
    ..contains = [m30, m31, m32, m2, m3];
  m8
    ..beginKeywords = 'namespace'
    ..relevance = 0
    ..end = RegexSource('[{;=]')
    ..illegal = RegexSource('[^\\s:]')
    ..contains = [m31, m2, m3];
  m9
    ..beginKeywords = 'record'
    ..relevance = 0
    ..end = RegexSource('[{;=]')
    ..illegal = RegexSource('[^\\s:]')
    ..contains = [m31, m32, m2, m3];
  m10
    ..className = ScopeName('meta')
    ..begin = RegexSource('^\\s*\\[(?=[\\w])')
    ..excludeBegin = true
    ..end = RegexSource('\\]')
    ..excludeEnd = true
    ..contains = [m33];
  m11
    ..beginKeywords = 'new return throw await else'
    ..relevance = 0;
  m12
    ..className = ScopeName('function')
    ..begin = RegexSource(
      '([a-zA-Z]\\w*(<[a-zA-Z]\\w*(\\s*,\\s*[a-zA-Z]\\w*)*>)?(\\[\\])?\\s+)+[a-zA-Z]\\w*\\s*(<[^=]+>\\s*)?\\(',
    )
    ..returnBegin = true
    ..end = RegexSource('\\s*[{;=]')
    ..excludeEnd = true
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'base',
          'break',
          'case',
          'catch',
          'class',
          'const',
          'continue',
          'do',
          'else',
          'event',
          'explicit',
          'extern',
          'finally',
          'fixed',
          'for',
          'foreach',
          'goto',
          'if',
          'implicit',
          'in',
          'interface',
          'internal',
          'is',
          'lock',
          'namespace',
          'new',
          'operator',
          'out',
          'override',
          'params',
          'private',
          'protected',
          'public',
          'readonly',
          'record',
          'ref',
          'return',
          'scoped',
          'sealed',
          'sizeof',
          'stackalloc',
          'static',
          'struct',
          'switch',
          'this',
          'throw',
          'try',
          'typeof',
          'unchecked',
          'unsafe',
          'using',
          'virtual',
          'void',
          'volatile',
          'while',
          'add',
          'alias',
          'and',
          'ascending',
          'args',
          'async',
          'await',
          'by',
          'descending',
          'dynamic',
          'equals',
          'file',
          'from',
          'get',
          'global',
          'group',
          'init',
          'into',
          'join',
          'let',
          'nameof',
          'not',
          'notnull',
          'on',
          'or',
          'orderby',
          'partial',
          'record',
          'remove',
          'required',
          'scoped',
          'select',
          'set',
          'unmanaged',
          'value|0',
          'var',
          'when',
          'where',
          'with',
          'yield',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'byte',
          'char',
          'decimal',
          'delegate',
          'double',
          'dynamic',
          'enum',
          'float',
          'int',
          'long',
          'nint',
          'nuint',
          'object',
          'sbyte',
          'short',
          'string',
          'ulong',
          'uint',
          'ushort',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: ['default', 'false', 'null', 'true'],
        fromList: true,
      ),
    ])
    ..contains = [m34, m35, m36, m37, m2, m3];
  m13
    ..begin = RegexSource('@[a-zA-Z]\\w*')
    ..relevance = 0;
  m14
    ..className = ScopeName('doctag')
    ..variants = [m38, m39, m40];
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m17
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m18
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m21
    ..className = ScopeName('string')
    ..begin = RegexSource('"""("*)(?!")(.|\\n)*?"""\\1')
    ..relevance = 1;
  m22
    ..className = ScopeName('string')
    ..begin = RegexSource('\\\$@"')
    ..end = RegexSource('"')
    ..contains = [m41, m42, m43, m44];
  m23
    ..className = ScopeName('string')
    ..begin = RegexSource('\\\$"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m45, m46, m47, m48];
  m24
    ..className = ScopeName('string')
    ..begin = RegexSource('@"')
    ..end = RegexSource('"')
    ..contains = [m49];
  m25
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m47]
    ..frozen = true;
  m26
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m47]
    ..frozen = true;
  m27..begin = RegexSource('\\b0[bB]_*[01](_*[01])*([uU][lL]?|[lL][uU]?)?');
  m28
    ..begin = RegexSource(
      '(-?)\\b0[xX]_*[a-fA-F0-9](_*[a-fA-F0-9])*([uU][lL]?|[lL][uU]?)?',
    );
  m29
    ..begin = RegexSource(
      '(-?)(\\b\\d(_*\\d)*(\\.(\\d(_*\\d)*)?)?|\\.\\d(_*\\d)*)([eE][-+]?\\d(_*\\d)*)?([fFdDmM]|[uU][lL]?|[lL][uU]?)?',
    );
  m30..beginKeywords = 'where class';
  m31
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z](\\.?\\w)*')
    ..relevance = 0;
  m32
    ..begin = RegexSource('<')
    ..end = RegexSource('>')
    ..contains = [m50, m31];
  m33
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m34
    ..beginKeywords = 'public private protected static internal protected abstract async extern override unsafe virtual new sealed partial'
    ..relevance = 0;
  m35
    ..begin = RegexSource('[a-zA-Z]\\w*\\s*(<[^=]+>\\s*)?\\(')
    ..returnBegin = true
    ..contains = [m51, m32]
    ..relevance = 0;
  m36..match = RegexSource('\\(\\)');
  m37
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'base',
          'break',
          'case',
          'catch',
          'class',
          'const',
          'continue',
          'do',
          'else',
          'event',
          'explicit',
          'extern',
          'finally',
          'fixed',
          'for',
          'foreach',
          'goto',
          'if',
          'implicit',
          'in',
          'interface',
          'internal',
          'is',
          'lock',
          'namespace',
          'new',
          'operator',
          'out',
          'override',
          'params',
          'private',
          'protected',
          'public',
          'readonly',
          'record',
          'ref',
          'return',
          'scoped',
          'sealed',
          'sizeof',
          'stackalloc',
          'static',
          'struct',
          'switch',
          'this',
          'throw',
          'try',
          'typeof',
          'unchecked',
          'unsafe',
          'using',
          'virtual',
          'void',
          'volatile',
          'while',
          'add',
          'alias',
          'and',
          'ascending',
          'args',
          'async',
          'await',
          'by',
          'descending',
          'dynamic',
          'equals',
          'file',
          'from',
          'get',
          'global',
          'group',
          'init',
          'into',
          'join',
          'let',
          'nameof',
          'not',
          'notnull',
          'on',
          'or',
          'orderby',
          'partial',
          'record',
          'remove',
          'required',
          'scoped',
          'select',
          'set',
          'unmanaged',
          'value|0',
          'var',
          'when',
          'where',
          'with',
          'yield',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'byte',
          'char',
          'decimal',
          'delegate',
          'double',
          'dynamic',
          'enum',
          'float',
          'int',
          'long',
          'nint',
          'nuint',
          'object',
          'sbyte',
          'short',
          'string',
          'ulong',
          'uint',
          'ushort',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: ['default', 'false', 'null', 'true'],
        fromList: true,
      ),
    ])
    ..relevance = 0
    ..contains = [m5, m6, m3];
  m38
    ..begin = RegexSource('///')
    ..relevance = 0;
  m39..begin = RegexSource('<!--|-->');
  m40
    ..begin = RegexSource('</?')
    ..end = RegexSource('>');
  m41..begin = RegexSource('\\{\\{');
  m42..begin = RegexSource('\\}\\}');
  m43..begin = RegexSource('""');
  m44
    ..className = ScopeName('subst')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'base',
          'break',
          'case',
          'catch',
          'class',
          'const',
          'continue',
          'do',
          'else',
          'event',
          'explicit',
          'extern',
          'finally',
          'fixed',
          'for',
          'foreach',
          'goto',
          'if',
          'implicit',
          'in',
          'interface',
          'internal',
          'is',
          'lock',
          'namespace',
          'new',
          'operator',
          'out',
          'override',
          'params',
          'private',
          'protected',
          'public',
          'readonly',
          'record',
          'ref',
          'return',
          'scoped',
          'sealed',
          'sizeof',
          'stackalloc',
          'static',
          'struct',
          'switch',
          'this',
          'throw',
          'try',
          'typeof',
          'unchecked',
          'unsafe',
          'using',
          'virtual',
          'void',
          'volatile',
          'while',
          'add',
          'alias',
          'and',
          'ascending',
          'args',
          'async',
          'await',
          'by',
          'descending',
          'dynamic',
          'equals',
          'file',
          'from',
          'get',
          'global',
          'group',
          'init',
          'into',
          'join',
          'let',
          'nameof',
          'not',
          'notnull',
          'on',
          'or',
          'orderby',
          'partial',
          'record',
          'remove',
          'required',
          'scoped',
          'select',
          'set',
          'unmanaged',
          'value|0',
          'var',
          'when',
          'where',
          'with',
          'yield',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'byte',
          'char',
          'decimal',
          'delegate',
          'double',
          'dynamic',
          'enum',
          'float',
          'int',
          'long',
          'nint',
          'nuint',
          'object',
          'sbyte',
          'short',
          'string',
          'ulong',
          'uint',
          'ushort',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: ['default', 'false', 'null', 'true'],
        fromList: true,
      ),
    ])
    ..contains = [m22, m23, m24, m25, m26, m6, m3];
  m45..begin = RegexSource('\\{\\{');
  m46..begin = RegexSource('\\}\\}');
  m47
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m48
    ..className = ScopeName('subst')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'base',
          'break',
          'case',
          'catch',
          'class',
          'const',
          'continue',
          'do',
          'else',
          'event',
          'explicit',
          'extern',
          'finally',
          'fixed',
          'for',
          'foreach',
          'goto',
          'if',
          'implicit',
          'in',
          'interface',
          'internal',
          'is',
          'lock',
          'namespace',
          'new',
          'operator',
          'out',
          'override',
          'params',
          'private',
          'protected',
          'public',
          'readonly',
          'record',
          'ref',
          'return',
          'scoped',
          'sealed',
          'sizeof',
          'stackalloc',
          'static',
          'struct',
          'switch',
          'this',
          'throw',
          'try',
          'typeof',
          'unchecked',
          'unsafe',
          'using',
          'virtual',
          'void',
          'volatile',
          'while',
          'add',
          'alias',
          'and',
          'ascending',
          'args',
          'async',
          'await',
          'by',
          'descending',
          'dynamic',
          'equals',
          'file',
          'from',
          'get',
          'global',
          'group',
          'init',
          'into',
          'join',
          'let',
          'nameof',
          'not',
          'notnull',
          'on',
          'or',
          'orderby',
          'partial',
          'record',
          'remove',
          'required',
          'scoped',
          'select',
          'set',
          'unmanaged',
          'value|0',
          'var',
          'when',
          'where',
          'with',
          'yield',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'byte',
          'char',
          'decimal',
          'delegate',
          'double',
          'dynamic',
          'enum',
          'float',
          'int',
          'long',
          'nint',
          'nuint',
          'object',
          'sbyte',
          'short',
          'string',
          'ulong',
          'uint',
          'ushort',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: ['default', 'false', 'null', 'true'],
        fromList: true,
      ),
    ])
    ..illegal = RegexSource('\\n')
    ..contains = [m52, m23, m53, m25, m26, m6, m54];
  m49..begin = RegexSource('""');
  m50..beginKeywords = 'in out';
  m51
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z]\\w*')
    ..relevance = 0
    ..frozen = true;
  m52
    ..className = ScopeName('string')
    ..begin = RegexSource('\\\$@"')
    ..end = RegexSource('"')
    ..contains = [m55, m56, m57, m48]
    ..illegal = RegexSource('\\n');
  m53
    ..className = ScopeName('string')
    ..begin = RegexSource('@"')
    ..end = RegexSource('"')
    ..contains = [m49]
    ..illegal = RegexSource('\\n');
  m54
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m19, m20]
    ..illegal = RegexSource('\\n');
  m55..begin = RegexSource('\\{\\{');
  m56..begin = RegexSource('\\}\\}');
  m57..begin = RegexSource('""');
  return m0;
}
