// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `csp` language (CSP).
Language buildCsp() {
  final m0 = Language(name: 'CSP');
  final m1 = Mode(), m2 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'base-uri',
          'child-src',
          'connect-src',
          'default-src',
          'fenced-frame-src',
          'font-src',
          'form-action',
          'frame-ancestors',
          'frame-src',
          'img-src',
          'manifest-src',
          'media-src',
          'object-src',
          'plugin-types',
          'report-to',
          'report-uri',
          'require-trusted-types-for',
          'sandbox',
          'script-src',
          'script-src-attr',
          'script-src-elem',
          'style-src',
          'style-src-attr',
          'style-src-elem',
          'trusted-types',
          'unsafe-hashes',
          'worker-src',
        ],
        fromList: true,
      ),
    ], pattern: '[a-zA-Z][a-zA-Z0-9_-]*')
    ..contains = [m1, m2];
  m1
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m2
    ..className = ScopeName('attribute')
    ..begin = RegexSource('^Content')
    ..end = RegexSource(':')
    ..excludeEnd = true;
  return m0;
}
