// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `d` language (D).
Language buildD() {
  final m0 = Language(name: 'D');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'alias',
          'align',
          'asm',
          'assert',
          'auto',
          'body',
          'break',
          'byte',
          'case',
          'cast',
          'catch',
          'class',
          'const',
          'continue',
          'debug',
          'default',
          'delete',
          'deprecated',
          'do',
          'else',
          'enum',
          'export',
          'extern',
          'final',
          'finally',
          'for',
          'foreach',
          'foreach_reverse|10',
          'goto',
          'if',
          'immutable',
          'import',
          'in',
          'inout',
          'int',
          'interface',
          'invariant',
          'is',
          'lazy',
          'macro',
          'mixin',
          'module',
          'new',
          'nothrow',
          'out',
          'override',
          'package',
          'pragma',
          'private',
          'protected',
          'public',
          'pure',
          'ref',
          'return',
          'scope',
          'shared',
          'static',
          'struct',
          'super',
          'switch',
          'synchronized',
          'template',
          'this',
          'throw',
          'try',
          'typedef',
          'typeid',
          'typeof',
          'union',
          'unittest',
          'version',
          'void',
          'volatile',
          'while',
          'with',
          '__FILE__',
          '__LINE__',
          '__gshared|10',
          '__thread',
          '__traits',
          '__DATE__',
          '__EOF__',
          '__TIME__',
          '__TIMESTAMP__',
          '__VENDOR__',
          '__VERSION__',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'bool',
          'cdouble',
          'cent',
          'cfloat',
          'char',
          'creal',
          'dchar',
          'delegate',
          'double',
          'dstring',
          'float',
          'function',
          'idouble',
          'ifloat',
          'ireal',
          'long',
          'real',
          'short',
          'string',
          'ubyte',
          'ucent',
          'uint',
          'ulong',
          'ushort',
          'wchar',
          'wstring',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['false', 'null', 'true'], fromList: false),
    ], pattern: '[a-zA-Z_]\\w*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m15, m16]
    ..frozen = true;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m17, m18]
    ..frozen = true;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\/\\+')
    ..end = RegexSource('\\+\\/')
    ..contains = [self, m19, m20]
    ..relevance = 10;
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('x"[\\da-fA-F\\s\\n\\r]*"[cwd]?')
    ..relevance = 10;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..contains = [m21]
    ..end = RegexSource('"[cwd]?');
  m6
    ..className = ScopeName('string')
    ..begin = RegexSource('[rq]"')
    ..end = RegexSource('"[cwd]?')
    ..relevance = 5;
  m7
    ..className = ScopeName('string')
    ..begin = RegexSource('`')
    ..end = RegexSource('`[cwd]?');
  m8
    ..className = ScopeName('string')
    ..begin = RegexSource('q"\\{')
    ..end = RegexSource('\\}"');
  m9
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '\\b(((0[xX](([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*)\\.([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*)|\\.?([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*))[pP][+-]?(0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d))|((0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d)(\\.\\d*|([eE][+-]?(0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d)))|\\d+\\.(0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d)|\\.(0|[1-9][\\d_]*)([eE][+-]?(0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d))?))([fF]|L|i|[fF]i|Li)?|((0|[1-9][\\d_]*)|0[bB][01_]+|0[xX]([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*))(i|[fF]i|Li))',
    )
    ..relevance = 0;
  m10
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '\\b((0|[1-9][\\d_]*)|0[bB][01_]+|0[xX]([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*))(L|u|U|Lu|LU|uL|UL)?',
    )
    ..relevance = 0;
  m11
    ..className = ScopeName('string')
    ..begin = RegexSource(
      '\'(\\\\([\'"\\?\\\\abfnrtv]|u[\\dA-Fa-f]{4}|[0-7]{1,3}|x[\\dA-Fa-f]{2}|U[\\dA-Fa-f]{8})|&[a-zA-Z\\d]{2,};|.)',
    )
    ..end = RegexSource('\'')
    ..illegal = RegexSource('.');
  m12
    ..className = ScopeName('meta')
    ..begin = RegexSource('^#!')
    ..end = RegexSource('\$')
    ..relevance = 5;
  m13
    ..className = ScopeName('meta')
    ..begin = RegexSource('#(line)')
    ..end = RegexSource('\$')
    ..relevance = 5;
  m14
    ..className = ScopeName('keyword')
    ..begin = RegexSource('@[a-zA-Z_][a-zA-Z_\\d]*');
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m17
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m18
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m21
    ..begin = RegexSource(
      '\\\\([\'"\\?\\\\abfnrtv]|u[\\dA-Fa-f]{4}|[0-7]{1,3}|x[\\dA-Fa-f]{2}|U[\\dA-Fa-f]{8})|&[a-zA-Z\\d]{2,};',
    )
    ..relevance = 0;
  return m0;
}
