// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `delphi` language (Delphi).
Language buildDelphi() {
  final m0 = Language(
    name: 'Delphi',
    aliases: ['dpr', 'dfm', 'pas', 'pascal'],
    caseInsensitive: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'exports',
          'register',
          'file',
          'shl',
          'array',
          'record',
          'property',
          'for',
          'mod',
          'while',
          'set',
          'ally',
          'label',
          'uses',
          'raise',
          'not',
          'stored',
          'class',
          'safecall',
          'var',
          'interface',
          'or',
          'private',
          'static',
          'exit',
          'index',
          'inherited',
          'to',
          'else',
          'stdcall',
          'override',
          'shr',
          'asm',
          'far',
          'resourcestring',
          'finalization',
          'packed',
          'virtual',
          'out',
          'and',
          'protected',
          'library',
          'do',
          'xorwrite',
          'goto',
          'near',
          'function',
          'end',
          'div',
          'overload',
          'object',
          'unit',
          'begin',
          'string',
          'on',
          'inline',
          'repeat',
          'until',
          'destructor',
          'write',
          'message',
          'program',
          'with',
          'read',
          'initialization',
          'except',
          'default',
          'nil',
          'if',
          'case',
          'cdecl',
          'in',
          'downto',
          'threadvar',
          'of',
          'try',
          'pascal',
          'const',
          'external',
          'constructor',
          'type',
          'public',
          'then',
          'implementation',
          'finally',
          'published',
          'procedure',
          'absolute',
          'reintroduce',
          'operator',
          'as',
          'is',
          'abstract',
          'alias',
          'assembler',
          'bitpacked',
          'break',
          'continue',
          'cppdecl',
          'cvar',
          'enumerator',
          'experimental',
          'platform',
          'deprecated',
          'unimplemented',
          'dynamic',
          'export',
          'far16',
          'forward',
          'generic',
          'helper',
          'implements',
          'interrupt',
          'iochecks',
          'local',
          'name',
          'nodefault',
          'noreturn',
          'nostackframe',
          'oldfpccall',
          'otherwise',
          'saveregisters',
          'softfloat',
          'specialize',
          'strict',
          'unaligned',
          'varargs',
        ],
        fromList: true,
      ),
    ])
    ..illegal = RegexSource('"|\\\$[G-Zg-z]|\\/\\*|<\\/|\\|')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m10];
  m2
    ..className = ScopeName('string')
    ..variants = [m11, m12, m13, m14];
  m3
    ..className = ScopeName('number')
    ..relevance = 0
    ..variants = [m15, m16, m17, m18, m19, m20];
  m4
    ..begin = RegexSource('[a-zA-Z]\\w*\\s*=\\s*class\\s*\\(')
    ..returnBegin = true
    ..contains = [m21];
  m5
    ..className = ScopeName('function')
    ..beginKeywords = 'function constructor destructor procedure'
    ..end = RegexSource('[:;]')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: ['function', 'constructor|10', 'destructor|10', 'procedure|10'],
        fromList: false,
      ),
    ])
    ..contains = [m21, m22, m6, m7, m8, m9];
  m6
    ..className = ScopeName('meta')
    ..variants = [m23, m24];
  m7
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m25, m26]
    ..frozen = true;
  m8
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [m27, m28]
    ..relevance = 0;
  m9
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\(\\*')
    ..end = RegexSource('\\*\\)')
    ..contains = [m29, m30]
    ..relevance = 10;
  m10..begin = RegexSource('\'\'');
  m11..match = RegexSource('#\\d[\\d_]*');
  m12..match = RegexSource('#\\\$[\\dA-Fa-f][\\dA-Fa-f_]*');
  m13..match = RegexSource('#&[0-7][0-7_]*');
  m14..match = RegexSource('#%[01][01_]*');
  m15..match = RegexSource('\\b\\d[\\d_]*(\\.\\d[\\d_]*)?');
  m16..match = RegexSource('\\\$[\\dA-Fa-f_]+');
  m17
    ..match = RegexSource('\\\$')
    ..relevance = 0;
  m18..match = RegexSource('&[0-7][0-7_]*');
  m19..match = RegexSource('%[01_]+');
  m20
    ..match = RegexSource('%')
    ..relevance = 0;
  m21
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z]\\w*')
    ..relevance = 0
    ..frozen = true;
  m22
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'exports',
          'register',
          'file',
          'shl',
          'array',
          'record',
          'property',
          'for',
          'mod',
          'while',
          'set',
          'ally',
          'label',
          'uses',
          'raise',
          'not',
          'stored',
          'class',
          'safecall',
          'var',
          'interface',
          'or',
          'private',
          'static',
          'exit',
          'index',
          'inherited',
          'to',
          'else',
          'stdcall',
          'override',
          'shr',
          'asm',
          'far',
          'resourcestring',
          'finalization',
          'packed',
          'virtual',
          'out',
          'and',
          'protected',
          'library',
          'do',
          'xorwrite',
          'goto',
          'near',
          'function',
          'end',
          'div',
          'overload',
          'object',
          'unit',
          'begin',
          'string',
          'on',
          'inline',
          'repeat',
          'until',
          'destructor',
          'write',
          'message',
          'program',
          'with',
          'read',
          'initialization',
          'except',
          'default',
          'nil',
          'if',
          'case',
          'cdecl',
          'in',
          'downto',
          'threadvar',
          'of',
          'try',
          'pascal',
          'const',
          'external',
          'constructor',
          'type',
          'public',
          'then',
          'implementation',
          'finally',
          'published',
          'procedure',
          'absolute',
          'reintroduce',
          'operator',
          'as',
          'is',
          'abstract',
          'alias',
          'assembler',
          'bitpacked',
          'break',
          'continue',
          'cppdecl',
          'cvar',
          'enumerator',
          'experimental',
          'platform',
          'deprecated',
          'unimplemented',
          'dynamic',
          'export',
          'far16',
          'forward',
          'generic',
          'helper',
          'implements',
          'interrupt',
          'iochecks',
          'local',
          'name',
          'nodefault',
          'noreturn',
          'nostackframe',
          'oldfpccall',
          'otherwise',
          'saveregisters',
          'softfloat',
          'specialize',
          'strict',
          'unaligned',
          'varargs',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m1, m2, m6, m7, m8, m9];
  m23
    ..begin = RegexSource('\\{\\\$')
    ..end = RegexSource('\\}');
  m24
    ..begin = RegexSource('\\(\\*\\\$')
    ..end = RegexSource('\\*\\)');
  m25
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m26
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m27
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m28
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m29
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m30
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  return m0;
}
