// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `elixir` language (Elixir).
Language buildElixir() {
  final m0 = Language(name: 'Elixir', aliases: ['ex', 'exs']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode(),
      m37 = Mode(),
      m38 = Mode(),
      m39 = Mode(),
      m40 = Mode(),
      m41 = Mode(),
      m42 = Mode(),
      m43 = Mode(),
      m44 = Mode(),
      m45 = Mode(),
      m46 = Mode(),
      m47 = Mode(),
      m48 = Mode(),
      m49 = Mode(),
      m50 = Mode(),
      m51 = Mode(),
      m52 = Mode(),
      m53 = Mode(),
      m54 = Mode(),
      m55 = Mode(),
      m56 = Mode(),
      m57 = Mode(),
      m58 = Mode(),
      m59 = Mode(),
      m60 = Mode(),
      m61 = Mode(),
      m62 = Mode(),
      m63 = Mode(),
      m64 = Mode(),
      m65 = Mode(),
      m66 = Mode(),
      m67 = Mode(),
      m68 = Mode(),
      m69 = Mode(),
      m70 = Mode(),
      m71 = Mode(),
      m72 = Mode(),
      m73 = Mode(),
      m74 = Mode(),
      m75 = Mode(),
      m76 = Mode(),
      m77 = Mode(),
      m78 = Mode(),
      m79 = Mode(),
      m80 = Mode(),
      m81 = Mode(),
      m82 = Mode(),
      m83 = Mode(),
      m84 = Mode(),
      m85 = Mode(),
      m86 = Mode(),
      m87 = Mode(),
      m88 = Mode(),
      m89 = Mode(),
      m90 = Mode(),
      m91 = Mode(),
      m92 = Mode(),
      m93 = Mode(),
      m94 = Mode(),
      m95 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'after',
          'alias',
          'and',
          'case',
          'catch',
          'cond',
          'defstruct',
          'defguard',
          'defguardp',
          'do',
          'else',
          'end',
          'fn',
          'for',
          'if',
          'import',
          'in',
          'not',
          'or',
          'quote',
          'raise',
          'receive',
          'require',
          'reraise',
          'rescue',
          'try',
          'unless',
          'unquote',
          'unquote_splicing',
          'use',
          'when',
          'with|0',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['false', 'nil', 'true'], fromList: true),
    ], pattern: '[a-zA-Z_][a-zA-Z0-9_.]*(!|\\?)?')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14];
  m1
    ..scope = ScopeName('string')
    ..match = RegexSource('\\?\'')
    ..relevance = 0;
  m2
    ..className = ScopeName('string')
    ..contains = [m15, m16]
    ..variants = [m17, m18, m19, m20, m21, m22, m23, m24];
  m3
    ..className = ScopeName('regex')
    ..variants = [m25, m26];
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('~[A-Z](?=[/|([{<"\'])')
    ..contains = [m27, m28, m29, m30, m31, m32, m33, m34];
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('~[a-z](?=[/|([{<"\'])')
    ..contains = [m35, m36, m37, m38, m39, m40, m41, m42];
  m6
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m43, m44]
    ..frozen = true;
  m7
    ..className = ScopeName('class')
    ..beginKeywords = 'defimpl defmodule defprotocol defrecord'
    ..end = RegexSource('\\bdo\\b|\$|;')
    ..contains = [m45];
  m8
    ..className = ScopeName('function')
    ..beginKeywords = 'def defp defmacro defmacrop'
    ..end = RegexSource('\\B\\b')
    ..contains = [m45];
  m9..begin = RegexSource('::');
  m10
    ..className = ScopeName('symbol')
    ..begin = RegexSource(':(?![\\s:])')
    ..contains = [m2, m46]
    ..relevance = 0;
  m11
    ..className = ScopeName('symbol')
    ..begin = RegexSource('[a-zA-Z_][a-zA-Z0-9_.]*(!|\\?)?:(?!:)')
    ..relevance = 0;
  m12
    ..className = ScopeName('title.class')
    ..begin = RegexSource('(\\b[A-Z][a-zA-Z0-9_]+)')
    ..relevance = 0;
  m13
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '(\\b0o[0-7_]+)|(\\b0b[01_]+)|(\\b0x[0-9a-fA-F_]+)|(-?\\b[0-9][0-9_]*(\\.[0-9_]+([eE][-+]?[0-9]+)?)?)',
    )
    ..relevance = 0;
  m14
    ..className = ScopeName('variable')
    ..begin = RegexSource('(\\\$\\W)|((\\\$|@@?)(\\w+))');
  m15
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m16
    ..className = ScopeName('subst')
    ..begin = RegexSource('#\\{')
    ..end = RegexSource('\\}')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'after',
          'alias',
          'and',
          'case',
          'catch',
          'cond',
          'defstruct',
          'defguard',
          'defguardp',
          'do',
          'else',
          'end',
          'fn',
          'for',
          'if',
          'import',
          'in',
          'not',
          'or',
          'quote',
          'raise',
          'receive',
          'require',
          'reraise',
          'rescue',
          'try',
          'unless',
          'unquote',
          'unquote_splicing',
          'use',
          'when',
          'with|0',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['false', 'nil', 'true'], fromList: true),
    ], pattern: '[a-zA-Z_][a-zA-Z0-9_.]*(!|\\?)?')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14];
  m17
    ..begin = RegexSource('"""')
    ..end = RegexSource('"""');
  m18
    ..begin = RegexSource('\'\'\'')
    ..end = RegexSource('\'\'\'');
  m19
    ..begin = RegexSource('~S"""')
    ..end = RegexSource('"""')
    ..contains = [];
  m20
    ..begin = RegexSource('~S"')
    ..end = RegexSource('"')
    ..contains = [];
  m21
    ..begin = RegexSource('~S\'\'\'')
    ..end = RegexSource('\'\'\'')
    ..contains = [];
  m22
    ..begin = RegexSource('~S\'')
    ..end = RegexSource('\'')
    ..contains = [];
  m23
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m24
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m25
    ..begin = RegexSource('~r(?=[/|([{<"\'])')
    ..contains = [m47, m48, m49, m50, m51, m52, m53, m54];
  m26
    ..begin = RegexSource('~R(?=[/|([{<"\'])')
    ..contains = [m55, m56, m57, m58, m59, m60, m61, m62];
  m27
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m63];
  m28
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m64];
  m29
    ..begin = RegexSource('\\/')
    ..end = RegexSource('\\/')
    ..contains = [m65];
  m30
    ..begin = RegexSource('\\|')
    ..end = RegexSource('\\|')
    ..contains = [m66];
  m31
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m67];
  m32
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\]')
    ..contains = [m68];
  m33
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [m69];
  m34
    ..begin = RegexSource('<')
    ..end = RegexSource('>')
    ..contains = [m70];
  m35
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m71, m72, m16];
  m36
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m73, m72, m16];
  m37
    ..begin = RegexSource('\\/')
    ..end = RegexSource('\\/')
    ..contains = [m74, m72, m16];
  m38
    ..begin = RegexSource('\\|')
    ..end = RegexSource('\\|')
    ..contains = [m75, m72, m16];
  m39
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m76, m72, m16];
  m40
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\]')
    ..contains = [m77, m72, m16];
  m41
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [m78, m72, m16];
  m42
    ..begin = RegexSource('<')
    ..end = RegexSource('>')
    ..contains = [m79, m72, m16];
  m43
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m44
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m45
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z_][a-zA-Z0-9_.]*(!|\\?)?')
    ..relevance = 0
    ..endsParent = true;
  m46
    ..begin = RegexSource(
      '[a-zA-Z_]\\w*[!?=]?|[-+~]@|<<|>>|=~|===?|<=>|[<>]=?|\\*\\*|[-/+%^&*~`|]|\\[\\]=?',
    );
  m47
    ..begin = RegexSource('"')
    ..end = RegexSource('"[uismxfU]{0,7}')
    ..contains = [m80, m72, m16];
  m48
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'[uismxfU]{0,7}')
    ..contains = [m81, m72, m16];
  m49
    ..begin = RegexSource('\\/')
    ..end = RegexSource('\\/[uismxfU]{0,7}')
    ..contains = [m82, m72, m16];
  m50
    ..begin = RegexSource('\\|')
    ..end = RegexSource('\\|[uismxfU]{0,7}')
    ..contains = [m83, m72, m16];
  m51
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)[uismxfU]{0,7}')
    ..contains = [m84, m72, m16];
  m52
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\][uismxfU]{0,7}')
    ..contains = [m85, m72, m16];
  m53
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}[uismxfU]{0,7}')
    ..contains = [m86, m72, m16];
  m54
    ..begin = RegexSource('<')
    ..end = RegexSource('>[uismxfU]{0,7}')
    ..contains = [m87, m72, m16];
  m55
    ..begin = RegexSource('"')
    ..end = RegexSource('"[uismxfU]{0,7}')
    ..contains = [m88];
  m56
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'[uismxfU]{0,7}')
    ..contains = [m89];
  m57
    ..begin = RegexSource('\\/')
    ..end = RegexSource('\\/[uismxfU]{0,7}')
    ..contains = [m90];
  m58
    ..begin = RegexSource('\\|')
    ..end = RegexSource('\\|[uismxfU]{0,7}')
    ..contains = [m91];
  m59
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)[uismxfU]{0,7}')
    ..contains = [m92];
  m60
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\][uismxfU]{0,7}')
    ..contains = [m93];
  m61
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}[uismxfU]{0,7}')
    ..contains = [m94];
  m62
    ..begin = RegexSource('<')
    ..end = RegexSource('>[uismxfU]{0,7}')
    ..contains = [m95];
  m63
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\"')
    ..relevance = 0;
  m64
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\'')
    ..relevance = 0;
  m65
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\/')
    ..relevance = 0;
  m66
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\|')
    ..relevance = 0;
  m67
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\)')
    ..relevance = 0;
  m68
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\]')
    ..relevance = 0;
  m69
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\}')
    ..relevance = 0;
  m70
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\>')
    ..relevance = 0;
  m71
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\"')
    ..relevance = 0;
  m72
    ..match = RegexSource('\\\\[\\s\\S]')
    ..scope = ScopeName('char.escape')
    ..relevance = 0;
  m73
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\'')
    ..relevance = 0;
  m74
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\/')
    ..relevance = 0;
  m75
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\|')
    ..relevance = 0;
  m76
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\)')
    ..relevance = 0;
  m77
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\]')
    ..relevance = 0;
  m78
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\}')
    ..relevance = 0;
  m79
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\>')
    ..relevance = 0;
  m80
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\"')
    ..relevance = 0;
  m81
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\'')
    ..relevance = 0;
  m82
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\/')
    ..relevance = 0;
  m83
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\|')
    ..relevance = 0;
  m84
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\)')
    ..relevance = 0;
  m85
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\]')
    ..relevance = 0;
  m86
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\}')
    ..relevance = 0;
  m87
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\>')
    ..relevance = 0;
  m88
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\"')
    ..relevance = 0;
  m89
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\'')
    ..relevance = 0;
  m90
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\/')
    ..relevance = 0;
  m91
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\|')
    ..relevance = 0;
  m92
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\)')
    ..relevance = 0;
  m93
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\]')
    ..relevance = 0;
  m94
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\\\}')
    ..relevance = 0;
  m95
    ..scope = ScopeName('char.escape')
    ..begin = RegexSource('\\\\>')
    ..relevance = 0;
  return m0;
}
