// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `fix` language (FIX).
Language buildFix() {
  final m0 = Language(name: 'FIX', caseInsensitive: true);
  final m1 = Mode(), m2 = Mode(), m3 = Mode();
  m0..contains = [m1];
  m1
    ..begin = RegexSource('[^\\u2401\\u0001]+')
    ..end = RegexSource('[\\u2401\\u0001]')
    ..excludeEnd = true
    ..returnBegin = true
    ..returnEnd = false
    ..contains = [m2, m3];
  m2
    ..begin = RegexSource('([^\\u2401\\u0001=]+)')
    ..end = RegexSource('=([^\\u2401\\u0001=]+)')
    ..returnEnd = true
    ..returnBegin = false
    ..className = ScopeName('attr');
  m3
    ..begin = RegexSource('=')
    ..end = RegexSource('([\\u2401\\u0001])')
    ..excludeEnd = true
    ..excludeBegin = true
    ..className = ScopeName('string');
  return m0;
}
