// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `gams` language (GAMS).
Language buildGams() {
  final m0 = Language(name: 'GAMS', aliases: ['gms'], caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode(),
      m37 = Mode(),
      m38 = Mode(),
      m39 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abort',
          'acronym',
          'acronyms',
          'alias',
          'all',
          'and',
          'assign',
          'binary',
          'card',
          'diag',
          'display',
          'else',
          'eq',
          'file',
          'files',
          'for',
          'free',
          'ge',
          'gt',
          'if',
          'integer',
          'le',
          'loop',
          'lt',
          'maximizing',
          'minimizing',
          'model',
          'models',
          'ne',
          'negative',
          'no',
          'not',
          'option',
          'options',
          'or',
          'ord',
          'positive',
          'prod',
          'put',
          'putpage',
          'puttl',
          'repeat',
          'sameas',
          'semicont',
          'semiint',
          'smax',
          'smin',
          'solve',
          'sos1',
          'sos2',
          'sum',
          'system',
          'table',
          'then',
          'until',
          'using',
          'while',
          'xor',
          'yes',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['eps', 'inf', 'na'], fromList: false),
      (
        scope: 'built_in',
        words: [
          'abs',
          'arccos',
          'arcsin',
          'arctan',
          'arctan2',
          'Beta',
          'betaReg',
          'binomial',
          'ceil',
          'centropy',
          'cos',
          'cosh',
          'cvPower',
          'div',
          'div0',
          'eDist',
          'entropy',
          'errorf',
          'execSeed',
          'exp',
          'fact',
          'floor',
          'frac',
          'gamma',
          'gammaReg',
          'log',
          'logBeta',
          'logGamma',
          'log10',
          'log2',
          'mapVal',
          'max',
          'min',
          'mod',
          'ncpCM',
          'ncpF',
          'ncpVUpow',
          'ncpVUsin',
          'normal',
          'pi',
          'poly',
          'power',
          'randBinomial',
          'randLinear',
          'randTriangle',
          'round',
          'rPower',
          'sigmoid',
          'sign',
          'signPower',
          'sin',
          'sinh',
          'slexp',
          'sllog10',
          'slrec',
          'sqexp',
          'sqlog10',
          'sqr',
          'sqrec',
          'sqrt',
          'tan',
          'tanh',
          'trunc',
          'uniform',
          'uniformInt',
          'vcPower',
          'bool_and',
          'bool_eqv',
          'bool_imp',
          'bool_not',
          'bool_or',
          'bool_xor',
          'ifThen',
          'rel_eq',
          'rel_ge',
          'rel_gt',
          'rel_le',
          'rel_lt',
          'rel_ne',
          'gday',
          'gdow',
          'ghour',
          'gleap',
          'gmillisec',
          'gminute',
          'gmonth',
          'gsecond',
          'gyear',
          'jdate',
          'jnow',
          'jstart',
          'jtime',
          'errorLevel',
          'execError',
          'gamsRelease',
          'gamsVersion',
          'handleCollect',
          'handleDelete',
          'handleStatus',
          'handleSubmit',
          'heapFree',
          'heapLimit',
          'heapSize',
          'jobHandle',
          'jobKill',
          'jobStatus',
          'jobTerminate',
          'licenseLevel',
          'licenseStatus',
          'maxExecError',
          'sleep',
          'timeClose',
          'timeComp',
          'timeElapsed',
          'timeExec',
          'timeStart',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^\\\$ontext')
    ..end = RegexSource('^\\\$offtext')
    ..contains = [m13, m14];
  m2
    ..className = ScopeName('meta')
    ..begin = RegexSource('^\\\$[a-z0-9]+')
    ..end = RegexSource('\$')
    ..returnBegin = true
    ..contains = [m15];
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^\\*')
    ..end = RegexSource('\$')
    ..contains = [m16, m17];
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m18, m19]
    ..frozen = true;
  m5
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m20, m21]
    ..frozen = true;
  m6
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m22]
    ..frozen = true;
  m7
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m22]
    ..frozen = true;
  m8
    ..beginKeywords = 'set sets parameter parameters variable variables scalar scalars equation equations'
    ..end = RegexSource(';')
    ..contains = [m23, m4, m5, m6, m7, m24, m25];
  m9
    ..beginKeywords = 'table'
    ..end = RegexSource(';')
    ..returnBegin = true
    ..contains = [m26, m27, m4, m5, m6, m7, m11];
  m10
    ..className = ScopeName('function')
    ..begin = RegexSource('^[a-z][a-z0-9_,\\-+\' ()\$]+\\.{2}')
    ..returnBegin = true
    ..contains = [m28, m29, m12];
  m11
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m12
    ..className = ScopeName('symbol')
    ..variants = [m30, m31];
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m15
    ..className = ScopeName('keyword')
    ..begin = RegexSource('^\\\$[a-z0-9]+');
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m18
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m19
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m20
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m21
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m22
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m23
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^\\*')
    ..end = RegexSource('\$')
    ..contains = [m32, m33];
  m24
    ..begin = RegexSource('/')
    ..end = RegexSource('/')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abort',
          'acronym',
          'acronyms',
          'alias',
          'all',
          'and',
          'assign',
          'binary',
          'card',
          'diag',
          'display',
          'else',
          'eq',
          'file',
          'files',
          'for',
          'free',
          'ge',
          'gt',
          'if',
          'integer',
          'le',
          'loop',
          'lt',
          'maximizing',
          'minimizing',
          'model',
          'models',
          'ne',
          'negative',
          'no',
          'not',
          'option',
          'options',
          'or',
          'ord',
          'positive',
          'prod',
          'put',
          'putpage',
          'puttl',
          'repeat',
          'sameas',
          'semicont',
          'semiint',
          'smax',
          'smin',
          'solve',
          'sos1',
          'sos2',
          'sum',
          'system',
          'table',
          'then',
          'until',
          'using',
          'while',
          'xor',
          'yes',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['eps', 'inf', 'na'], fromList: false),
      (
        scope: 'built_in',
        words: [
          'abs',
          'arccos',
          'arcsin',
          'arctan',
          'arctan2',
          'Beta',
          'betaReg',
          'binomial',
          'ceil',
          'centropy',
          'cos',
          'cosh',
          'cvPower',
          'div',
          'div0',
          'eDist',
          'entropy',
          'errorf',
          'execSeed',
          'exp',
          'fact',
          'floor',
          'frac',
          'gamma',
          'gammaReg',
          'log',
          'logBeta',
          'logGamma',
          'log10',
          'log2',
          'mapVal',
          'max',
          'min',
          'mod',
          'ncpCM',
          'ncpF',
          'ncpVUpow',
          'ncpVUsin',
          'normal',
          'pi',
          'poly',
          'power',
          'randBinomial',
          'randLinear',
          'randTriangle',
          'round',
          'rPower',
          'sigmoid',
          'sign',
          'signPower',
          'sin',
          'sinh',
          'slexp',
          'sllog10',
          'slrec',
          'sqexp',
          'sqlog10',
          'sqr',
          'sqrec',
          'sqrt',
          'tan',
          'tanh',
          'trunc',
          'uniform',
          'uniformInt',
          'vcPower',
          'bool_and',
          'bool_eqv',
          'bool_imp',
          'bool_not',
          'bool_or',
          'bool_xor',
          'ifThen',
          'rel_eq',
          'rel_ge',
          'rel_gt',
          'rel_le',
          'rel_lt',
          'rel_ne',
          'gday',
          'gdow',
          'ghour',
          'gleap',
          'gmillisec',
          'gminute',
          'gmonth',
          'gsecond',
          'gyear',
          'jdate',
          'jnow',
          'jstart',
          'jtime',
          'errorLevel',
          'execError',
          'gamsRelease',
          'gamsVersion',
          'handleCollect',
          'handleDelete',
          'handleStatus',
          'handleSubmit',
          'heapFree',
          'heapLimit',
          'heapSize',
          'jobHandle',
          'jobKill',
          'jobStatus',
          'jobTerminate',
          'licenseLevel',
          'licenseStatus',
          'maxExecError',
          'sleep',
          'timeClose',
          'timeComp',
          'timeElapsed',
          'timeExec',
          'timeStart',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m34, m4, m5, m6, m7, m11];
  m25
    ..begin = RegexSource('[a-z][a-z0-9_]*(\\([a-z0-9_, ]*\\))?[ \\t]+')
    ..excludeBegin = true
    ..end = RegexSource('\$')
    ..endsWithParent = true
    ..contains = [m34, m24, m35];
  m26
    ..beginKeywords = 'table'
    ..end = RegexSource('\$')
    ..contains = [m25];
  m27
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^\\*')
    ..end = RegexSource('\$')
    ..contains = [m36, m37];
  m28
    ..className = ScopeName('title')
    ..begin = RegexSource('^[a-z0-9_]+');
  m29
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..excludeBegin = true
    ..excludeEnd = true;
  m30..begin = RegexSource('=[lgenxc]=');
  m31..begin = RegexSource('\\\$');
  m32
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m33
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m34
    ..className = ScopeName('comment')
    ..variants = [m38, m39]
    ..illegal = RegexSource('\\n')
    ..contains = [m22];
  m35
    ..className = ScopeName('comment')
    ..begin = RegexSource(
      '[a-z0-9&#*=?@\\\\><:,()\$[\\]_.{}!+%^-]+(?:[ ]+[a-z0-9&#*=?@\\\\><:,()\$[\\]_.{}!+%^-]+)*',
    )
    ..relevance = 0;
  m36
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m37
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m38
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m39
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  return m0;
}
