// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';
import 'package:hilite/src/callbacks.dart' as callbacks;

/// The `gcode` language (G-code (ISO 6983)).
Language buildGcode() {
  final m0 = Language(
    name: 'G-code (ISO 6983)',
    aliases: ['nc'],
    caseInsensitive: true,
    disableAutodetect: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'THEN',
          'ELSE',
          'ENDIF',
          'IF',
          'GOTO',
          'DO',
          'WHILE',
          'WH',
          'END',
          'CALL',
          'SUB',
          'ENDSUB',
          'EQ',
          'NE',
          'LT',
          'GT',
          'LE',
          'GE',
          'AND',
          'OR',
          'XOR',
          '%',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: [
          'ATAN',
          'ABS',
          'ACOS',
          'ASIN',
          'COS',
          'EXP',
          'FIX',
          'FUP',
          'ROUND',
          'LN',
          'SIN',
          'SQRT',
          'TAN',
          'EXISTS',
        ],
        fromList: true,
      ),
    ], pattern: '[A-Z]+|%')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m12, m13];
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m14, m15];
  m3
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m16]
    ..frozen = true;
  m4
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m16]
    ..frozen = true;
  m5
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m6
    ..scope = ScopeName('title.function')
    ..variants = [m17, m18, m19, m20];
  m7
    ..scope = ScopeName('symbol')
    ..variants = [m21, m22, m23, m24, m25];
  m8
    ..scope = ScopeName('operator')
    ..match = RegexSource('^N\\s*\\d+');
  m9
    ..scope = ScopeName('variable')
    ..match = RegexSource('-?#\\s*\\d+');
  m10
    ..scope = ScopeName('property')
    ..variants = [m26, m27];
  m11
    ..scope = ScopeName('params')
    ..variants = [m28, m29];
  m12
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m13
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m16
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m17..match = RegexSource('\\b[GM]\\s*\\d+(\\.\\d+)?');
  m18
    ..begin = RegexSource('[GM]\\s*\\d+(\\.\\d+)?')
    ..onBegin = callbacks.gcodeLetterBoundary;
  m19..match = RegexSource('\\bT\\s*\\d+');
  m20
    ..begin = RegexSource('T\\s*\\d+')
    ..onBegin = callbacks.gcodeLetterBoundary;
  m21..match = RegexSource('\\bO\\s*\\d+');
  m22
    ..begin = RegexSource('O\\s*\\d+')
    ..onBegin = callbacks.gcodeLetterBoundary;
  m23..match = RegexSource('\\bO<.+>');
  m24
    ..begin = RegexSource('O<.+>')
    ..onBegin = callbacks.gcodeLetterBoundary;
  m25..match = RegexSource('\\*\\s*\\d+\\s*\$');
  m26
    ..match = RegexSource(
      '\\b[ABCUVWXYZ]\\s*[+-]?((\\.\\d+)|(\\d+)(\\.\\d*)?)',
    );
  m27
    ..begin = RegexSource('[ABCUVWXYZ]\\s*[+-]?((\\.\\d+)|(\\d+)(\\.\\d*)?)')
    ..onBegin = callbacks.gcodeLetterBoundary;
  m28
    ..match = RegexSource(
      '\\b[FHIJKPQRS]\\s*[+-]?((\\.\\d+)|(\\d+)(\\.\\d*)?)',
    );
  m29
    ..begin = RegexSource('[FHIJKPQRS]\\s*[+-]?((\\.\\d+)|(\\d+)(\\.\\d*)?)')
    ..onBegin = callbacks.gcodeLetterBoundary;
  return m0;
}
