// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `ini` language (TOML, also INI).
Language buildIni() {
  final m0 = Language(
    name: 'TOML, also INI',
    aliases: ['toml'],
    caseInsensitive: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode();
  m0
    ..illegal = RegexSource('\\S')
    ..contains = [m1, m2, m3];
  m1
    ..scope = ScopeName('comment')
    ..begin = null
    ..end = null
    ..contains = [m4, m5]
    ..variants = [m6, m7];
  m2
    ..className = ScopeName('section')
    ..begin = RegexSource('\\[+')
    ..end = RegexSource('\\]+');
  m3
    ..begin = RegexSource(
      '(?:[A-Za-z0-9_-]+|"(\\\\"|[^"])*"|\'[^\']*\')(\\s*\\.\\s*(?:[A-Za-z0-9_-]+|"(\\\\"|[^"])*"|\'[^\']*\'))*(?=\\s*=\\s*[^#\\s])',
    )
    ..className = ScopeName('attr')
    ..starts = m8;
  m4
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m5
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m6
    ..begin = RegexSource(';')
    ..end = RegexSource('\$');
  m7
    ..begin = RegexSource('#')
    ..end = RegexSource('\$');
  m8
    ..end = RegexSource('\$')
    ..contains = [m1, m9, m10, m11, m12, m13];
  m9
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\]')
    ..contains = [m1, m10, m11, m12, m13, self]
    ..relevance = 0;
  m10
    ..className = ScopeName('literal')
    ..begin = RegexSource('\\bon|off|true|false|yes|no\\b');
  m11
    ..className = ScopeName('variable')
    ..variants = [m14, m15];
  m12
    ..className = ScopeName('string')
    ..contains = [m16]
    ..variants = [m17, m18, m19, m20];
  m13
    ..className = ScopeName('number')
    ..relevance = 0
    ..variants = [m21, m22];
  m14..begin = RegexSource('\\\$[\\w\\d"][\\w\\d_]*');
  m15..begin = RegexSource('\\\$\\{(.*?)\\}');
  m16
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m17
    ..begin = RegexSource('\'\'\'')
    ..end = RegexSource('\'\'\'')
    ..relevance = 10;
  m18
    ..begin = RegexSource('"""')
    ..end = RegexSource('"""')
    ..relevance = 10;
  m19
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m20
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m21..begin = RegexSource('([+-]+)?[\\d]+_[\\d_]+');
  m22..begin = RegexSource('\\b\\d+(\\.\\d+)?');
  return m0;
}
