// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `jboss-cli` language (JBoss CLI).
Language buildJbossCli() {
  final m0 = Language(name: 'JBoss CLI', aliases: ['wildfly-cli']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'alias',
          'batch',
          'cd',
          'clear',
          'command',
          'connect',
          'connection-factory',
          'connection-info',
          'data-source',
          'deploy',
          'deployment-info',
          'deployment-overlay',
          'echo',
          'echo-dmr',
          'help',
          'history',
          'if',
          'jdbc-driver-info',
          'jms-queue|20',
          'jms-topic|20',
          'ls',
          'patch',
          'pwd',
          'quit',
          'read-attribute',
          'read-operation',
          'reload',
          'rollout-plan',
          'run-batch',
          'set',
          'shutdown',
          'try',
          'unalias',
          'undeploy',
          'unset',
          'version',
          'xa-data-source',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false'], fromList: false),
    ], pattern: '[a-z-]+')
    ..contains = [m1, m2, m3, m4, m5, m6];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m7, m8]
    ..frozen = true;
  m2
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m9]
    ..frozen = true;
  m3
    ..className = ScopeName('params')
    ..begin = RegexSource('--[\\w\\-=\\/]+');
  m4
    ..className = ScopeName('function')
    ..begin = RegexSource(':[\\w\\-.]+')
    ..relevance = 0;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('\\B([\\/.])[\\w\\-.\\/=]+');
  m6
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m10]
    ..relevance = 0;
  m7
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m8
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m9
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m10
    ..begin = RegexSource('[\\w-]+ *=')
    ..returnBegin = true
    ..relevance = 0
    ..contains = [m11];
  m11
    ..className = ScopeName('attr')
    ..begin = RegexSource('[\\w-]+');
  return m0;
}
