// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `kotlin` language (Kotlin).
Language buildKotlin() {
  final m0 = Language(name: 'Kotlin', aliases: ['kt', 'kts', 'ktm', 'ktx']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode(),
      m37 = Mode(),
      m38 = Mode(),
      m39 = Mode(),
      m40 = Mode(),
      m41 = Mode(),
      m42 = Mode(),
      m43 = Mode(),
      m44 = Mode(),
      m45 = Mode(),
      m46 = Mode(),
      m47 = Mode(),
      m48 = Mode(),
      m49 = Mode(),
      m50 = Mode(),
      m51 = Mode(),
      m52 = Mode(),
      m53 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'val',
          'var',
          'vararg',
          'get',
          'set',
          'class',
          'object',
          'open',
          'private',
          'protected',
          'public',
          'noinline',
          'crossinline',
          'dynamic',
          'final',
          'enum',
          'if',
          'else',
          'do',
          'while',
          'for',
          'when',
          'throw',
          'try',
          'catch',
          'finally',
          'import',
          'package',
          'is',
          'in',
          'fun',
          'override',
          'companion',
          'reified',
          'inline',
          'lateinit',
          'init',
          'interface',
          'annotation',
          'data',
          'sealed',
          'internal',
          'infix',
          'operator',
          'out',
          'by',
          'constructor',
          'super',
          'tailrec',
          'where',
          'const',
          'inner',
          'suspend',
          'typealias',
          'external',
          'expect',
          'actual',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'Byte',
          'Short',
          'Char',
          'Int',
          'Long',
          'Boolean',
          'Float',
          'Double',
          'Void',
          'Unit',
          'Nothing',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'null'], fromList: false),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m13, m14, m15]
    ..relevance = 0;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m16, m17]
    ..frozen = true;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m18, m19, m20];
  m4
    ..className = ScopeName('keyword')
    ..begin = RegexSource('\\b(break|continue|return|this)\\b')
    ..starts = m21;
  m5
    ..className = ScopeName('symbol')
    ..begin = RegexSource('[a-zA-Z_]\\w*@');
  m6
    ..className = ScopeName('meta')
    ..begin = RegexSource(
      '@(?:file|property|field|get|set|receiver|param|setparam|delegate)\\s*:(?:\\s*[a-zA-Z_]\\w*)?',
    );
  m7
    ..className = ScopeName('meta')
    ..begin = RegexSource('@[a-zA-Z_]\\w*')
    ..contains = [m22];
  m8
    ..className = ScopeName('function')
    ..beginKeywords = 'fun'
    ..end = RegexSource('[(]|\$')
    ..returnBegin = true
    ..excludeEnd = true
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'val',
          'var',
          'vararg',
          'get',
          'set',
          'class',
          'object',
          'open',
          'private',
          'protected',
          'public',
          'noinline',
          'crossinline',
          'dynamic',
          'final',
          'enum',
          'if',
          'else',
          'do',
          'while',
          'for',
          'when',
          'throw',
          'try',
          'catch',
          'finally',
          'import',
          'package',
          'is',
          'in',
          'fun',
          'override',
          'companion',
          'reified',
          'inline',
          'lateinit',
          'init',
          'interface',
          'annotation',
          'data',
          'sealed',
          'internal',
          'infix',
          'operator',
          'out',
          'by',
          'constructor',
          'super',
          'tailrec',
          'where',
          'const',
          'inner',
          'suspend',
          'typealias',
          'external',
          'expect',
          'actual',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'Byte',
          'Short',
          'Char',
          'Int',
          'Long',
          'Boolean',
          'Float',
          'Double',
          'Void',
          'Unit',
          'Nothing',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'null'], fromList: false),
    ])
    ..relevance = 5
    ..contains = [m23, m24, m25, m3];
  m9
    ..begin = RegexList(['class|interface|trait', '\\s+', '[a-zA-Z_]\\w*'])
    ..beginScope = ScopeGroups({3: 'title.class'})
    ..keywords = RawKeywords([
      (scope: null, words: ['class', 'interface', 'trait'], fromList: false),
    ])
    ..end = RegexSource('[:\\{(]|\$')
    ..excludeEnd = true
    ..illegal = RegexSource('extends implements')
    ..contains = [m26, m27, m28, m29, m6, m7];
  m10
    ..className = ScopeName('string')
    ..variants = [m30, m31, m32];
  m11
    ..className = ScopeName('meta')
    ..begin = RegexSource('^#!/usr/bin/env')
    ..end = RegexSource('\$')
    ..illegal = RegexSource('\n');
  m12
    ..className = ScopeName('number')
    ..variants = [m33, m34, m35, m36, m37, m38, m39, m40, m41]
    ..relevance = 0;
  m13
    ..className = ScopeName('doctag')
    ..begin = RegexSource('@[A-Za-z]+');
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m18
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m42, m43]
    ..frozen = true;
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m21..contains = [m44];
  m22
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m45, self];
  m23
    ..begin = RegexSource('[a-zA-Z_]\\w*\\s*\\(')
    ..returnBegin = true
    ..relevance = 0
    ..contains = [m27];
  m24
    ..className = ScopeName('type')
    ..begin = RegexSource('<')
    ..end = RegexSource('>')
    ..keywords = RawKeywords([
      (scope: null, words: ['reified'], fromList: false),
    ])
    ..relevance = 0;
  m25
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..endsParent = true
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'as',
          'val',
          'var',
          'vararg',
          'get',
          'set',
          'class',
          'object',
          'open',
          'private',
          'protected',
          'public',
          'noinline',
          'crossinline',
          'dynamic',
          'final',
          'enum',
          'if',
          'else',
          'do',
          'while',
          'for',
          'when',
          'throw',
          'try',
          'catch',
          'finally',
          'import',
          'package',
          'is',
          'in',
          'fun',
          'override',
          'companion',
          'reified',
          'inline',
          'lateinit',
          'init',
          'interface',
          'annotation',
          'data',
          'sealed',
          'internal',
          'infix',
          'operator',
          'out',
          'by',
          'constructor',
          'super',
          'tailrec',
          'where',
          'const',
          'inner',
          'suspend',
          'typealias',
          'external',
          'expect',
          'actual',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'Byte',
          'Short',
          'Char',
          'Int',
          'Long',
          'Boolean',
          'Float',
          'Double',
          'Void',
          'Unit',
          'Nothing',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'null'], fromList: false),
    ])
    ..relevance = 0
    ..contains = [m46, m2, m3, m6, m7, m10, m47];
  m26..beginKeywords = 'public protected internal private constructor';
  m27
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z_]\\w*')
    ..relevance = 0
    ..frozen = true;
  m28
    ..className = ScopeName('type')
    ..begin = RegexSource('<')
    ..end = RegexSource('>')
    ..excludeBegin = true
    ..excludeEnd = true
    ..relevance = 0;
  m29
    ..className = ScopeName('type')
    ..begin = RegexSource('[,:]\\s*')
    ..end = RegexSource('[<\\(,){\\s]|\$')
    ..excludeBegin = true
    ..returnEnd = true;
  m30
    ..begin = RegexSource('"""')
    ..end = RegexSource('"""(?=[^"])')
    ..contains = [m48, m49];
  m31
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m50];
  m32
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m50, m48, m49];
  m33
    ..begin = RegexSource(
      '(\\b([0-9](_*[0-9])*)((\\.([0-9](_*[0-9])*))|\\.)?|(\\.([0-9](_*[0-9])*)))[eE][+-]?([0-9](_*[0-9])*)[fFdD]?\\b',
    );
  m34
    ..begin = RegexSource(
      '\\b([0-9](_*[0-9])*)((\\.([0-9](_*[0-9])*))[fFdD]?\\b|\\.([fFdD]\\b)?)',
    );
  m35..begin = RegexSource('(\\.([0-9](_*[0-9])*))[fFdD]?\\b');
  m36..begin = RegexSource('\\b([0-9](_*[0-9])*)[fFdD]\\b');
  m37
    ..begin = RegexSource(
      '\\b0[xX](([0-9a-fA-F](_*[0-9a-fA-F])*)\\.?|([0-9a-fA-F](_*[0-9a-fA-F])*)?\\.([0-9a-fA-F](_*[0-9a-fA-F])*))[pP][+-]?([0-9](_*[0-9])*)[fFdD]?\\b',
    );
  m38..begin = RegexSource('\\b(0|[1-9](_*[0-9])*)[lL]?\\b');
  m39..begin = RegexSource('\\b0[xX]([0-9a-fA-F](_*[0-9a-fA-F])*)[lL]?\\b');
  m40..begin = RegexSource('\\b0(_*[0-7])*[lL]?\\b');
  m41..begin = RegexSource('\\b0[bB][01](_*[01])*[lL]?\\b');
  m42
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m43
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m44
    ..className = ScopeName('symbol')
    ..begin = RegexSource('@\\w+');
  m45
    ..className = ScopeName('string')
    ..variants = [m30, m31, m32];
  m46
    ..begin = RegexSource(':')
    ..end = RegexSource('[=,\\/]')
    ..endsWithParent = true
    ..contains = [m51, m2, m3]
    ..relevance = 0;
  m47
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m48
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$[a-zA-Z_]\\w*');
  m49
    ..className = ScopeName('subst')
    ..begin = RegexSource('\\\$\\{')
    ..end = RegexSource('\\}')
    ..contains = [m47, m10];
  m50
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m51..variants = [m52, m53];
  m52
    ..className = ScopeName('type')
    ..begin = RegexSource('[a-zA-Z_]\\w*');
  m53
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [m51];
  return m0;
}
