// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';
import 'package:hilite/src/callbacks.dart' as callbacks;

/// The `latex` language (LaTeX).
Language buildLatex() {
  final m0 = Language(name: 'LaTeX', aliases: ['tex']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode(),
      m37 = Mode(),
      m38 = Mode(),
      m39 = Mode(),
      m40 = Mode(),
      m41 = Mode(),
      m42 = Mode(),
      m43 = Mode(),
      m44 = Mode(),
      m45 = Mode(),
      m46 = Mode(),
      m47 = Mode(),
      m48 = Mode(),
      m49 = Mode(),
      m50 = Mode(),
      m51 = Mode(),
      m52 = Mode(),
      m53 = Mode(),
      m54 = Mode(),
      m55 = Mode(),
      m56 = Mode(),
      m57 = Mode(),
      m58 = Mode(),
      m59 = Mode(),
      m60 = Mode(),
      m61 = Mode(),
      m62 = Mode(),
      m63 = Mode(),
      m64 = Mode(),
      m65 = Mode(),
      m66 = Mode(),
      m67 = Mode(),
      m68 = Mode(),
      m69 = Mode(),
      m70 = Mode(),
      m71 = Mode(),
      m72 = Mode(),
      m73 = Mode(),
      m74 = Mode(),
      m75 = Mode(),
      m76 = Mode(),
      m77 = Mode(),
      m78 = Mode(),
      m79 = Mode(),
      m80 = Mode(),
      m81 = Mode(),
      m82 = Mode(),
      m83 = Mode(),
      m84 = Mode(),
      m85 = Mode(),
      m86 = Mode(),
      m87 = Mode(),
      m88 = Mode(),
      m89 = Mode(),
      m90 = Mode(),
      m91 = Mode(),
      m92 = Mode(),
      m93 = Mode(),
      m94 = Mode(),
      m95 = Mode(),
      m96 = Mode(),
      m97 = Mode(),
      m98 = Mode(),
      m99 = Mode(),
      m100 = Mode(),
      m101 = Mode(),
      m102 = Mode(),
      m103 = Mode(),
      m104 = Mode(),
      m105 = Mode(),
      m106 = Mode(),
      m107 = Mode(),
      m108 = Mode(),
      m109 = Mode(),
      m110 = Mode(),
      m111 = Mode(),
      m112 = Mode(),
      m113 = Mode(),
      m114 = Mode(),
      m115 = Mode(),
      m116 = Mode(),
      m117 = Mode(),
      m118 = Mode(),
      m119 = Mode(),
      m120 = Mode(),
      m121 = Mode();
  m0
    ..contains = [
      m1,
      m2,
      m3,
      m4,
      m5,
      m6,
      m7,
      m8,
      m9,
      m10,
      m11,
      m12,
      m13,
      m14,
      m15,
      m16,
      m17,
      m18,
      m19,
      m20,
      m21,
      m22,
      m23,
      m24,
    ];
  m1
    ..begin = RegexSource('\\\\verb(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\verb'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m26;
  m2
    ..begin = RegexSource('\\\\lstinline(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\lstinline'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m27;
  m3
    ..begin = RegexSource('\\\\mint(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\mint'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m28;
  m4
    ..begin = RegexSource('\\\\mintinline(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\mintinline'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m29;
  m5
    ..begin = RegexSource('\\\\url(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\url'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m30;
  m6
    ..begin = RegexSource('\\\\hyperref(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\hyperref'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m31;
  m7
    ..begin = RegexSource('\\\\href(?![a-zA-Z@:_])')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\href'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m32;
  m8
    ..begin = RegexSource('\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{verbatim\\})')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m33;
  m9
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{filecontents\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m34;
  m10
    ..begin = RegexSource('\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{Verbatim\\})')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m35;
  m11
    ..begin = RegexSource('\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{BVerbatim\\})')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m36;
  m12
    ..begin = RegexSource('\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{LVerbatim\\})')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m37;
  m13
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{verbatim\\*\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m38;
  m14
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{filecontents\\*\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m39;
  m15
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{Verbatim\\*\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m40;
  m16
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{BVerbatim\\*\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m41;
  m17
    ..begin = RegexSource(
      '\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{LVerbatim\\*\\})',
    )
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m42;
  m18
    ..begin = RegexSource('\\\\begin(?=[ \t]*(\\r?\\n[ \t]*)?\\{minted\\})')
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['\\begin'], fromList: false),
    ], pattern: '\\\\[a-zA-Z]+')
    ..relevance = 0
    ..contains = [m25]
    ..starts = m43;
  m19
    ..className = ScopeName('keyword')
    ..begin = RegexSource('\\\\')
    ..relevance = 0
    ..contains = [m44, m45, m46, m47];
  m20
    ..className = ScopeName('params')
    ..relevance = 0
    ..begin = RegexSource('#+\\d?');
  m21..variants = [m48, m49, m50, m51, m52, m53];
  m22
    ..className = ScopeName('built_in')
    ..relevance = 0
    ..begin = RegexSource('[\$&^_]');
  m23
    ..className = ScopeName('meta')
    ..begin = RegexSource('% ?!(T[eE]X|tex|BIB|bib)')
    ..end = RegexSource('\$')
    ..relevance = 10;
  m24
    ..scope = ScopeName('comment')
    ..begin = RegexSource('%')
    ..end = RegexSource('\$')
    ..contains = [m54, m55]
    ..relevance = 0;
  m25
    ..begin = RegexSource('\\s+')
    ..relevance = 0;
  m26..contains = [m56];
  m27..contains = [m57];
  m28
    ..contains = [m25]
    ..starts = m58;
  m29
    ..contains = [m25]
    ..starts = m59;
  m30..contains = [m60, m61];
  m31..contains = [m62];
  m32
    ..contains = [m25]
    ..starts = m63;
  m33
    ..relevance = 0
    ..contains = [m64]
    ..starts = m65;
  m34
    ..relevance = 0
    ..contains = [m64]
    ..starts = m66;
  m35
    ..relevance = 0
    ..contains = [m64]
    ..starts = m67;
  m36
    ..relevance = 0
    ..contains = [m64]
    ..starts = m68;
  m37
    ..relevance = 0
    ..contains = [m64]
    ..starts = m69;
  m38
    ..relevance = 0
    ..contains = [m64]
    ..starts = m70;
  m39
    ..relevance = 0
    ..contains = [m64]
    ..starts = m71;
  m40
    ..relevance = 0
    ..contains = [m64]
    ..starts = m72;
  m41
    ..relevance = 0
    ..contains = [m64]
    ..starts = m73;
  m42
    ..relevance = 0
    ..contains = [m64]
    ..starts = m74;
  m43
    ..relevance = 0
    ..contains = [m64]
    ..starts = m75;
  m44
    ..endsParent = true
    ..begin = RegexSource(
      '(?:(?:NeedsTeXFormat|RequirePackage|GetIdInfo)(?![a-zA-Z@:_])|Provides(?:Expl)?(?:Package|Class|File)(?![a-zA-Z@:_])|(?:DeclareOption|ProcessOptions)(?![a-zA-Z@:_])|(?:documentclass|usepackage|input|include)(?![a-zA-Z@:_])|makeat(?:letter|other)(?![a-zA-Z@:_])|ExplSyntax(?:On|Off)(?![a-zA-Z@:_])|(?:new|renew|provide)?command(?![a-zA-Z@:_])|(?:re)newenvironment(?![a-zA-Z@:_])|(?:New|Renew|Provide|Declare)(?:Expandable)?DocumentCommand(?![a-zA-Z@:_])|(?:New|Renew|Provide|Declare)DocumentEnvironment(?![a-zA-Z@:_])|(?:(?:e|g|x)?def|let)(?![a-zA-Z@:_])|(?:begin|end)(?![a-zA-Z@:_])|(?:part|chapter|(?:sub){0,2}section|(?:sub)?paragraph)(?![a-zA-Z@:_])|caption(?![a-zA-Z@:_])|(?:label|(?:eq|page|name)?ref|(?:paren|foot|super)?cite)(?![a-zA-Z@:_])|(?:alpha|beta|[Gg]amma|[Dd]elta|(?:var)?epsilon|zeta|eta|[Tt]heta|vartheta)(?![a-zA-Z@:_])|(?:iota|(?:var)?kappa|[Ll]ambda|mu|nu|[Xx]i|[Pp]i|varpi|(?:var)rho)(?![a-zA-Z@:_])|(?:[Ss]igma|varsigma|tau|[Uu]psilon|[Pp]hi|varphi|chi|[Pp]si|[Oo]mega)(?![a-zA-Z@:_])|(?:frac|sum|prod|lim|infty|times|sqrt|leq|geq|left|right|middle|[bB]igg?)(?![a-zA-Z@:_])|(?:[lr]angle|q?quad|[lcvdi]?dots|d?dot|hat|tilde|bar)(?![a-zA-Z@:_]))',
    );
  m45
    ..endsParent = true
    ..begin = RegexSource(
      '(?:__)?[a-zA-Z]{2,}_[a-zA-Z](?:_?[a-zA-Z])+:[a-zA-Z]*(?![a-zA-Z:_])|[lgc]__?[a-zA-Z](?:_?[a-zA-Z])*_[a-zA-Z]{2,}(?![a-zA-Z:_])|[qs]__?[a-zA-Z](?:_?[a-zA-Z])+(?![a-zA-Z:_])|use(?:_i)?:[a-zA-Z]*(?![a-zA-Z:_])|(?:else|fi|or):(?![a-zA-Z:_])|(?:if|cs|exp):w(?![a-zA-Z:_])|(?:hbox|vbox):n(?![a-zA-Z:_])|::[a-zA-Z]_unbraced(?![a-zA-Z:_])|::[a-zA-Z:](?![a-zA-Z:_])',
    );
  m46
    ..endsParent = true
    ..variants = [m48, m49, m50, m51, m52, m53];
  m47
    ..endsParent = true
    ..relevance = 0
    ..variants = [m76, m77];
  m48..begin = RegexSource('\\^{6}[0-9a-f]{6}');
  m49..begin = RegexSource('\\^{5}[0-9a-f]{5}');
  m50..begin = RegexSource('\\^{4}[0-9a-f]{4}');
  m51..begin = RegexSource('\\^{3}[0-9a-f]{3}');
  m52..begin = RegexSource('\\^{2}[0-9a-f]{2}');
  m53..begin = RegexSource('\\^{2}[\\u0000-\\u007f]');
  m54
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m55
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m56
    ..className = ScopeName('string')
    ..begin = RegexSource('(.|\\r?\\n)')
    ..end = RegexSource('(.|\\r?\\n)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..endsParent = true
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m57
    ..className = ScopeName('string')
    ..begin = RegexSource('(.|\\r?\\n)')
    ..end = RegexSource('(.|\\r?\\n)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..endsParent = true
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m58
    ..relevance = 0
    ..contains = [m64]
    ..starts = m78;
  m59
    ..relevance = 0
    ..contains = [m64]
    ..starts = m79;
  m60
    ..relevance = 0
    ..begin = RegexSource('\\{')
    ..starts = m80;
  m61
    ..relevance = 0
    ..begin = RegexSource('\\{')
    ..starts = m81;
  m62
    ..relevance = 0
    ..begin = RegexSource('\\{')
    ..starts = m82;
  m63
    ..relevance = 0
    ..contains = [m83]
    ..starts = m84;
  m64
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [m85, m19, m20, m21, m22, m23, m24]
    ..endsParent = true;
  m65
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{verbatim\\})');
  m66
    ..contains = [m25]
    ..starts = m86;
  m67
    ..contains = [m25]
    ..starts = m87;
  m68
    ..contains = [m25]
    ..starts = m88;
  m69
    ..contains = [m25]
    ..starts = m89;
  m70
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{verbatim\\*\\})');
  m71
    ..contains = [m25]
    ..starts = m90;
  m72
    ..contains = [m25]
    ..starts = m91;
  m73
    ..contains = [m25]
    ..starts = m92;
  m74
    ..contains = [m25]
    ..starts = m93;
  m75
    ..contains = [m25]
    ..starts = m94;
  m76..begin = RegexSource('[a-zA-Z@]+');
  m77..begin = RegexSource('[^a-zA-Z@]?');
  m78..contains = [m95];
  m79..contains = [m96, m97];
  m80
    ..endsParent = true
    ..contains = [m98];
  m81
    ..endsParent = true
    ..contains = [m99];
  m82
    ..endsParent = true
    ..contains = [m100];
  m83
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\]')
    ..endsParent = true
    ..relevance = 0
    ..contains = [m85, m19, m20, m21, m22, m23, m24];
  m84..contains = [m101];
  m85
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self, m19, m20, m21, m22, m23, m24];
  m86
    ..relevance = 0
    ..contains = [m64]
    ..starts = m102;
  m87
    ..relevance = 0
    ..contains = [m83]
    ..starts = m103;
  m88
    ..relevance = 0
    ..contains = [m83]
    ..starts = m104;
  m89
    ..relevance = 0
    ..contains = [m83]
    ..starts = m105;
  m90
    ..relevance = 0
    ..contains = [m64]
    ..starts = m106;
  m91
    ..relevance = 0
    ..contains = [m83]
    ..starts = m107;
  m92
    ..relevance = 0
    ..contains = [m83]
    ..starts = m108;
  m93
    ..relevance = 0
    ..contains = [m83]
    ..starts = m109;
  m94
    ..relevance = 0
    ..contains = [m83]
    ..starts = m110;
  m95
    ..className = ScopeName('string')
    ..begin = RegexSource('(.|\\r?\\n)')
    ..end = RegexSource('(.|\\r?\\n)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..endsParent = true
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m96
    ..relevance = 0
    ..begin = RegexSource('\\{')
    ..starts = m111;
  m97
    ..className = ScopeName('string')
    ..begin = RegexSource('(.|\\r?\\n)')
    ..end = RegexSource('(.|\\r?\\n)')
    ..excludeBegin = true
    ..excludeEnd = true
    ..endsParent = true
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m98
    ..className = ScopeName('link')
    ..end = RegexSource('(?=\\})')
    ..endsParent = true
    ..contains = [m112];
  m99
    ..className = ScopeName('link')
    ..end = RegexSource('(?=\\})')
    ..endsParent = true
    ..contains = [m113];
  m100
    ..className = ScopeName('link')
    ..end = RegexSource('(?=\\})')
    ..endsParent = true
    ..contains = [m114];
  m101
    ..relevance = 0
    ..begin = RegexSource('\\{')
    ..starts = m115;
  m102
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{filecontents\\})');
  m103
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{Verbatim\\})');
  m104
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{BVerbatim\\})');
  m105
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{LVerbatim\\})');
  m106
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{filecontents\\*\\})');
  m107
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{Verbatim\\*\\})');
  m108
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{BVerbatim\\*\\})');
  m109
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{LVerbatim\\*\\})');
  m110
    ..contains = [m25]
    ..starts = m116;
  m111
    ..endsParent = true
    ..contains = [m117];
  m112
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self];
  m113
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self];
  m114
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self];
  m115
    ..endsParent = true
    ..contains = [m118];
  m116
    ..relevance = 0
    ..contains = [m64]
    ..starts = m119;
  m117
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\})')
    ..endsParent = true
    ..contains = [m120];
  m118
    ..className = ScopeName('link')
    ..end = RegexSource('(?=\\})')
    ..endsParent = true
    ..contains = [m121];
  m119
    ..className = ScopeName('string')
    ..end = RegexSource('(?=\\\\end\\{minted\\})');
  m120
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self];
  m121
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..relevance = 0
    ..contains = [self];
  return m0;
}
