// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `ldif` language (LDIF).
Language buildLdif() {
  final m0 = Language(name: 'LDIF');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode();
  m0..contains = [m1, m2, m3, m4];
  m1
    ..className = ScopeName('attribute')
    ..match = RegexSource('^dn(?=:)')
    ..relevance = 10;
  m2
    ..className = ScopeName('attribute')
    ..match = RegexSource('^\\w+(?=:)');
  m3
    ..className = ScopeName('literal')
    ..match = RegexSource('^-');
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m5, m6]
    ..frozen = true;
  m5
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m6
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  return m0;
}
