// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `leaf` language (Leaf).
Language buildLeaf() {
  final m0 = Language(name: 'Leaf');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode();
  m0..contains = [m1, m2];
  m1
    ..match = RegexList(['#+', '([A-Za-z_][A-Za-z_0-9]*)?', '(?=\\()'])
    ..scope = ScopeGroups({1: 'punctuation', 2: 'keyword'})
    ..starts = m3
    ..contains = [m4];
  m2
    ..match = RegexList(['#+', '([A-Za-z_][A-Za-z_0-9]*)?', ':?'])
    ..scope = ScopeGroups({1: 'punctuation', 2: 'keyword', 3: 'punctuation'});
  m3..contains = [m5];
  m4
    ..scope = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)(?=\\:?)')
    ..endsParent = true
    ..relevance = 7
    ..contains = [m6, m7, m8, m9, m10];
  m5
    ..match = RegexSource('\\:')
    ..scope = ScopeName('punctuation');
  m6
    ..match = RegexList(['([A-Za-z_][A-Za-z_0-9]*)?', '(?=\\()'])
    ..scope = ScopeGroups({1: 'keyword'})
    ..contains = [m4];
  m7
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m8
    ..scope = ScopeName('keyword')
    ..match = RegexSource('\\b(?:true|false|in)\\b');
  m9
    ..scope = ScopeName('variable')
    ..match = RegexSource('[A-Za-z_][A-Za-z_0-9]*');
  m10
    ..scope = ScopeName('operator')
    ..match = RegexSource(
      '\\+|\\-|\\*|\\/|\\%|\\=\\=|\\=|\\!|\\>|\\<|\\&\\&|\\|\\|',
    );
  return m0;
}
