// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';
import 'package:hilite/src/callbacks.dart' as callbacks;

/// The `lisp` language (Lisp).
Language buildLisp() {
  final m0 = Language(name: 'Lisp');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode();
  m0
    ..illegal = RegexSource('\\S')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..className = ScopeName('number')
    ..variants = [m10, m11, m12, m13, m14];
  m2
    ..scope = ScopeName('meta')
    ..begin = RegexSource('^#![ ]*\\/')
    ..end = RegexSource('\$')
    ..relevance = 0
    ..onBegin = callbacks.shebangOnBegin;
  m3
    ..className = ScopeName('literal')
    ..begin = RegexSource('\\b(t{1}|nil)\\b');
  m4
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..setJsNull(ModeKey.illegal)
    ..contains = [m15];
  m5
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m16, m17]
    ..relevance = 0;
  m6
    ..contains = [m1, m4, m18, m19, m20, m9]
    ..variants = [m21, m22, m23];
  m7..variants = [m24, m25];
  m8
    ..begin = RegexSource('\\(\\s*')
    ..end = RegexSource('\\)')
    ..contains = [m26, m27];
  m9
    ..begin = RegexSource('[a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*')
    ..relevance = 0;
  m10
    ..begin = RegexSource(
      '(-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s|D|E|F|L|S)(\\+|-)?\\d+)?',
    )
    ..relevance = 0;
  m11..begin = RegexSource('#(b|B)[0-1]+(/[0-1]+)?');
  m12..begin = RegexSource('#(o|O)[0-7]+(/[0-7]+)?');
  m13..begin = RegexSource('#(x|X)[0-9a-fA-F]+(/[0-9a-fA-F]+)?');
  m14
    ..begin = RegexSource(
      '#(c|C)\\((-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s|D|E|F|L|S)(\\+|-)?\\d+)? +(-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s|D|E|F|L|S)(\\+|-)?\\d+)?',
    )
    ..end = RegexSource('\\)');
  m15
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m18
    ..scope = ScopeName('variable')
    ..match = RegexSource('\\*[^\\s()*]+\\*');
  m19
    ..className = ScopeName('symbol')
    ..begin = RegexSource(
      '[:&][a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*',
    );
  m20
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..contains = [self, m3, m4, m1, m9];
  m21
    ..begin = RegexSource('[\'`]\\(')
    ..end = RegexSource('\\)');
  m22
    ..begin = RegexSource('\\(quote ')
    ..end = RegexSource('\\)')
    ..keywords = RawKeywords([
      (scope: 'name', words: ['quote'], fromList: false),
    ]);
  m23..begin = RegexSource('\'\\|[^]*?\\|');
  m24
    ..begin = RegexSource(
      '\'[a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*',
    );
  m25
    ..begin = RegexSource(
      '#\'[a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*(::[a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*)*',
    );
  m26
    ..className = ScopeName('name')
    ..variants = [m28, m29];
  m27
    ..endsWithParent = true
    ..relevance = 0
    ..contains = [m6, m7, m8, m3, m1, m4, m5, m18, m19, m30, m9];
  m28
    ..begin = RegexSource('[a-zA-Z_\\-+\\*\\/<=>&#][a-zA-Z0-9_\\-+*\\/<=>&#!]*')
    ..relevance = 0;
  m29..begin = RegexSource('\\|[^]*?\\|');
  m30..begin = RegexSource('\\|[^]*?\\|');
  return m0;
}
