// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `llvm` language (LLVM IR).
Language buildLlvm() {
  final m0 = Language(name: 'LLVM IR');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'begin',
          'end',
          'true',
          'false',
          'declare',
          'define',
          'global',
          'constant',
          'private',
          'linker_private',
          'internal',
          'available_externally',
          'linkonce',
          'linkonce_odr',
          'weak',
          'weak_odr',
          'appending',
          'dllimport',
          'dllexport',
          'common',
          'default',
          'hidden',
          'protected',
          'extern_weak',
          'external',
          'thread_local',
          'zeroinitializer',
          'undef',
          'null',
          'to',
          'tail',
          'target',
          'triple',
          'datalayout',
          'volatile',
          'nuw',
          'nsw',
          'nnan',
          'ninf',
          'nsz',
          'arcp',
          'fast',
          'exact',
          'inbounds',
          'align',
          'addrspace',
          'section',
          'alias',
          'module',
          'asm',
          'sideeffect',
          'gc',
          'dbg',
          'linker_private_weak',
          'attributes',
          'blockaddress',
          'initialexec',
          'localdynamic',
          'localexec',
          'prefix',
          'unnamed_addr',
          'ccc',
          'fastcc',
          'coldcc',
          'x86_stdcallcc',
          'x86_fastcallcc',
          'arm_apcscc',
          'arm_aapcscc',
          'arm_aapcs_vfpcc',
          'ptx_device',
          'ptx_kernel',
          'intel_ocl_bicc',
          'msp430_intrcc',
          'spir_func',
          'spir_kernel',
          'x86_64_sysvcc',
          'x86_64_win64cc',
          'x86_thiscallcc',
          'cc',
          'c',
          'signext',
          'zeroext',
          'inreg',
          'sret',
          'nounwind',
          'noreturn',
          'noalias',
          'nocapture',
          'byval',
          'nest',
          'readnone',
          'readonly',
          'inlinehint',
          'noinline',
          'alwaysinline',
          'optsize',
          'ssp',
          'sspreq',
          'noredzone',
          'noimplicitfloat',
          'naked',
          'builtin',
          'cold',
          'nobuiltin',
          'noduplicate',
          'nonlazybind',
          'optnone',
          'returns_twice',
          'sanitize_address',
          'sanitize_memory',
          'sanitize_thread',
          'sspstrong',
          'uwtable',
          'returned',
          'type',
          'opaque',
          'eq',
          'ne',
          'slt',
          'sgt',
          'sle',
          'sge',
          'ult',
          'ugt',
          'ule',
          'uge',
          'oeq',
          'one',
          'olt',
          'ogt',
          'ole',
          'oge',
          'ord',
          'uno',
          'ueq',
          'une',
          'x',
          'acq_rel',
          'acquire',
          'alignstack',
          'atomic',
          'catch',
          'cleanup',
          'filter',
          'inteldialect',
          'max',
          'min',
          'monotonic',
          'nand',
          'personality',
          'release',
          'seq_cst',
          'singlethread',
          'umax',
          'umin',
          'unordered',
          'xchg',
          'add',
          'fadd',
          'sub',
          'fsub',
          'mul',
          'fmul',
          'udiv',
          'sdiv',
          'fdiv',
          'urem',
          'srem',
          'frem',
          'shl',
          'lshr',
          'ashr',
          'and',
          'or',
          'xor',
          'icmp',
          'fcmp',
          'phi',
          'call',
          'trunc',
          'zext',
          'sext',
          'fptrunc',
          'fpext',
          'uitofp',
          'sitofp',
          'fptoui',
          'fptosi',
          'inttoptr',
          'ptrtoint',
          'bitcast',
          'addrspacecast',
          'select',
          'va_arg',
          'ret',
          'br',
          'switch',
          'invoke',
          'unwind',
          'unreachable',
          'indirectbr',
          'landingpad',
          'resume',
          'malloc',
          'alloca',
          'free',
          'load',
          'store',
          'getelementptr',
          'extractelement',
          'insertelement',
          'shufflevector',
          'getresult',
          'extractvalue',
          'insertvalue',
          'atomicrmw',
          'cmpxchg',
          'fence',
          'argmemonly',
        ],
        fromList: false,
      ),
      (
        scope: 'type',
        words: [
          'void',
          'half',
          'bfloat',
          'float',
          'double',
          'fp128',
          'x86_fp80',
          'ppc_fp128',
          'x86_amx',
          'x86_mmx',
          'ptr',
          'label',
          'token',
          'metadata',
          'opaque',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11];
  m1
    ..className = ScopeName('type')
    ..begin = RegexSource('\\bi\\d+(?=\\s|\\b)');
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';\\s*\$')
    ..setJsNull(ModeKey.end)
    ..contains = [m12, m13]
    ..relevance = 0;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m14, m15];
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m16, m17]
    ..frozen = true;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m18];
  m6
    ..className = ScopeName('title')
    ..variants = [m19, m20, m21, m22, m23];
  m7
    ..className = ScopeName('punctuation')
    ..relevance = 0
    ..begin = RegexSource(',');
  m8
    ..className = ScopeName('operator')
    ..relevance = 0
    ..begin = RegexSource('=');
  m9
    ..className = ScopeName('variable')
    ..variants = [m24, m25, m26];
  m10
    ..className = ScopeName('symbol')
    ..variants = [m27]
    ..relevance = 0;
  m11
    ..className = ScopeName('number')
    ..variants = [m28, m29]
    ..relevance = 0;
  m12
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m13
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m16
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m17
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m18
    ..className = ScopeName('char.escape')
    ..match = RegexSource('\\\\\\d\\d');
  m19..begin = RegexSource('@([-a-zA-Z\$._][\\w\$.-]*)');
  m20..begin = RegexSource('@\\d+');
  m21..begin = RegexSource('!([-a-zA-Z\$._][\\w\$.-]*)');
  m22..begin = RegexSource('!\\d+([-a-zA-Z\$._][\\w\$.-]*)');
  m23..begin = RegexSource('!\\d+');
  m24..begin = RegexSource('%([-a-zA-Z\$._][\\w\$.-]*)');
  m25..begin = RegexSource('%\\d+');
  m26..begin = RegexSource('#\\d+');
  m27..begin = RegexSource('^\\s*[a-z]+:');
  m28..begin = RegexSource('[su]?0[xX][KMLHR]?[a-fA-F0-9]+');
  m29
    ..begin = RegexSource(
      '[-+]?\\d+(?:[.]\\d+)?(?:[eE][-+]?\\d+(?:[.]\\d+)?)?',
    );
  return m0;
}
