// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `mercury` language (Mercury).
Language buildMercury() {
  final m0 = Language(name: 'Mercury', aliases: ['m', 'moo']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'module',
          'use_module',
          'import_module',
          'include_module',
          'end_module',
          'initialise',
          'mutable',
          'initialize',
          'finalize',
          'finalise',
          'interface',
          'implementation',
          'pred',
          'mode',
          'func',
          'type',
          'inst',
          'solver',
          'any_pred',
          'any_func',
          'is',
          'semidet',
          'det',
          'nondet',
          'multi',
          'erroneous',
          'failure',
          'cc_nondet',
          'cc_multi',
          'typeclass',
          'instance',
          'where',
          'pragma',
          'promise',
          'external',
          'trace',
          'atomic',
          'or_else',
          'require_complete_switch',
          'require_det',
          'require_semidet',
          'require_multi',
          'require_nondet',
          'require_cc_multi',
          'require_cc_nondet',
          'require_erroneous',
          'require_failure',
        ],
        fromList: false,
      ),
      (
        scope: 'meta',
        words: [
          'inline',
          'no_inline',
          'type_spec',
          'source_file',
          'fact_table',
          'obsolete',
          'memo',
          'loop_check',
          'minimal_model',
          'terminates',
          'does_not_terminate',
          'check_termination',
          'promise_equivalent_clauses',
          'foreign_proc',
          'foreign_decl',
          'foreign_code',
          'foreign_type',
          'foreign_import_module',
          'foreign_export_enum',
          'foreign_export',
          'foreign_enum',
          'may_call_mercury',
          'will_not_call_mercury',
          'thread_safe',
          'not_thread_safe',
          'maybe_thread_safe',
          'promise_pure',
          'promise_semipure',
          'tabled_for_io',
          'local',
          'untrailed',
          'trailed',
          'attach_to_io_state',
          'can_pass_as_mercury_type',
          'stable',
          'will_not_throw_exception',
          'may_modify_trail',
          'will_not_modify_trail',
          'may_duplicate',
          'may_not_duplicate',
          'affects_liveness',
          'does_not_affect_liveness',
          'doesnt_affect_liveness',
          'no_sharing',
          'unknown_sharing',
          'sharing',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'some',
          'all',
          'not',
          'if',
          'then',
          'else',
          'true',
          'fail',
          'false',
          'try',
          'catch',
          'catch_any',
          'semidet_true',
          'semidet_false',
          'semidet_fail',
          'impure_true',
          'impure',
          'semipure',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..className = ScopeName('built_in')
    ..variants = [m11, m12, m13, m14, m15];
  m2
    ..className = ScopeName('built_in')
    ..variants = [m16, m17];
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('%')
    ..end = RegexSource('\$')
    ..contains = [m18, m19];
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m20, m21]
    ..frozen = true;
  m5
    ..className = ScopeName('number')
    ..begin = RegexSource('0\'.\\|0[box][0-9a-fA-F]*');
  m6
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m7
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m22]
    ..relevance = 0;
  m8
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m22, m23]
    ..relevance = 0;
  m9..begin = RegexSource(':-');
  m10..begin = RegexSource('\\.\$');
  m11..begin = RegexSource('<=>');
  m12
    ..begin = RegexSource('<=')
    ..relevance = 0;
  m13
    ..begin = RegexSource('=>')
    ..relevance = 0;
  m14..begin = RegexSource('/\\\\');
  m15..begin = RegexSource('\\\\/');
  m16..begin = RegexSource(':-\\|-->');
  m17
    ..begin = RegexSource('=')
    ..relevance = 0;
  m18
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m19
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m20
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m21
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m22
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m23
    ..className = ScopeName('subst')
    ..begin = RegexSource(
      '\\\\[abfnrtv]\\|\\\\x[0-9a-fA-F]*\\\\\\|%[-+# *.0-9]*[dioxXucsfeEgGp]',
    )
    ..relevance = 0;
  return m0;
}
