// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `mipsasm` language (MIPS Assembly).
Language buildMipsasm() {
  final m0 = Language(
    name: 'MIPS Assembly',
    aliases: ['mips'],
    caseInsensitive: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'meta',
        words: [
          '.2byte',
          '.4byte',
          '.align',
          '.ascii',
          '.asciz',
          '.balign',
          '.byte',
          '.code',
          '.data',
          '.else',
          '.end',
          '.endif',
          '.endm',
          '.endr',
          '.equ',
          '.err',
          '.exitm',
          '.extern',
          '.global',
          '.hword',
          '.if',
          '.ifdef',
          '.ifndef',
          '.include',
          '.irp',
          '.long',
          '.macro',
          '.rept',
          '.req',
          '.section',
          '.set',
          '.skip',
          '.space',
          '.text',
          '.word',
          '.ltorg',
          '',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          '\$0',
          '\$1',
          '\$2',
          '\$3',
          '\$4',
          '\$5',
          '\$6',
          '\$7',
          '\$8',
          '\$9',
          '\$10',
          '\$11',
          '\$12',
          '\$13',
          '\$14',
          '\$15',
          '\$16',
          '\$17',
          '\$18',
          '\$19',
          '\$20',
          '\$21',
          '\$22',
          '\$23',
          '\$24',
          '\$25',
          '\$26',
          '\$27',
          '\$28',
          '\$29',
          '\$30',
          '\$31',
          'zero',
          'at',
          'v0',
          'v1',
          'a0',
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          't0',
          't1',
          't2',
          't3',
          't4',
          't5',
          't6',
          't7',
          't8',
          't9',
          's0',
          's1',
          's2',
          's3',
          's4',
          's5',
          's6',
          's7',
          's8',
          'k0',
          'k1',
          'gp',
          'sp',
          'fp',
          'ra',
          '\$f0',
          '\$f1',
          '\$f2',
          '\$f2',
          '\$f4',
          '\$f5',
          '\$f6',
          '\$f7',
          '\$f8',
          '\$f9',
          '\$f10',
          '\$f11',
          '\$f12',
          '\$f13',
          '\$f14',
          '\$f15',
          '\$f16',
          '\$f17',
          '\$f18',
          '\$f19',
          '\$f20',
          '\$f21',
          '\$f22',
          '\$f23',
          '\$f24',
          '\$f25',
          '\$f26',
          '\$f27',
          '\$f28',
          '\$f29',
          '\$f30',
          '\$f31',
          'Context',
          'Random',
          'EntryLo0',
          'EntryLo1',
          'Context',
          'PageMask',
          'Wired',
          'EntryHi',
          'HWREna',
          'BadVAddr',
          'Count',
          'Compare',
          'SR',
          'IntCtl',
          'SRSCtl',
          'SRSMap',
          'Cause',
          'EPC',
          'PRId',
          'EBase',
          'Config',
          'Config1',
          'Config2',
          'Config3',
          'LLAddr',
          'Debug',
          'DEPC',
          'DESAVE',
          'CacheErr',
          'ECC',
          'ErrorEPC',
          'TagLo',
          'DataLo',
          'TagHi',
          'DataHi',
          'WatchLo',
          'WatchHi',
          'PerfCtl',
          'PerfCnt',
          '',
        ],
        fromList: false,
      ),
    ], pattern: '\\.?[a-zA-Z]\\w*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8]
    ..illegal = RegexSource('\\/');
  m1
    ..className = ScopeName('keyword')
    ..begin = RegexSource(
      '\\b(addi?u?|andi?|b(al)?|beql?|bgez(al)?l?|bgtzl?|blezl?|bltz(al)?l?|bnel?|cl[oz]|divu?|ext|ins|j(al)?|jalr(\\.hb)?|jr(\\.hb)?|lbu?|lhu?|ll|lui|lw[lr]?|maddu?|mfhi|mflo|movn|movz|move|msubu?|mthi|mtlo|mul|multu?|nop|nor|ori?|rotrv?|sb|sc|se[bh]|sh|sllv?|slti?u?|srav?|srlv?|subu?|sw[lr]?|xori?|wsbh|abs\\.[sd]|add\\.[sd]|alnv.ps|bc1[ft]l?|c\\.(s?f|un|u?eq|[ou]lt|[ou]le|ngle?|seq|l[et]|ng[et])\\.[sd]|(ceil|floor|round|trunc)\\.[lw]\\.[sd]|cfc1|cvt\\.d\\.[lsw]|cvt\\.l\\.[dsw]|cvt\\.ps\\.s|cvt\\.s\\.[dlw]|cvt\\.s\\.p[lu]|cvt\\.w\\.[dls]|div\\.[ds]|ldx?c1|luxc1|lwx?c1|madd\\.[sd]|mfc1|mov[fntz]?\\.[ds]|msub\\.[sd]|mth?c1|mul\\.[ds]|neg\\.[ds]|nmadd\\.[ds]|nmsub\\.[ds]|p[lu][lu]\\.ps|recip\\.fmt|r?sqrt\\.[ds]|sdx?c1|sub\\.[ds]|suxc1|swx?c1|break|cache|d?eret|[de]i|ehb|mfc0|mtc0|pause|prefx?|rdhwr|rdpgpr|sdbbp|ssnop|synci?|syscall|teqi?|tgei?u?|tlb(p|r|w[ir])|tlti?u?|tnei?|wait|wrpgpr)',
    )
    ..end = RegexSource('\\s');
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('[;#](?!\\s*\$)')
    ..end = RegexSource('\$')
    ..contains = [m9, m10];
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m11, m12]
    ..frozen = true;
  m4
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m13]
    ..frozen = true;
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('[^\\\\]\'')
    ..relevance = 0;
  m6
    ..className = ScopeName('title')
    ..begin = RegexSource('\\|')
    ..end = RegexSource('\\|')
    ..illegal = RegexSource('\\n')
    ..relevance = 0;
  m7
    ..className = ScopeName('number')
    ..variants = [m14, m15]
    ..relevance = 0;
  m8
    ..className = ScopeName('symbol')
    ..variants = [m16, m17, m18]
    ..relevance = 0;
  m9
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m10
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m11
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m12
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m13
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m14..begin = RegexSource('0x[0-9a-f]+');
  m15..begin = RegexSource('\\b-?\\d+');
  m16..begin = RegexSource('^\\s*[a-z_\\.\\\$][a-z0-9_\\.\\\$]+:');
  m17..begin = RegexSource('^\\s*[0-9]+:');
  m18..begin = RegexSource('[0-9]+[bf]');
  return m0;
}
