// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `moonscript` language (MoonScript).
Language buildMoonscript() {
  final m0 = Language(name: 'MoonScript', aliases: ['moon']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'if',
          'then',
          'not',
          'for',
          'in',
          'while',
          'do',
          'return',
          'else',
          'elseif',
          'break',
          'continue',
          'switch',
          'and',
          'or',
          'unless',
          'when',
          'class',
          'extends',
          'super',
          'local',
          'import',
          'export',
          'from',
          'using',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'nil'], fromList: false),
      (
        scope: 'built_in',
        words: [
          '_G',
          '_VERSION',
          'assert',
          'collectgarbage',
          'dofile',
          'error',
          'getfenv',
          'getmetatable',
          'ipairs',
          'load',
          'loadfile',
          'loadstring',
          'module',
          'next',
          'pairs',
          'pcall',
          'print',
          'rawequal',
          'rawget',
          'rawset',
          'require',
          'select',
          'setfenv',
          'setmetatable',
          'tonumber',
          'tostring',
          'type',
          'unpack',
          'xpcall',
          'coroutine',
          'debug',
          'io',
          'math',
          'os',
          'package',
          'string',
          'table',
        ],
        fromList: false,
      ),
    ])
    ..illegal = RegexSource('\\/\\*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..starts = m11;
  m2
    ..className = ScopeName('string')
    ..variants = [m12, m13];
  m3
    ..className = ScopeName('built_in')
    ..begin = RegexSource('@__[a-zA-Z]\\w*');
  m4..begin = RegexSource('@[a-zA-Z]\\w*');
  m5..begin = RegexSource('[a-zA-Z]\\w*\\\\[a-zA-Z]\\w*');
  m6
    ..scope = ScopeName('comment')
    ..begin = RegexSource('--')
    ..end = RegexSource('\$')
    ..contains = [m14, m15];
  m7
    ..className = ScopeName('function')
    ..begin = RegexSource(
      '^\\s*[A-Za-z\$_][0-9A-Za-z\$_]*\\s*=\\s*(\\(.*\\)\\s*)?\\B[-=]>',
    )
    ..end = RegexSource('[-=]>')
    ..returnBegin = true
    ..contains = [m16, m17];
  m8
    ..begin = RegexSource('[\\(,:=]\\s*')
    ..relevance = 0
    ..contains = [m18];
  m9
    ..className = ScopeName('class')
    ..beginKeywords = 'class'
    ..end = RegexSource('\$')
    ..illegal = RegexSource('[:="\\[\\]]')
    ..contains = [m19, m16];
  m10
    ..className = ScopeName('name')
    ..begin = RegexSource('[A-Za-z\$_][0-9A-Za-z\$_]*:')
    ..end = RegexSource(':')
    ..returnBegin = true
    ..returnEnd = true
    ..relevance = 0;
  m11
    ..end = RegexSource('(\\s*/)?')
    ..relevance = 0;
  m12
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m20];
  m13
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m20, m21];
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m16
    ..scope = ScopeName('title')
    ..begin = RegexSource('[A-Za-z\$_][0-9A-Za-z\$_]*')
    ..relevance = 0;
  m17
    ..className = ScopeName('params')
    ..begin = RegexSource('\\([^\\(]')
    ..returnBegin = true
    ..contains = [m22];
  m18
    ..className = ScopeName('function')
    ..begin = RegexSource('(\\(.*\\)\\s*)?\\B[-=]>')
    ..end = RegexSource('[-=]>')
    ..returnBegin = true
    ..contains = [m17];
  m19
    ..beginKeywords = 'extends'
    ..endsWithParent = true
    ..illegal = RegexSource('[:="\\[\\]]')
    ..contains = [m16];
  m20
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m21
    ..className = ScopeName('subst')
    ..begin = RegexSource('#\\{')
    ..end = RegexSource('\\}')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'if',
          'then',
          'not',
          'for',
          'in',
          'while',
          'do',
          'return',
          'else',
          'elseif',
          'break',
          'continue',
          'switch',
          'and',
          'or',
          'unless',
          'when',
          'class',
          'extends',
          'super',
          'local',
          'import',
          'export',
          'from',
          'using',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'nil'], fromList: false),
      (
        scope: 'built_in',
        words: [
          '_G',
          '_VERSION',
          'assert',
          'collectgarbage',
          'dofile',
          'error',
          'getfenv',
          'getmetatable',
          'ipairs',
          'load',
          'loadfile',
          'loadstring',
          'module',
          'next',
          'pairs',
          'pcall',
          'print',
          'rawequal',
          'rawget',
          'rawset',
          'require',
          'select',
          'setfenv',
          'setmetatable',
          'tonumber',
          'tostring',
          'type',
          'unpack',
          'xpcall',
          'coroutine',
          'debug',
          'io',
          'math',
          'os',
          'package',
          'string',
          'table',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5];
  m22
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'if',
          'then',
          'not',
          'for',
          'in',
          'while',
          'do',
          'return',
          'else',
          'elseif',
          'break',
          'continue',
          'switch',
          'and',
          'or',
          'unless',
          'when',
          'class',
          'extends',
          'super',
          'local',
          'import',
          'export',
          'from',
          'using',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'nil'], fromList: false),
      (
        scope: 'built_in',
        words: [
          '_G',
          '_VERSION',
          'assert',
          'collectgarbage',
          'dofile',
          'error',
          'getfenv',
          'getmetatable',
          'ipairs',
          'load',
          'loadfile',
          'loadstring',
          'module',
          'next',
          'pairs',
          'pcall',
          'print',
          'rawequal',
          'rawget',
          'rawset',
          'require',
          'select',
          'setfenv',
          'setmetatable',
          'tonumber',
          'tostring',
          'type',
          'unpack',
          'xpcall',
          'coroutine',
          'debug',
          'io',
          'math',
          'os',
          'package',
          'string',
          'table',
        ],
        fromList: false,
      ),
    ])
    ..contains = [self, m1, m2, m3, m4, m5];
  return m0;
}
