// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `nginx` language (Nginx config).
Language buildNginx() {
  final m0 = Language(name: 'Nginx config', aliases: ['nginxconf']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode();
  m0
    ..contains = [m1, m2, m3, m4]
    ..illegal = RegexSource('[^\\s\\}\\{]');
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m5, m6]
    ..frozen = true;
  m2
    ..beginKeywords = 'upstream location'
    ..end = RegexSource(';|\\{')
    ..contains = [m1, m7, m8, m9, m10, m11, m12]
    ..keywords = RawKeywords([
      (scope: 'section', words: ['upstream', 'location'], fromList: false),
    ]);
  m3
    ..className = ScopeName('section')
    ..begin = RegexSource('[a-zA-Z_]\\w*(?=\\s+\\{)')
    ..relevance = 0;
  m4
    ..begin = RegexSource('(?=[a-zA-Z_]\\w*\\s)')
    ..end = RegexSource(';|\\{')
    ..contains = [m13]
    ..relevance = 0;
  m5
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m6
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m7
    ..className = ScopeName('string')
    ..contains = [m14, m12]
    ..variants = [m15, m16];
  m8
    ..begin = RegexSource('([a-z]+):/')
    ..end = RegexSource('\\s')
    ..endsWithParent = true
    ..excludeEnd = true
    ..contains = [m12];
  m9
    ..className = ScopeName('regexp')
    ..contains = [m14, m12]
    ..variants = [m17, m18, m19, m20];
  m10
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}(:\\d{1,5})?\\b',
    );
  m11
    ..className = ScopeName('number')
    ..begin = RegexSource('\\b\\d+[kKmMgGdshdwy]?\\b')
    ..relevance = 0;
  m12
    ..className = ScopeName('variable')
    ..variants = [m21, m22, m23];
  m13
    ..className = ScopeName('attribute')
    ..begin = RegexSource('[a-zA-Z_]\\w*')
    ..starts = m24;
  m14
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m15
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m16
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m17
    ..begin = RegexSource('\\s\\^')
    ..end = RegexSource('\\s|\\{|;')
    ..returnEnd = true;
  m18
    ..begin = RegexSource('~\\*?\\s+')
    ..end = RegexSource('\\s|\\{|;')
    ..returnEnd = true;
  m19..begin = RegexSource('\\*(\\.[a-z\\-]+)+');
  m20..begin = RegexSource('([a-z\\-]+\\.)+\\*');
  m21..begin = RegexSource('\\\$\\d+');
  m22..begin = RegexSource('\\\$\\{\\w+\\}');
  m23..begin = RegexSource('[\$@][a-zA-Z_]\\w*');
  m24
    ..endsWithParent = true
    ..keywords = RawKeywords([
      (
        scope: 'literal',
        words: [
          'on',
          'off',
          'yes',
          'no',
          'true',
          'false',
          'none',
          'blocked',
          'debug',
          'info',
          'notice',
          'warn',
          'error',
          'crit',
          'select',
          'break',
          'last',
          'permanent',
          'redirect',
          'kqueue',
          'rtsig',
          'epoll',
          'poll',
          '/dev/poll',
        ],
        fromList: true,
      ),
    ], pattern: '[a-z_]{2,}|\\/dev\\/poll')
    ..relevance = 0
    ..illegal = RegexSource('=>')
    ..contains = [m1, m7, m8, m9, m10, m11, m12];
  return m0;
}
