// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `nim` language (Nim).
Language buildNim() {
  final m0 = Language(name: 'Nim');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'addr',
          'and',
          'as',
          'asm',
          'bind',
          'block',
          'break',
          'case',
          'cast',
          'concept',
          'const',
          'continue',
          'converter',
          'defer',
          'discard',
          'distinct',
          'div',
          'do',
          'elif',
          'else',
          'end',
          'enum',
          'except',
          'export',
          'finally',
          'for',
          'from',
          'func',
          'generic',
          'guarded',
          'if',
          'import',
          'in',
          'include',
          'interface',
          'is',
          'isnot',
          'iterator',
          'let',
          'macro',
          'method',
          'mixin',
          'mod',
          'nil',
          'not',
          'notin',
          'object',
          'of',
          'or',
          'out',
          'proc',
          'ptr',
          'raise',
          'ref',
          'return',
          'shared',
          'shl',
          'shr',
          'static',
          'template',
          'try',
          'tuple',
          'type',
          'using',
          'var',
          'when',
          'while',
          'with',
          'without',
          'xor',
          'yield',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['true', 'false'], fromList: true),
      (
        scope: 'type',
        words: [
          'int',
          'int8',
          'int16',
          'int32',
          'int64',
          'uint',
          'uint8',
          'uint16',
          'uint32',
          'uint64',
          'float',
          'float32',
          'float64',
          'bool',
          'char',
          'string',
          'cstring',
          'pointer',
          'expr',
          'stmt',
          'void',
          'auto',
          'any',
          'range',
          'array',
          'openarray',
          'varargs',
          'seq',
          'set',
          'clong',
          'culong',
          'cchar',
          'cschar',
          'cshort',
          'cint',
          'csize',
          'clonglong',
          'cfloat',
          'cdouble',
          'clongdouble',
          'cuchar',
          'cushort',
          'cuint',
          'culonglong',
          'cstringarray',
          'semistatic',
        ],
        fromList: true,
      ),
      (
        scope: 'built_in',
        words: ['stdin', 'stdout', 'stderr', 'result'],
        fromList: true,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7];
  m1
    ..className = ScopeName('meta')
    ..begin = RegexSource('\\{\\.')
    ..end = RegexSource('\\.\\}')
    ..relevance = 10;
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource('[a-zA-Z]\\w*"')
    ..end = RegexSource('"')
    ..contains = [m8];
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('([a-zA-Z]\\w*)?"""')
    ..end = RegexSource('"""');
  m4
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m9]
    ..frozen = true;
  m5
    ..className = ScopeName('type')
    ..begin = RegexSource('\\b[A-Z]\\w+\\b')
    ..relevance = 0;
  m6
    ..className = ScopeName('number')
    ..relevance = 0
    ..variants = [m10, m11, m12, m13];
  m7
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m14, m15]
    ..frozen = true;
  m8..begin = RegexSource('""');
  m9
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m10
    ..begin = RegexSource(
      '\\b(0[xX][0-9a-fA-F][_0-9a-fA-F]*)(\'?[iIuU](8|16|32|64))?',
    );
  m11..begin = RegexSource('\\b(0o[0-7][_0-7]*)(\'?[iIuUfF](8|16|32|64))?');
  m12..begin = RegexSource('\\b(0(b|B)[01][_01]*)(\'?[iIuUfF](8|16|32|64))?');
  m13..begin = RegexSource('\\b(\\d[_\\d]*)(\'?[iIuUfF](8|16|32|64))?');
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  return m0;
}
