// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `nsis` language (NSIS).
Language buildNsis() {
  final m0 = Language(name: 'NSIS', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'Abort',
          'AddBrandingImage',
          'AddSize',
          'AllowRootDirInstall',
          'AllowSkipFiles',
          'AutoCloseWindow',
          'BGFont',
          'BGGradient',
          'BrandingText',
          'BringToFront',
          'Call',
          'CallInstDLL',
          'Caption',
          'ChangeUI',
          'CheckBitmap',
          'ClearErrors',
          'CompletedText',
          'ComponentText',
          'CopyFiles',
          'CPU',
          'CRCCheck',
          'CreateDirectory',
          'CreateFont',
          'CreateShortCut',
          'Delete',
          'DeleteINISec',
          'DeleteINIStr',
          'DeleteRegKey',
          'DeleteRegValue',
          'DetailPrint',
          'DetailsButtonText',
          'DirText',
          'DirVar',
          'DirVerify',
          'EnableWindow',
          'EnumRegKey',
          'EnumRegValue',
          'Exch',
          'Exec',
          'ExecShell',
          'ExecShellWait',
          'ExecWait',
          'ExpandEnvStrings',
          'File',
          'FileBufSize',
          'FileClose',
          'FileErrorText',
          'FileOpen',
          'FileRead',
          'FileReadByte',
          'FileReadUTF16LE',
          'FileReadWord',
          'FileWriteUTF16LE',
          'FileSeek',
          'FileWrite',
          'FileWriteByte',
          'FileWriteWord',
          'FindClose',
          'FindFirst',
          'FindNext',
          'FindWindow',
          'FlushINI',
          'GetCurInstType',
          'GetCurrentAddress',
          'GetDlgItem',
          'GetDLLVersion',
          'GetDLLVersionLocal',
          'GetErrorLevel',
          'GetFileTime',
          'GetFileTimeLocal',
          'GetFullPathName',
          'GetFunctionAddress',
          'GetInstDirError',
          'GetKnownFolderPath',
          'GetLabelAddress',
          'GetRegView',
          'GetShellVarContext',
          'GetTempFileName',
          'GetWinVer',
          'Goto',
          'HideWindow',
          'Icon',
          'IfAbort',
          'IfAltRegView',
          'IfErrors',
          'IfFileExists',
          'IfRebootFlag',
          'IfRtlLanguage',
          'IfShellVarContextAll',
          'IfSilent',
          'InitPluginsDir',
          'InstallButtonText',
          'InstallColors',
          'InstallDir',
          'InstallDirRegKey',
          'InstProgressFlags',
          'InstType',
          'InstTypeGetText',
          'InstTypeSetText',
          'Int64Cmp',
          'Int64CmpU',
          'Int64Fmt',
          'IntCmp',
          'IntCmpU',
          'IntFmt',
          'IntOp',
          'IntPtrCmp',
          'IntPtrCmpU',
          'IntPtrOp',
          'IsWindow',
          'LangString',
          'LicenseBkColor',
          'LicenseData',
          'LicenseForceSelection',
          'LicenseLangString',
          'LicenseText',
          'LoadAndSetImage',
          'LoadLanguageFile',
          'LockWindow',
          'LogSet',
          'LogText',
          'ManifestAppendCustomString',
          'ManifestDisableWindowFiltering',
          'ManifestDPIAware',
          'ManifestDPIAwareness',
          'ManifestGdiScaling',
          'ManifestLongPathAware',
          'ManifestMaxVersionTested',
          'ManifestSupportedOS',
          'MessageBox',
          'MiscButtonText',
          'Name|0',
          'Nop',
          'OutFile',
          'Page',
          'PageCallbacks',
          'PEAddResource',
          'PEDllCharacteristics',
          'PERemoveResource',
          'PESubsysVer',
          'Pop',
          'Push',
          'Quit',
          'ReadEnvStr',
          'ReadINIStr',
          'ReadMemory',
          'ReadRegDWORD',
          'ReadRegStr',
          'Reboot',
          'RegDLL',
          'Rename',
          'RequestExecutionLevel',
          'ReserveFile',
          'Return',
          'RMDir',
          'SearchPath',
          'SectionGetFlags',
          'SectionGetInstTypes',
          'SectionGetSize',
          'SectionGetText',
          'SectionIn',
          'SectionSetFlags',
          'SectionSetInstTypes',
          'SectionSetSize',
          'SectionSetText',
          'SendMessage',
          'SetAutoClose',
          'SetBrandingImage',
          'SetCompress',
          'SetCompressor',
          'SetCompressorDictSize',
          'SetCompressionLevel',
          'SetCtlColors',
          'SetCurInstType',
          'SetDatablockOptimize',
          'SetDateSave',
          'SetDetailsPrint',
          'SetDetailsView',
          'SetErrorLevel',
          'SetErrors',
          'SetFileAttributes',
          'SetFont',
          'SetOutPath',
          'SetOverwrite',
          'SetRebootFlag',
          'SetRegView',
          'SetShellVarContext',
          'SetSilent',
          'ShowInstDetails',
          'ShowUninstDetails',
          'ShowWindow',
          'SilentInstall',
          'SilentUnInstall',
          'Sleep',
          'SpaceTexts',
          'StrCmp',
          'StrCmpS',
          'StrCpy',
          'StrLen',
          'SubCaption',
          'Target',
          'Unicode',
          'UnsafeStrCpy',
          'UninstallButtonText',
          'UninstallCaption',
          'UninstallIcon',
          'UninstallSubCaption',
          'UninstallText',
          'UninstPage',
          'UnRegDLL',
          'Var',
          'VIAddVersionKey',
          'VIFileVersion',
          'VIProductVersion',
          'WindowIcon',
          'WriteINIStr',
          'WriteRegBin',
          'WriteRegDWORD',
          'WriteRegExpandStr',
          'WriteRegMultiStr',
          'WriteRegNone',
          'WriteRegStr',
          'WriteUninstaller',
          'XPStyle',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: [
          'admin',
          'all',
          'auto',
          'both',
          'bottom',
          'bzip2',
          'colored',
          'components',
          'current',
          'custom',
          'directory',
          'false',
          'force',
          'hide',
          'highest',
          'ifdiff',
          'ifnewer',
          'instfiles',
          'lastused',
          'leave',
          'left',
          'license',
          'listonly',
          'lzma',
          'nevershow',
          'none',
          'normal',
          'notset',
          'off',
          'on',
          'open',
          'print',
          'right',
          'show',
          'silent',
          'silentlog',
          'smooth',
          'textonly',
          'top',
          'true',
          'try',
          'un.components',
          'un.custom',
          'un.directory',
          'un.instfiles',
          'un.license',
          'uninstConfirm',
          'user',
          'Win10',
          'Win7',
          'Win8',
          'WinVista',
          'zlib',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m15, m16]
    ..frozen = true;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m17, m18]
    ..frozen = true;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource(';')
    ..end = RegexSource('\$')
    ..contains = [m19, m20]
    ..relevance = 0;
  m4
    ..match = RegexList([
      'Var',
      '\\s+',
      '(?:\\/GLOBAL\\s+)?',
      '[A-Za-z][\\w.]*',
    ])
    ..scope = ScopeGroups({1: 'keyword', 3: 'params', 4: 'variable'});
  m5
    ..match = RegexList(['Function', '\\s+', '(\\.)?[a-zA-Z]\\w*'])
    ..scope = ScopeGroups({1: 'keyword', 3: 'title.function'});
  m6..beginKeywords = 'Function PageEx Section SectionGroup FunctionEnd PageExEnd SectionEnd SectionGroupEnd';
  m7
    ..className = ScopeName('string')
    ..variants = [m21, m22, m23]
    ..illegal = RegexSource('\\n')
    ..contains = [m24, m25, m9, m10, m11];
  m8
    ..className = ScopeName('keyword')
    ..begin = RegexSource(
      '!(?:addincludedir|addplugindir|appendfile|appendmemfile|assert|cd|define|delfile|echo|else|elseif|elseifdef|elseifmacrodef|elseifmacrondef|elseifndef|endif|error|execute|finalize|getdllversion|gettlbversion|if|ifdef|ifmacrodef|ifmacrondef|ifndef|include|insertmacro|macro|macroend|macroundef|makensis|packhdr|pragma|searchparse|searchreplace|system|tempfile|undef|uninstfinalize|verbose|warning)\\b',
    );
  m9
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$+\\{[\\!\\w.:-]+\\}');
  m10
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$+\\w[\\w\\.]*')
    ..illegal = RegexSource('\\(\\)\\{\\}');
  m11
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$+\\([\\w^.:!-]+\\)');
  m12
    ..className = ScopeName('params')
    ..begin = RegexSource(
      '(?:ARCHIVE|FILE_ATTRIBUTE_ARCHIVE|FILE_ATTRIBUTE_NORMAL|FILE_ATTRIBUTE_OFFLINE|FILE_ATTRIBUTE_READONLY|FILE_ATTRIBUTE_SYSTEM|FILE_ATTRIBUTE_TEMPORARY|HKCC|HKCR|HKCR32|HKCR64|HKCU|HKCU32|HKCU64|HKDD|HKEY_CLASSES_ROOT|HKEY_CURRENT_CONFIG|HKEY_CURRENT_USER|HKEY_DYN_DATA|HKEY_LOCAL_MACHINE|HKEY_PERFORMANCE_DATA|HKEY_USERS|HKLM|HKLM32|HKLM64|HKPD|HKU|IDABORT|IDCANCEL|IDIGNORE|IDNO|IDOK|IDRETRY|IDYES|MB_ABORTRETRYIGNORE|MB_DEFBUTTON1|MB_DEFBUTTON2|MB_DEFBUTTON3|MB_DEFBUTTON4|MB_ICONEXCLAMATION|MB_ICONINFORMATION|MB_ICONQUESTION|MB_ICONSTOP|MB_OK|MB_OKCANCEL|MB_RETRYCANCEL|MB_RIGHT|MB_RTLREADING|MB_SETFOREGROUND|MB_TOPMOST|MB_USERICON|MB_YESNO|MB_YESNOCANCEL|OFFLINE|READONLY|SHCTX|SHELL_CONTEXT|SW_HIDE|SW_SHOW|SW_SHOWMAXIMIZED|SW_SHOWMINIMIZED|SW_SHOWNORMAL)\\b',
    );
  m13
    ..className = ScopeName('title.function')
    ..begin = RegexSource('\\w+::\\w+');
  m14
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m17
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m18
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m19
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m20
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m21
    ..begin = RegexSource('"')
    ..end = RegexSource('"');
  m22
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m23
    ..begin = RegexSource('`')
    ..end = RegexSource('`');
  m24
    ..className = ScopeName('char.escape')
    ..begin = RegexSource('\\\$(\\\\[nrt]|\\\$)');
  m25
    ..className = ScopeName('variable.constant')
    ..begin = RegexSource(
      '\\\$(?:ADMINTOOLS|APPDATA|CDBURN_AREA|CMDLINE|COMMONFILES32|COMMONFILES64|COMMONFILES|COOKIES|DESKTOP|DOCUMENTS|EXEDIR|EXEFILE|EXEPATH|FAVORITES|FONTS|HISTORY|HWNDPARENT|INSTDIR|INTERNET_CACHE|LANGUAGE|LOCALAPPDATA|MUSIC|NETHOOD|OUTDIR|PICTURES|PLUGINSDIR|PRINTHOOD|PROFILE|PROGRAMFILES32|PROGRAMFILES64|PROGRAMFILES|QUICKLAUNCH|RECENT|RESOURCES_LOCALIZED|RESOURCES|SENDTO|SMPROGRAMS|SMSTARTUP|STARTMENU|SYSDIR|TEMP|TEMPLATES|VIDEOS|WINDIR)',
    );
  return m0;
}
