// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `oxygene` language (Oxygene).
Language buildOxygene() {
  final m0 = Language(name: 'Oxygene', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'add',
          'and',
          'array',
          'as',
          'asc',
          'aspect',
          'assembly',
          'async',
          'begin',
          'break',
          'block',
          'by',
          'case',
          'class',
          'concat',
          'const',
          'copy',
          'constructor',
          'continue',
          'create',
          'default',
          'delegate',
          'desc',
          'distinct',
          'div',
          'do',
          'downto',
          'dynamic',
          'each',
          'else',
          'empty',
          'end',
          'ensure',
          'enum',
          'equals',
          'event',
          'except',
          'exit',
          'extension',
          'external',
          'false',
          'final',
          'finalize',
          'finalizer',
          'finally',
          'flags',
          'for',
          'forward',
          'from',
          'function',
          'future',
          'global',
          'group',
          'has',
          'if',
          'implementation',
          'implements',
          'implies',
          'in',
          'index',
          'inherited',
          'inline',
          'interface',
          'into',
          'invariants',
          'is',
          'iterator',
          'join',
          'locked',
          'locking',
          'loop',
          'matching',
          'method',
          'mod',
          'module',
          'namespace',
          'nested',
          'new',
          'nil',
          'not',
          'notify',
          'nullable',
          'of',
          'old',
          'on',
          'operator',
          'or',
          'order',
          'out',
          'override',
          'parallel',
          'params',
          'partial',
          'pinned',
          'private',
          'procedure',
          'property',
          'protected',
          'public',
          'queryable',
          'raise',
          'read',
          'readonly',
          'record',
          'reintroduce',
          'remove',
          'repeat',
          'require',
          'result',
          'reverse',
          'sealed',
          'select',
          'self',
          'sequence',
          'set',
          'shl',
          'shr',
          'skip',
          'static',
          'step',
          'soft',
          'take',
          'then',
          'to',
          'true',
          'try',
          'tuple',
          'type',
          'union',
          'unit',
          'unsafe',
          'until',
          'uses',
          'using',
          'var',
          'virtual',
          'raises',
          'volatile',
          'where',
          'while',
          'with',
          'write',
          'xor',
          'yield',
          'await',
          'mapped',
          'deprecated',
          'stdcall',
          'cdecl',
          'pascal',
          'register',
          'safecall',
          'overload',
          'library',
          'platform',
          'reference',
          'packed',
          'strict',
          'published',
          'autoreleasepool',
          'selector',
          'strong',
          'weak',
          'unretained',
        ],
        fromList: false,
      ),
    ], pattern: '\\.?\\w+')
    ..illegal = RegexSource('("|\\\$[G-Zg-z]|\\/\\*|</|=>|->)')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [m9, m10]
    ..relevance = 0;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\(\\*')
    ..end = RegexSource('\\*\\)')
    ..contains = [m11, m12]
    ..relevance = 10;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m13, m14]
    ..frozen = true;
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m15];
  m5
    ..className = ScopeName('string')
    ..begin = RegexSource('(#\\d+)+');
  m6
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m7
    ..beginKeywords = 'function constructor destructor procedure method'
    ..end = RegexSource('[:;]')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: [
          'function',
          'constructor|10',
          'destructor|10',
          'procedure|10',
          'method|10',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m16, m17, m1, m2];
  m8
    ..scope = ScopeName('punctuation')
    ..match = RegexSource(';')
    ..relevance = 0;
  m9
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m10
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m11
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m12
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m15..begin = RegexSource('\'\'');
  m16
    ..scope = ScopeName('title.function')
    ..begin = RegexSource('[a-zA-Z]\\w*')
    ..relevance = 0;
  m17
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstract',
          'add',
          'and',
          'array',
          'as',
          'asc',
          'aspect',
          'assembly',
          'async',
          'begin',
          'break',
          'block',
          'by',
          'case',
          'class',
          'concat',
          'const',
          'copy',
          'constructor',
          'continue',
          'create',
          'default',
          'delegate',
          'desc',
          'distinct',
          'div',
          'do',
          'downto',
          'dynamic',
          'each',
          'else',
          'empty',
          'end',
          'ensure',
          'enum',
          'equals',
          'event',
          'except',
          'exit',
          'extension',
          'external',
          'false',
          'final',
          'finalize',
          'finalizer',
          'finally',
          'flags',
          'for',
          'forward',
          'from',
          'function',
          'future',
          'global',
          'group',
          'has',
          'if',
          'implementation',
          'implements',
          'implies',
          'in',
          'index',
          'inherited',
          'inline',
          'interface',
          'into',
          'invariants',
          'is',
          'iterator',
          'join',
          'locked',
          'locking',
          'loop',
          'matching',
          'method',
          'mod',
          'module',
          'namespace',
          'nested',
          'new',
          'nil',
          'not',
          'notify',
          'nullable',
          'of',
          'old',
          'on',
          'operator',
          'or',
          'order',
          'out',
          'override',
          'parallel',
          'params',
          'partial',
          'pinned',
          'private',
          'procedure',
          'property',
          'protected',
          'public',
          'queryable',
          'raise',
          'read',
          'readonly',
          'record',
          'reintroduce',
          'remove',
          'repeat',
          'require',
          'result',
          'reverse',
          'sealed',
          'select',
          'self',
          'sequence',
          'set',
          'shl',
          'shr',
          'skip',
          'static',
          'step',
          'soft',
          'take',
          'then',
          'to',
          'true',
          'try',
          'tuple',
          'type',
          'union',
          'unit',
          'unsafe',
          'until',
          'uses',
          'using',
          'var',
          'virtual',
          'raises',
          'volatile',
          'where',
          'while',
          'with',
          'write',
          'xor',
          'yield',
          'await',
          'mapped',
          'deprecated',
          'stdcall',
          'cdecl',
          'pascal',
          'register',
          'safecall',
          'overload',
          'library',
          'platform',
          'reference',
          'packed',
          'strict',
          'published',
          'autoreleasepool',
          'selector',
          'strong',
          'weak',
          'unretained',
        ],
        fromList: false,
      ),
    ], pattern: '\\.?\\w+')
    ..contains = [m4, m5];
  return m0;
}
