// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `parser3` language (Parser3).
Language buildParser3() {
  final m0 = Language(name: 'Parser3');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode();
  m0
    ..subLanguage = SubLanguageName('xml')
    ..relevance = 0
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^#')
    ..end = RegexSource('\$')
    ..contains = [m9, m10];
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\^rem\\{')
    ..end = RegexSource('\\}')
    ..contains = [m11, m12, m13]
    ..relevance = 10;
  m3
    ..className = ScopeName('meta')
    ..begin = RegexSource('^@(?:BASE|USE|CLASS|OPTIONS)\$')
    ..relevance = 10;
  m4
    ..className = ScopeName('title')
    ..begin = RegexSource(
      '@[\\w\\-]+\\[[\\w^;\\-]*\\](?:\\[[\\w^;\\-]*\\])?(?:.*)\$',
    );
  m5
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$\\{?[\\w\\-.:]+\\}?');
  m6
    ..className = ScopeName('keyword')
    ..begin = RegexSource('\\^[\\w\\-.:]+');
  m7
    ..className = ScopeName('number')
    ..begin = RegexSource('\\^#[0-9a-fA-F]+');
  m8
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m9
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m10
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m11
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..contains = [self, m14, m15];
  m12
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m13
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m14
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m15
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  return m0;
}
