// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `plaintext` language (Plain text).
Language buildPlaintext() {
  final m0 = Language(
    name: 'Plain text',
    aliases: ['text', 'txt'],
    disableAutodetect: true,
  );
  return m0;
}
