// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `pony` language (Pony).
Language buildPony() {
  final m0 = Language(name: 'Pony');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'actor',
          'addressof',
          'and',
          'as',
          'be',
          'break',
          'class',
          'compile_error',
          'compile_intrinsic',
          'consume',
          'continue',
          'delegate',
          'digestof',
          'do',
          'else',
          'elseif',
          'embed',
          'end',
          'error',
          'for',
          'fun',
          'if',
          'ifdef',
          'in',
          'interface',
          'is',
          'isnt',
          'lambda',
          'let',
          'match',
          'new',
          'not',
          'object',
          'or',
          'primitive',
          'recover',
          'repeat',
          'return',
          'struct',
          'then',
          'trait',
          'try',
          'type',
          'until',
          'use',
          'var',
          'where',
          'while',
          'with',
          'xor',
        ],
        fromList: false,
      ),
      (
        scope: 'meta',
        words: ['iso', 'val', 'tag', 'trn', 'box', 'ref'],
        fromList: false,
      ),
      (scope: 'literal', words: ['this', 'false', 'true'], fromList: false),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..className = ScopeName('type')
    ..begin = RegexSource('\\b_?[A-Z][\\w]*')
    ..relevance = 0;
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource('"""')
    ..end = RegexSource('"""')
    ..relevance = 10;
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m9];
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m9]
    ..relevance = 0;
  m5
    ..begin = RegexSource('[a-zA-Z]\\w*\'')
    ..relevance = 0;
  m6
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|\\b0[bB][01]+|(\\b\\d+(_\\d+)?(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0;
  m7
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m10, m11]
    ..frozen = true;
  m8
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m12, m13]
    ..frozen = true;
  m9
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m10
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m11
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m12
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m13
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  return m0;
}
