// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `profile` language (Python profiler).
Language buildProfile() {
  final m0 = Language(name: 'Python profiler');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode();
  m0..contains = [m1, m2, m3, m4, m5, m6, m7];
  m1
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m2
    ..begin = RegexSource('[a-zA-Z_][\\da-zA-Z_]+\\.[\\da-zA-Z_]{1,3}')
    ..end = RegexSource(':')
    ..excludeEnd = true;
  m3
    ..begin = RegexSource('(ncalls|tottime|cumtime)')
    ..end = RegexSource('\$')
    ..keywords = RawKeywords([
      (
        scope: null,
        words: ['ncalls', 'tottime|10', 'cumtime|10', 'filename'],
        fromList: false,
      ),
    ])
    ..relevance = 10;
  m4
    ..begin = RegexSource('function calls')
    ..end = RegexSource('\$')
    ..contains = [m1]
    ..relevance = 10;
  m5
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m8]
    ..frozen = true;
  m6
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m8]
    ..frozen = true;
  m7
    ..className = ScopeName('string')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)\$')
    ..excludeBegin = true
    ..excludeEnd = true
    ..relevance = 0;
  m8
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  return m0;
}
