// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `properties` language (.properties).
Language buildProperties() {
  final m0 = Language(
    name: '.properties',
    caseInsensitive: true,
    disableAutodetect: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode();
  m0
    ..illegal = RegexSource('\\S')
    ..contains = [m1, m2, m3];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^\\s*[!#]')
    ..end = RegexSource('\$')
    ..contains = [m4, m5];
  m2
    ..returnBegin = true
    ..variants = [m6, m7]
    ..contains = [m8]
    ..starts = m9;
  m3
    ..className = ScopeName('attr')
    ..begin = RegexSource('([^\\\\:= \\t\\f\\n]|\\\\.)+[ \\t\\f]*\$');
  m4
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m5
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m6
    ..begin = RegexSource(
      '([^\\\\:= \\t\\f\\n]|\\\\.)+[ \\t\\f]*[:=][ \\t\\f]*',
    );
  m7..begin = RegexSource('([^\\\\:= \\t\\f\\n]|\\\\.)+[ \\t\\f]+');
  m8
    ..className = ScopeName('attr')
    ..begin = RegexSource('([^\\\\:= \\t\\f\\n]|\\\\.)+')
    ..endsParent = true;
  m9
    ..end = RegexSource('([ \\t\\f]*[:=][ \\t\\f]*|[ \\t\\f]+)')
    ..relevance = 0
    ..starts = m10;
  m10
    ..className = ScopeName('string')
    ..end = RegexSource('\$')
    ..relevance = 0
    ..contains = [m11, m12];
  m11..begin = RegexSource('\\\\\\\\');
  m12..begin = RegexSource('\\\\\\n');
  return m0;
}
