// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `protobuf` language (Protocol Buffers).
Language buildProtobuf() {
  final m0 = Language(name: 'Protocol Buffers', aliases: ['proto']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'package',
          'import',
          'option',
          'optional',
          'required',
          'repeated',
          'group',
          'oneof',
        ],
        fromList: true,
      ),
      (
        scope: 'type',
        words: [
          'double',
          'float',
          'int32',
          'int64',
          'uint32',
          'uint64',
          'sint32',
          'sint64',
          'fixed32',
          'fixed64',
          'sfixed32',
          'sfixed64',
          'bool',
          'string',
          'bytes',
        ],
        fromList: true,
      ),
      (scope: 'literal', words: ['true', 'false'], fromList: true),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7];
  m1
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m8]
    ..frozen = true;
  m2
    ..scope = ScopeName('number')
    ..begin = RegexSource('\\b\\d+(\\.\\d+)?')
    ..relevance = 0
    ..frozen = true;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m9, m10]
    ..frozen = true;
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m11, m12]
    ..frozen = true;
  m5
    ..match = RegexList(['(message|enum|service)\\s+', '[a-zA-Z]\\w*'])
    ..scope = ScopeGroups({1: 'keyword', 2: 'title.class'});
  m6
    ..className = ScopeName('function')
    ..beginKeywords = 'rpc'
    ..end = RegexSource('[{;]')
    ..excludeEnd = true
    ..keywords = RawKeywords([
      (scope: null, words: ['rpc', 'returns'], fromList: false),
    ]);
  m7..begin = RegexSource('^\\s*[A-Z_]+(?=\\s*=[^\\n]+;\$)');
  m8
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m9
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m10
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m11
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m12
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  return m0;
}
