// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';
import 'package:hilite/src/callbacks.dart' as callbacks;

/// The `r` language (R).
Language buildR() {
  final m0 = Language(name: 'R');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode(),
      m26 = Mode(),
      m27 = Mode(),
      m28 = Mode(),
      m29 = Mode(),
      m30 = Mode(),
      m31 = Mode(),
      m32 = Mode(),
      m33 = Mode(),
      m34 = Mode(),
      m35 = Mode(),
      m36 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'function',
          'if',
          'in',
          'break',
          'next',
          'repeat',
          'else',
          'for',
          'while',
        ],
        fromList: false,
      ),
      (
        scope: 'literal',
        words: [
          'NULL',
          'NA',
          'TRUE',
          'FALSE',
          'Inf',
          'NaN',
          'NA_integer_|10',
          'NA_real_|10',
          'NA_character_|10',
          'NA_complex_|10',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'LETTERS',
          'letters',
          'month.abb',
          'month.name',
          'pi',
          'T',
          'F',
          'abs',
          'acos',
          'acosh',
          'all',
          'any',
          'anyNA',
          'Arg',
          'as.call',
          'as.character',
          'as.complex',
          'as.double',
          'as.environment',
          'as.integer',
          'as.logical',
          'as.null.default',
          'as.numeric',
          'as.raw',
          'asin',
          'asinh',
          'atan',
          'atanh',
          'attr',
          'attributes',
          'baseenv',
          'browser',
          'c',
          'call',
          'ceiling',
          'class',
          'Conj',
          'cos',
          'cosh',
          'cospi',
          'cummax',
          'cummin',
          'cumprod',
          'cumsum',
          'digamma',
          'dim',
          'dimnames',
          'emptyenv',
          'exp',
          'expression',
          'floor',
          'forceAndCall',
          'gamma',
          'gc.time',
          'globalenv',
          'Im',
          'interactive',
          'invisible',
          'is.array',
          'is.atomic',
          'is.call',
          'is.character',
          'is.complex',
          'is.double',
          'is.environment',
          'is.expression',
          'is.finite',
          'is.function',
          'is.infinite',
          'is.integer',
          'is.language',
          'is.list',
          'is.logical',
          'is.matrix',
          'is.na',
          'is.name',
          'is.nan',
          'is.null',
          'is.numeric',
          'is.object',
          'is.pairlist',
          'is.raw',
          'is.recursive',
          'is.single',
          'is.symbol',
          'lazyLoadDBfetch',
          'length',
          'lgamma',
          'list',
          'log',
          'max',
          'min',
          'missing',
          'Mod',
          'names',
          'nargs',
          'nzchar',
          'oldClass',
          'on.exit',
          'pos.to.env',
          'proc.time',
          'prod',
          'quote',
          'range',
          'Re',
          'rep',
          'retracemem',
          'return',
          'round',
          'seq_along',
          'seq_len',
          'seq.int',
          'sign',
          'signif',
          'sin',
          'sinh',
          'sinpi',
          'sqrt',
          'standardGeneric',
          'substitute',
          'sum',
          'switch',
          'tan',
          'tanh',
          'tanpi',
          'tracemem',
          'trigamma',
          'trunc',
          'unclass',
          'untracemem',
          'UseMethod',
          'xtfrm',
        ],
        fromList: false,
      ),
    ], pattern: '(?:(?:[a-zA-Z]|\\.[._a-zA-Z])[._a-zA-Z0-9]*)|\\.(?!\\d)')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#\'')
    ..end = RegexSource('\$')
    ..contains = [m9, m10, m11, m12, m13, m14];
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m15, m16]
    ..frozen = true;
  m3
    ..scope = ScopeName('string')
    ..contains = [m17]
    ..variants = [m18, m19, m20, m21, m22, m23, m24, m25];
  m4
    ..relevance = 0
    ..variants = [m26, m27, m28, m29];
  m5
    ..scope = ScopeGroups({3: 'operator'})
    ..match = RegexList([
      '(?:(?:[a-zA-Z]|\\.[._a-zA-Z])[._a-zA-Z0-9]*)|\\.(?!\\d)',
      '\\s+',
      '<-',
      '\\s+',
    ]);
  m6
    ..scope = ScopeName('operator')
    ..relevance = 0
    ..variants = [m30, m31];
  m7
    ..scope = ScopeName('punctuation')
    ..relevance = 0
    ..match = RegexSource('(?:[()]|[{}]|\\[\\[|[[\\]]|\\\\|,)');
  m8
    ..begin = RegexSource('`')
    ..end = RegexSource('`')
    ..contains = [m32];
  m9
    ..scope = ScopeName('doctag')
    ..match = RegexSource('@examples')
    ..starts = m33;
  m10
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('@param')
    ..end = RegexSource('\$')
    ..contains = [m34];
  m11
    ..scope = ScopeName('doctag')
    ..match = RegexSource('@[a-zA-Z]+');
  m12
    ..scope = ScopeName('keyword')
    ..match = RegexSource('\\\\[a-zA-Z]+');
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m17
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m18
    ..begin = RegexSource('[rR]"(-*)\\(')
    ..end = RegexSource('\\)(-*)"')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m19
    ..begin = RegexSource('[rR]"(-*)\\{')
    ..end = RegexSource('\\}(-*)"')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m20
    ..begin = RegexSource('[rR]"(-*)\\[')
    ..end = RegexSource('\\](-*)"')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m21
    ..begin = RegexSource('[rR]\'(-*)\\(')
    ..end = RegexSource('\\)(-*)\'')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m22
    ..begin = RegexSource('[rR]\'(-*)\\{')
    ..end = RegexSource('\\}(-*)\'')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m23
    ..begin = RegexSource('[rR]\'(-*)\\[')
    ..end = RegexSource('\\](-*)\'')
    ..onBegin = callbacks.endSameAsBeginOnBegin
    ..onEnd = callbacks.endSameAsBeginOnEnd;
  m24
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..relevance = 0;
  m25
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..relevance = 0;
  m26
    ..scope = ScopeGroups({1: 'operator', 2: 'number'})
    ..match = RegexList([
      '[=!<>:]=|\\|\\||&&|:::?|<-|<<-|->>|->|\\|>|[-+*\\/?!\$&|:<=>@^~]|\\*\\*',
      '(?:0[xX][0-9a-fA-F]+\\.[0-9a-fA-F]*[pP][+-]?\\d+i?|0[xX][0-9a-fA-F]+(?:[pP][+-]?\\d+)?[Li]?|(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][+-]?\\d+)?[Li]?)',
    ]);
  m27
    ..scope = ScopeGroups({1: 'operator', 2: 'number'})
    ..match = RegexList([
      '%[^%]*%',
      '(?:0[xX][0-9a-fA-F]+\\.[0-9a-fA-F]*[pP][+-]?\\d+i?|0[xX][0-9a-fA-F]+(?:[pP][+-]?\\d+)?[Li]?|(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][+-]?\\d+)?[Li]?)',
    ]);
  m28
    ..scope = ScopeGroups({1: 'punctuation', 2: 'number'})
    ..match = RegexList([
      '(?:[()]|[{}]|\\[\\[|[[\\]]|\\\\|,)',
      '(?:0[xX][0-9a-fA-F]+\\.[0-9a-fA-F]*[pP][+-]?\\d+i?|0[xX][0-9a-fA-F]+(?:[pP][+-]?\\d+)?[Li]?|(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][+-]?\\d+)?[Li]?)',
    ]);
  m29
    ..scope = ScopeGroups({2: 'number'})
    ..match = RegexList([
      '[^a-zA-Z0-9._]|^',
      '(?:0[xX][0-9a-fA-F]+\\.[0-9a-fA-F]*[pP][+-]?\\d+i?|0[xX][0-9a-fA-F]+(?:[pP][+-]?\\d+)?[Li]?|(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][+-]?\\d+)?[Li]?)',
    ]);
  m30
    ..match = RegexSource(
      '[=!<>:]=|\\|\\||&&|:::?|<-|<<-|->>|->|\\|>|[-+*\\/?!\$&|:<=>@^~]|\\*\\*',
    );
  m31..match = RegexSource('%[^%]*%');
  m32..begin = RegexSource('\\\\.');
  m33
    ..end = RegexSource('(?=(?:\\n^#\'\\s*(?=@[a-zA-Z]+)|\\n^(?!#\')))')
    ..endsParent = true;
  m34
    ..scope = ScopeName('variable')
    ..variants = [m35, m36]
    ..endsParent = true;
  m35
    ..match = RegexSource(
      '(?:(?:[a-zA-Z]|\\.[._a-zA-Z])[._a-zA-Z0-9]*)|\\.(?!\\d)',
    );
  m36..match = RegexSource('`(?:\\\\.|[^`\\\\])+`');
  return m0;
}
