// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `routeros` language (MikroTik RouterOS script).
Language buildRouteros() {
  final m0 = Language(
    name: 'MikroTik RouterOS script',
    aliases: ['mikrotik'],
    caseInsensitive: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'literal',
        words: ['true', 'false', 'yes', 'no', 'nothing', 'nil', 'null'],
        fromList: false,
      ),
      (
        scope: 'keyword',
        words: [
          'foreach',
          'do',
          'while',
          'for',
          'if',
          'from',
          'to',
          'step',
          'else',
          'on-error',
          'and',
          'or',
          'not',
          'in',
          ':foreach',
          ':do',
          ':while',
          ':for',
          ':if',
          ':from',
          ':to',
          ':step',
          ':else',
          ':on-error',
          ':and',
          ':or',
          ':not',
          ':in',
          ':global',
          ':local',
          ':beep',
          ':delay',
          ':put',
          ':len',
          ':typeof',
          ':pick',
          ':log',
          ':time',
          ':set',
          ':find',
          ':environment',
          ':terminal',
          ':error',
          ':execute',
          ':parse',
          ':resolve',
          ':toarray',
          ':tobool',
          ':toid',
          ':toip',
          ':toip6',
          ':tonum',
          ':tostr',
          ':totime',
        ],
        fromList: false,
      ),
    ], pattern: ':?[\\w-]+')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..variants = [m10, m11, m12]
    ..illegal = RegexSource('.');
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('^#')
    ..end = RegexSource('\$')
    ..contains = [m13, m14];
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m15, m5, m16];
  m4
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m5
    ..className = ScopeName('variable')
    ..variants = [m17, m18];
  m6
    ..begin = RegexSource('[\\w-]+=([^\\s{}[\\]()>]+)')
    ..relevance = 0
    ..returnBegin = true
    ..contains = [m19, m20];
  m7
    ..className = ScopeName('number')
    ..begin = RegexSource('\\*[0-9a-fA-F]+');
  m8
    ..begin = RegexSource(
      '\\b(add|remove|enable|disable|set|get|print|export|edit|find|run|debug|error|info|warning)([\\s[(\\]|])',
    )
    ..returnBegin = true
    ..contains = [m21];
  m9
    ..className = ScopeName('built_in')
    ..variants = [m22, m23];
  m10
    ..begin = RegexSource('\\/\\*')
    ..end = RegexSource('\\*\\/');
  m11
    ..begin = RegexSource('\\/\\/')
    ..end = RegexSource('\$');
  m12
    ..begin = RegexSource('<\\/')
    ..end = RegexSource('>');
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m15
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m16
    ..className = ScopeName('variable')
    ..begin = RegexSource('\\\$\\(')
    ..end = RegexSource('\\)')
    ..contains = [m15];
  m17..begin = RegexSource('\\\$[\\w\\d#@][\\w\\d_]*');
  m18..begin = RegexSource('\\\$\\{(.*?)\\}');
  m19
    ..className = ScopeName('attribute')
    ..begin = RegexSource('[^=]+');
  m20
    ..begin = RegexSource('=')
    ..endsWithParent = true
    ..relevance = 0
    ..contains = [m3, m4, m5, m24, m25];
  m21
    ..className = ScopeName('built_in')
    ..begin = RegexSource('\\w+');
  m22
    ..begin = RegexSource(
      '(\\.\\./|/|\\s)((traffic-flow|traffic-generator|firewall|scheduler|aaa|accounting|address-list|address|align|area|bandwidth-server|bfd|bgp|bridge|client|clock|community|config|connection|console|customer|default|dhcp-client|dhcp-server|discovery|dns|e-mail|ethernet|filter|firmware|gps|graphing|group|hardware|health|hotspot|identity|igmp-proxy|incoming|instance|interface|ip|ipsec|ipv6|irq|l2tp-server|lcd|ldp|logging|mac-server|mac-winbox|mangle|manual|mirror|mme|mpls|nat|nd|neighbor|network|note|ntp|ospf|ospf-v3|ovpn-server|page|peer|pim|ping|policy|pool|port|ppp|pppoe-client|pptp-server|prefix|profile|proposal|proxy|queue|radius|resource|rip|ripng|route|routing|screen|script|security-profiles|server|service|service-port|settings|shares|smb|sms|sniffer|snmp|snooper|socks|sstp-server|system|tool|tracking|type|upgrade|upnp|user-manager|users|user|vlan|secret|vrrp|watchdog|web-access|wireless|pptp|pppoe|lan|wan|layer7-protocol|lease|simple|raw);?\\s)+',
    );
  m23
    ..begin = RegexSource('\\.\\.')
    ..relevance = 0;
  m24
    ..className = ScopeName('literal')
    ..begin = RegexSource('\\b(true|false|yes|no|nothing|nil|null)\\b');
  m25..begin = RegexSource('("[^"]*"|[^\\s{}[\\]]+)');
  return m0;
}
