// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `sas` language (SAS).
Language buildSas() {
  final m0 = Language(name: 'SAS', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'literal',
        words: [
          'null',
          'missing',
          '_all_',
          '_automatic_',
          '_character_',
          '_infile_',
          '_n_',
          '_name_',
          '_null_',
          '_numeric_',
          '_user_',
          '_webout_',
        ],
        fromList: true,
      ),
      (
        scope: 'keyword',
        words: [
          'do',
          'if',
          'then',
          'else',
          'end',
          'until',
          'while',
          'abort',
          'array',
          'attrib',
          'by',
          'call',
          'cards',
          'cards4',
          'catname',
          'continue',
          'datalines',
          'datalines4',
          'delete',
          'delim',
          'delimiter',
          'display',
          'dm',
          'drop',
          'endsas',
          'error',
          'file',
          'filename',
          'footnote',
          'format',
          'goto',
          'in',
          'infile',
          'informat',
          'input',
          'keep',
          'label',
          'leave',
          'length',
          'libname',
          'link',
          'list',
          'lostcard',
          'merge',
          'missing',
          'modify',
          'options',
          'output',
          'out',
          'page',
          'put',
          'redirect',
          'remove',
          'rename',
          'replace',
          'retain',
          'return',
          'select',
          'set',
          'skip',
          'startsas',
          'stop',
          'title',
          'update',
          'waitsas',
          'where',
          'window',
          'x|0',
          'systask',
          'add',
          'and',
          'alter',
          'as',
          'cascade',
          'check',
          'create',
          'delete',
          'describe',
          'distinct',
          'drop',
          'foreign',
          'from',
          'group',
          'having',
          'index',
          'insert',
          'into',
          'in',
          'key',
          'like',
          'message',
          'modify',
          'msgtype',
          'not',
          'null',
          'on',
          'or',
          'order',
          'primary',
          'references',
          'reset',
          'restrict',
          'select',
          'set',
          'table',
          'unique',
          'update',
          'validate',
          'view',
          'where',
        ],
        fromList: true,
      ),
    ])
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..className = ScopeName('keyword')
    ..begin = RegexSource('^\\s*(proc [\\w\\d_]+|data|run|quit)[\\s;]');
  m2
    ..className = ScopeName('variable')
    ..begin = RegexSource('&[a-zA-Z_&][a-zA-Z0-9_]*\\.?');
  m3
    ..begin = RegexList([
      '^\\s*',
      'datalines;|cards;',
      '(?:.*\\n)+',
      '^\\s*;\\s*\$',
    ])
    ..className = ScopeGroups({2: 'keyword', 3: 'string'});
  m4
    ..begin = RegexList(['%mend|%macro', '\\s+', '[a-zA-Z_&][a-zA-Z0-9_]*'])
    ..className = ScopeGroups({1: 'built_in', 3: 'title.function'});
  m5
    ..className = ScopeName('built_in')
    ..begin = RegexSource(
      '%(?:bquote|nrbquote|cmpres|qcmpres|compstor|datatyp|display|do|else|end|eval|global|goto|if|index|input|keydef|label|left|length|let|local|lowcase|macro|mend|nrbquote|nrquote|nrstr|put|qcmpres|qleft|qlowcase|qscan|qsubstr|qsysfunc|qtrim|quote|qupcase|scan|str|substr|superq|syscall|sysevalf|sysexec|sysfunc|sysget|syslput|sysprod|sysrc|sysrput|then|to|trim|unquote|until|upcase|verify|while|window)',
    );
  m6
    ..className = ScopeName('title.function')
    ..begin = RegexSource('%[a-zA-Z_][a-zA-Z_0-9]*');
  m7
    ..className = ScopeName('meta')
    ..begin = RegexSource(
      '(?:abs|addr|airy|arcos|arsin|atan|attrc|attrn|band|betainv|blshift|bnot|bor|brshift|bxor|byte|cdf|ceil|cexist|cinv|close|cnonct|collate|compbl|compound|compress|cos|cosh|css|curobs|cv|daccdb|daccdbsl|daccsl|daccsyd|dacctab|dairy|date|datejul|datepart|datetime|day|dclose|depdb|depdbsl|depdbsl|depsl|depsl|depsyd|depsyd|deptab|deptab|dequote|dhms|dif|digamma|dim|dinfo|dnum|dopen|doptname|doptnum|dread|dropnote|dsname|erf|erfc|exist|exp|fappend|fclose|fcol|fdelete|fetch|fetchobs|fexist|fget|fileexist|filename|fileref|finfo|finv|fipname|fipnamel|fipstate|floor|fnonct|fnote|fopen|foptname|foptnum|fpoint|fpos|fput|fread|frewind|frlen|fsep|fuzz|fwrite|gaminv|gamma|getoption|getvarc|getvarn|hbound|hms|hosthelp|hour|ibessel|index|indexc|indexw|input|inputc|inputn|int|intck|intnx|intrr|irr|jbessel|juldate|kurtosis|lag|lbound|left|length|lgamma|libname|libref|log|log10|log2|logpdf|logpmf|logsdf|lowcase|max|mdy|mean|min|minute|mod|month|mopen|mort|n|netpv|nmiss|normal|note|npv|open|ordinal|pathname|pdf|peek|peekc|pmf|point|poisson|poke|probbeta|probbnml|probchi|probf|probgam|probhypr|probit|probnegb|probnorm|probt|put|putc|putn|qtr|quote|ranbin|rancau|ranexp|rangam|range|rank|rannor|ranpoi|rantbl|rantri|ranuni|repeat|resolve|reverse|rewind|right|round|saving|scan|sdf|second|sign|sin|sinh|skewness|soundex|spedis|sqrt|std|stderr|stfips|stname|stnamel|substr|sum|symget|sysget|sysmsg|sysprod|sysrc|system|tan|tanh|time|timepart|tinv|tnonct|today|translate|tranwrd|trigamma|trim|trimn|trunc|uniform|upcase|uss|var|varfmt|varinfmt|varlabel|varlen|varname|varnum|varray|varrayx|vartype|verify|vformat|vformatd|vformatdx|vformatn|vformatnx|vformatw|vformatwx|vformatx|vinarray|vinarrayx|vinformat|vinformatd|vinformatdx|vinformatn|vinformatnx|vinformatw|vinformatwx|vinformatx|vlabel|vlabelx|vlength|vlengthx|vname|vnamex|vtype|vtypex|weekday|year|yyq|zipfips|zipname|zipnamel|zipstate)(?=\\()',
    );
  m8
    ..className = ScopeName('string')
    ..variants = [m11, m12];
  m9
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\*')
    ..end = RegexSource(';')
    ..contains = [m13, m14];
  m10
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m15, m16]
    ..frozen = true;
  m11
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m17]
    ..frozen = true;
  m12
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m17]
    ..frozen = true;
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m17
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  return m0;
}
