// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `scilab` language (Scilab).
Language buildScilab() {
  final m0 = Language(name: 'Scilab', aliases: ['sci']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abort',
          'break',
          'case',
          'clear',
          'catch',
          'continue',
          'do',
          'elseif',
          'else',
          'endfunction',
          'end',
          'for',
          'function',
          'global',
          'if',
          'pause',
          'return',
          'resume',
          'select',
          'try',
          'then',
          'while',
        ],
        fromList: false,
      ),
      (
        scope: 'literal',
        words: [
          '%f',
          '%F',
          '%t',
          '%T',
          '%pi',
          '%eps',
          '%inf',
          '%nan',
          '%e',
          '%i',
          '%z',
          '%s',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'abs',
          'and',
          'acos',
          'asin',
          'atan',
          'ceil',
          'cd',
          'chdir',
          'clearglobal',
          'cosh',
          'cos',
          'cumprod',
          'deff',
          'disp',
          'error',
          'exec',
          'execstr',
          'exists',
          'exp',
          'eye',
          'gettext',
          'floor',
          'fprintf',
          'fread',
          'fsolve',
          'imag',
          'isdef',
          'isempty',
          'isinfisnan',
          'isvector',
          'lasterror',
          'length',
          'load',
          'linspace',
          'list',
          'listfiles',
          'log10',
          'log2',
          'log',
          'max',
          'min',
          'msprintf',
          'mclose',
          'mopen',
          'ones',
          'or',
          'pathconvert',
          'poly',
          'printf',
          'prod',
          'pwd',
          'rand',
          'real',
          'round',
          'sinh',
          'sin',
          'size',
          'gsort',
          'sprintf',
          'sqrt',
          'strcat',
          'strcmps',
          'tring',
          'sum',
          'system',
          'tanh',
          'tan',
          'type',
          'typename',
          'warning',
          'zeros',
          'matrix',
        ],
        fromList: false,
      ),
    ], pattern: '%?\\w+')
    ..illegal = RegexSource('("|#|/\\*|\\s+/\\w+)')
    ..contains = [m1, m2, m3, m4, m5, m6];
  m1
    ..className = ScopeName('function')
    ..beginKeywords = 'function'
    ..end = RegexSource('\$')
    ..contains = [m7, m8];
  m2
    ..begin = RegexSource('[a-zA-Z_][a-zA-Z_0-9]*[\\.\']+')
    ..relevance = 0;
  m3
    ..begin = RegexSource('\\[')
    ..end = RegexSource('\\][\\.\']*')
    ..relevance = 0
    ..contains = [m5, m6];
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m9, m10];
  m5
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m6
    ..className = ScopeName('string')
    ..begin = RegexSource('\'|"')
    ..end = RegexSource('\'|"')
    ..contains = [m11, m12];
  m7
    ..scope = ScopeName('title')
    ..begin = RegexSource('[a-zA-Z_]\\w*')
    ..relevance = 0
    ..frozen = true;
  m8
    ..className = ScopeName('params')
    ..begin = RegexSource('\\(')
    ..end = RegexSource('\\)');
  m9
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m10
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m11
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m12..begin = RegexSource('\'\'');
  return m0;
}
