// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `smali` language (Smali).
Language buildSmali() {
  final m0 = Language(name: 'Smali');
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode();
  m0..contains = [m1, m2, m3, m4, m5, m6];
  m1
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..relevance = 0;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('#')
    ..end = RegexSource('\$')
    ..contains = [m7, m8]
    ..relevance = 0;
  m3
    ..className = ScopeName('keyword')
    ..variants = [m9, m10, m11, m12];
  m4
    ..className = ScopeName('built_in')
    ..variants = [m13, m14, m15];
  m5
    ..className = ScopeName('class')
    ..begin = RegexSource('L[^(;:\n]*;')
    ..relevance = 0;
  m6..begin = RegexSource('[vp][0-9]+');
  m7
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m8
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m9..begin = RegexSource('\\s*\\.end\\s[a-zA-Z0-9]*');
  m10
    ..begin = RegexSource('^[ ]*\\.[a-zA-Z]*')
    ..relevance = 0;
  m11
    ..begin = RegexSource('\\s:[a-zA-Z_0-9]*')
    ..relevance = 0;
  m12
    ..begin = RegexSource(
      '\\s(transient|constructor|abstract|final|synthetic|public|private|protected|static|bridge|system)',
    );
  m13
    ..begin = RegexSource(
      '\\s(add|and|cmp|cmpg|cmpl|const|div|double|float|goto|if|int|long|move|mul|neg|new|nop|not|or|rem|return|shl|shr|sput|sub|throw|ushr|xor)\\s',
    );
  m14
    ..begin = RegexSource(
      '\\s(add|and|cmp|cmpg|cmpl|const|div|double|float|goto|if|int|long|move|mul|neg|new|nop|not|or|rem|return|shl|shr|sput|sub|throw|ushr|xor)((-|/)[a-zA-Z0-9]+)+\\s',
    )
    ..relevance = 10;
  m15
    ..begin = RegexSource(
      '\\s(aget|aput|array|check|execute|fill|filled|goto/16|goto/32|iget|instance|invoke|iput|monitor|packed|sget|sparse)((-|/)[a-zA-Z0-9]+)*\\s',
    )
    ..relevance = 10;
  return m0;
}
