// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `sml` language (SML (Standard ML)).
Language buildSml() {
  final m0 = Language(name: 'SML (Standard ML)', aliases: ['ml']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'abstype',
          'and',
          'andalso',
          'as',
          'case',
          'datatype',
          'do',
          'else',
          'end',
          'eqtype',
          'exception',
          'fn',
          'fun',
          'functor',
          'handle',
          'if',
          'in',
          'include',
          'infix',
          'infixr',
          'let',
          'local',
          'nonfix',
          'of',
          'op',
          'open',
          'orelse',
          'raise',
          'rec',
          'sharing',
          'sig',
          'signature',
          'struct',
          'structure',
          'then',
          'type',
          'val',
          'with',
          'withtype',
          'where',
          'while',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'array',
          'bool',
          'char',
          'exn',
          'int',
          'list',
          'option',
          'order',
          'real',
          'ref',
          'string',
          'substring',
          'vector',
          'unit',
          'word',
        ],
        fromList: false,
      ),
      (
        scope: 'literal',
        words: [
          'true',
          'false',
          'NONE',
          'SOME',
          'LESS',
          'EQUAL',
          'GREATER',
          'nil',
        ],
        fromList: false,
      ),
    ], pattern: '[a-z_]\\w*!?')
    ..illegal = RegexSource('\\/\\/|>>')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..className = ScopeName('literal')
    ..begin = RegexSource('\\[(\\|\\|)?\\]|\\(\\)')
    ..relevance = 0;
  m2
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\\(\\*')
    ..end = RegexSource('\\*\\)')
    ..contains = [self, m11, m12];
  m3
    ..className = ScopeName('symbol')
    ..begin = RegexSource('\'[A-Za-z_](?!\')[\\w\']*');
  m4
    ..className = ScopeName('type')
    ..begin = RegexSource('`[A-Z][\\w\']*');
  m5
    ..className = ScopeName('type')
    ..begin = RegexSource('\\b[A-Z][\\w\']*')
    ..relevance = 0;
  m6..begin = RegexSource('[a-z_]\\w*\'[\\w\']*');
  m7
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..illegal = RegexSource('\\n')
    ..contains = [m13]
    ..className = ScopeName('string')
    ..relevance = 0;
  m8
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..setJsNull(ModeKey.illegal)
    ..contains = [m13];
  m9
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '\\b(0[xX][a-fA-F0-9_]+[Lln]?|0[oO][0-7_]+[Lln]?|0[bB][01_]+[Lln]?|[0-9][0-9_]*([Lln]|(\\.[0-9_]*)?([eE][-+]?[0-9_]+)?)?)',
    )
    ..relevance = 0;
  m10..begin = RegexSource('[-=]>');
  m11
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m12
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m13
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  return m0;
}
