// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `step21` language (STEP Part 21).
Language buildStep21() {
  final m0 = Language(
    name: 'STEP Part 21',
    aliases: ['p21', 'step', 'stp'],
    caseInsensitive: true,
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode();
  m0
    ..keywords = RawKeywords([
      (scope: 'keyword', words: ['HEADER', 'ENDSEC', 'DATA'], fromList: true),
    ], pattern: '[A-Z_][A-Z0-9_.]*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10];
  m1
    ..className = ScopeName('meta')
    ..begin = RegexSource('ISO-10303-21;')
    ..relevance = 10;
  m2
    ..className = ScopeName('meta')
    ..begin = RegexSource('END-ISO-10303-21;')
    ..relevance = 10;
  m3
    ..scope = ScopeName('comment')
    ..begin = RegexSource('//')
    ..end = RegexSource('\$')
    ..contains = [m11, m12]
    ..frozen = true;
  m4
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*')
    ..end = RegexSource('\\*/')
    ..contains = [m13, m14]
    ..frozen = true;
  m5
    ..scope = ScopeName('comment')
    ..begin = RegexSource('/\\*\\*!')
    ..end = RegexSource('\\*/')
    ..contains = [m15, m16];
  m6
    ..scope = ScopeName('number')
    ..begin = RegexSource(
      '(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)',
    )
    ..relevance = 0
    ..frozen = true;
  m7
    ..scope = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..setJsNull(ModeKey.illegal)
    ..contains = [m17];
  m8
    ..scope = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..setJsNull(ModeKey.illegal)
    ..contains = [m17];
  m9
    ..className = ScopeName('string')
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'');
  m10
    ..className = ScopeName('symbol')
    ..variants = [m18];
  m11
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m12
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m13
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0
    ..frozen = true;
  m14
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    )
    ..frozen = true;
  m15
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m16
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m17
    ..begin = RegexSource('\\\\[\\s\\S]')
    ..relevance = 0
    ..frozen = true;
  m18
    ..begin = RegexSource('#')
    ..end = RegexSource('\\d+')
    ..illegal = RegexSource('\\W');
  return m0;
}
