// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `subunit` language (SubUnit).
Language buildSubunit() {
  final m0 = Language(name: 'SubUnit', caseInsensitive: true);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode();
  m0..contains = [m1, m2, m3, m4];
  m1
    ..className = ScopeName('string')
    ..begin = RegexSource('\\[\n(multipart)?')
    ..end = RegexSource('\\]\n');
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource(
      '\\d{4}-\\d{2}-\\d{2}(\\s+)\\d{2}:\\d{2}:\\d{2}.\\d+Z',
    );
  m3
    ..className = ScopeName('string')
    ..begin = RegexSource('(\\+|-)\\d+');
  m4
    ..className = ScopeName('keyword')
    ..relevance = 10
    ..variants = [m5, m6, m7, m8];
  m5
    ..begin = RegexSource(
      '^(test|testing|success|successful|failure|error|skip|xfail|uxsuccess)(:?)\\s+(test)?',
    );
  m6..begin = RegexSource('^progress(:?)(\\s+)?(pop|push)?');
  m7..begin = RegexSource('^tags:');
  m8..begin = RegexSource('^time:');
  return m0;
}
