// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `vbnet` language (Visual Basic .NET).
Language buildVbnet() {
  final m0 = Language(
    name: 'Visual Basic .NET',
    aliases: ['vb'],
    caseInsensitive: true,
    classNameAliases: {'label': 'symbol'},
  );
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode(),
      m25 = Mode();
  m0
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'addhandler',
          'alias',
          'aggregate',
          'ansi',
          'as',
          'async',
          'assembly',
          'auto',
          'binary',
          'by',
          'byref',
          'byval',
          'call',
          'case',
          'catch',
          'class',
          'compare',
          'const',
          'continue',
          'custom',
          'declare',
          'default',
          'delegate',
          'dim',
          'distinct',
          'do',
          'each',
          'equals',
          'else',
          'elseif',
          'end',
          'enum',
          'erase',
          'error',
          'event',
          'exit',
          'explicit',
          'finally',
          'for',
          'friend',
          'from',
          'function',
          'get',
          'global',
          'goto',
          'group',
          'handles',
          'if',
          'implements',
          'imports',
          'in',
          'inherits',
          'interface',
          'into',
          'iterator',
          'join',
          'key',
          'let',
          'lib',
          'loop',
          'me',
          'mid',
          'module',
          'mustinherit',
          'mustoverride',
          'mybase',
          'myclass',
          'namespace',
          'narrowing',
          'new',
          'next',
          'notinheritable',
          'notoverridable',
          'of',
          'off',
          'on',
          'operator',
          'option',
          'optional',
          'order',
          'overloads',
          'overridable',
          'overrides',
          'paramarray',
          'partial',
          'preserve',
          'private',
          'property',
          'protected',
          'public',
          'raiseevent',
          'readonly',
          'redim',
          'removehandler',
          'resume',
          'return',
          'select',
          'set',
          'shadows',
          'shared',
          'skip',
          'static',
          'step',
          'stop',
          'structure',
          'strict',
          'sub',
          'synclock',
          'take',
          'text',
          'then',
          'throw',
          'to',
          'try',
          'unicode',
          'until',
          'using',
          'when',
          'where',
          'while',
          'widening',
          'with',
          'withevents',
          'writeonly',
          'yield',
        ],
        fromList: false,
      ),
      (
        scope: 'built_in',
        words: [
          'addressof',
          'and',
          'andalso',
          'await',
          'directcast',
          'gettype',
          'getxmlnamespace',
          'is',
          'isfalse',
          'isnot',
          'istrue',
          'like',
          'mod',
          'nameof',
          'new',
          'not',
          'or',
          'orelse',
          'trycast',
          'typeof',
          'xor',
          'cbool',
          'cbyte',
          'cchar',
          'cdate',
          'cdbl',
          'cdec',
          'cint',
          'clng',
          'cobj',
          'csbyte',
          'cshort',
          'csng',
          'cstr',
          'cuint',
          'culng',
          'cushort',
        ],
        fromList: false,
      ),
      (
        scope: 'type',
        words: [
          'boolean',
          'byte',
          'char',
          'date',
          'decimal',
          'double',
          'integer',
          'long',
          'object',
          'sbyte',
          'short',
          'single',
          'string',
          'uinteger',
          'ulong',
          'ushort',
        ],
        fromList: false,
      ),
      (scope: 'literal', words: ['true', 'false', 'nothing'], fromList: false),
    ])
    ..illegal = RegexSource('//|\\{|\\}|endif|gosub|variant|wend|^\\\$ ')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8];
  m1
    ..className = ScopeName('string')
    ..begin = RegexSource('"(""|[^/n])"C\\b');
  m2
    ..className = ScopeName('string')
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..illegal = RegexSource('\\n')
    ..contains = [m9];
  m3
    ..className = ScopeName('literal')
    ..variants = [m10, m11, m12, m13];
  m4
    ..className = ScopeName('number')
    ..relevance = 0
    ..variants = [m14, m15, m16, m17, m18];
  m5
    ..className = ScopeName('label')
    ..begin = RegexSource('^\\w+:');
  m6
    ..scope = ScopeName('comment')
    ..begin = RegexSource('\'\'\'')
    ..end = RegexSource('\$')
    ..contains = [m19, m20, m21];
  m7
    ..scope = ScopeName('comment')
    ..setJsNull(ModeKey.begin)
    ..end = RegexSource('\$')
    ..contains = [m22, m23]
    ..variants = [m24, m25];
  m8
    ..className = ScopeName('meta')
    ..begin = RegexSource(
      '[\\t ]*#(const|disable|else|elseif|enable|end|externalsource|if|region)\\b',
    )
    ..end = RegexSource('\$')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'const',
          'disable',
          'else',
          'elseif',
          'enable',
          'end',
          'externalsource',
          'if',
          'region',
          'then',
        ],
        fromList: false,
      ),
    ])
    ..contains = [m7];
  m9..begin = RegexSource('""');
  m10
    ..begin = RegexSource(
      '# *(?:\\d{4}-\\d{1,2}-\\d{1,2}|\\d{1,2}\\/\\d{1,2}\\/\\d{4}) *#',
    );
  m11..begin = RegexSource('# *\\d{1,2}(:\\d{1,2}){1,2} *#');
  m12..begin = RegexSource('# *(\\d|1[012])(:\\d+){0,2} *(AM|PM) *#');
  m13
    ..begin = RegexSource(
      '# *(?:\\d{4}-\\d{1,2}-\\d{1,2}|\\d{1,2}\\/\\d{1,2}\\/\\d{4}) +(?:(\\d|1[012])(:\\d+){0,2} *(AM|PM)|\\d{1,2}(:\\d{1,2}){1,2}) *#',
    );
  m14
    ..begin = RegexSource(
      '\\b\\d[\\d_]*((\\.[\\d_]+(E[+-]?[\\d_]+)?)|(E[+-]?[\\d_]+))[RFD@!#]?',
    );
  m15..begin = RegexSource('\\b\\d[\\d_]*((U?[SIL])|[%&])?');
  m16..begin = RegexSource('&H[\\dA-F_]+((U?[SIL])|[%&])?');
  m17..begin = RegexSource('&O[0-7_]+((U?[SIL])|[%&])?');
  m18..begin = RegexSource('&B[01_]+((U?[SIL])|[%&])?');
  m19
    ..className = ScopeName('doctag')
    ..begin = RegexSource('<\\/?')
    ..end = RegexSource('>');
  m20
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m21
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m22
    ..scope = ScopeName('doctag')
    ..begin = RegexSource('[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)')
    ..end = RegexSource('(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):')
    ..excludeBegin = true
    ..relevance = 0;
  m23
    ..begin = RegexSource(
      '[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+[\'](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}',
    );
  m24..begin = RegexSource('\'');
  m25..begin = RegexSource('([\\t ]|^)REM(?=\\s)');
  return m0;
}
