// GENERATED by tool/generate/generate.mjs from highlight.js 11.12.0. Do not edit.
// ignore_for_file: type=lint

import 'package:hilite/src/mode.dart';

/// The `xquery` language (XQuery).
Language buildXquery() {
  final m0 = Language(name: 'XQuery', aliases: ['xpath', 'xq', 'xqm']);
  final m1 = Mode(),
      m2 = Mode(),
      m3 = Mode(),
      m4 = Mode(),
      m5 = Mode(),
      m6 = Mode(),
      m7 = Mode(),
      m8 = Mode(),
      m9 = Mode(),
      m10 = Mode(),
      m11 = Mode(),
      m12 = Mode(),
      m13 = Mode(),
      m14 = Mode(),
      m15 = Mode(),
      m16 = Mode(),
      m17 = Mode(),
      m18 = Mode(),
      m19 = Mode(),
      m20 = Mode(),
      m21 = Mode(),
      m22 = Mode(),
      m23 = Mode(),
      m24 = Mode();
  m0
    ..illegal = RegexSource('(proc)|(abstract)|(extends)|(until)|(#)')
    ..keywords = RawKeywords([
      (
        scope: 'keyword',
        words: [
          'module',
          'schema',
          'namespace',
          'boundary-space',
          'preserve',
          'no-preserve',
          'strip',
          'default',
          'collation',
          'base-uri',
          'ordering',
          'context',
          'decimal-format',
          'decimal-separator',
          'copy-namespaces',
          'empty-sequence',
          'except',
          'exponent-separator',
          'external',
          'grouping-separator',
          'inherit',
          'no-inherit',
          'lax',
          'minus-sign',
          'per-mille',
          'percent',
          'schema-attribute',
          'schema-element',
          'strict',
          'unordered',
          'zero-digit',
          'declare',
          'import',
          'option',
          'function',
          'validate',
          'variable',
          'for',
          'at',
          'in',
          'let',
          'where',
          'order',
          'group',
          'by',
          'return',
          'if',
          'then',
          'else',
          'tumbling',
          'sliding',
          'window',
          'start',
          'when',
          'only',
          'end',
          'previous',
          'next',
          'stable',
          'ascending',
          'descending',
          'allowing',
          'empty',
          'greatest',
          'least',
          'some',
          'every',
          'satisfies',
          'switch',
          'case',
          'typeswitch',
          'try',
          'catch',
          'and',
          'or',
          'to',
          'union',
          'intersect',
          'instance',
          'of',
          'treat',
          'as',
          'castable',
          'cast',
          'map',
          'array',
          'delete',
          'insert',
          'into',
          'replace',
          'value',
          'rename',
          'copy',
          'modify',
          'update',
        ],
        fromList: true,
      ),
      (
        scope: 'type',
        words: [
          'item',
          'document-node',
          'node',
          'attribute',
          'document',
          'element',
          'comment',
          'namespace',
          'namespace-node',
          'processing-instruction',
          'text',
          'construction',
          'xs:anyAtomicType',
          'xs:untypedAtomic',
          'xs:duration',
          'xs:time',
          'xs:decimal',
          'xs:float',
          'xs:double',
          'xs:gYearMonth',
          'xs:gYear',
          'xs:gMonthDay',
          'xs:gMonth',
          'xs:gDay',
          'xs:boolean',
          'xs:base64Binary',
          'xs:hexBinary',
          'xs:anyURI',
          'xs:QName',
          'xs:NOTATION',
          'xs:dateTime',
          'xs:dateTimeStamp',
          'xs:date',
          'xs:string',
          'xs:normalizedString',
          'xs:token',
          'xs:language',
          'xs:NMTOKEN',
          'xs:Name',
          'xs:NCName',
          'xs:ID',
          'xs:IDREF',
          'xs:ENTITY',
          'xs:integer',
          'xs:nonPositiveInteger',
          'xs:negativeInteger',
          'xs:long',
          'xs:int',
          'xs:short',
          'xs:byte',
          'xs:nonNegativeInteger',
          'xs:unisignedLong',
          'xs:unsignedInt',
          'xs:unsignedShort',
          'xs:unsignedByte',
          'xs:positiveInteger',
          'xs:yearMonthDuration',
          'xs:dayTimeDuration',
        ],
        fromList: true,
      ),
      (
        scope: 'literal',
        words: [
          'eq',
          'ne',
          'lt',
          'le',
          'gt',
          'ge',
          'is',
          'self::',
          'child::',
          'descendant::',
          'descendant-or-self::',
          'attribute::',
          'following::',
          'following-sibling::',
          'parent::',
          'ancestor::',
          'ancestor-or-self::',
          'preceding::',
          'preceding-sibling::',
          'NaN',
        ],
        fromList: true,
      ),
    ], pattern: '[a-zA-Z\$][a-zA-Z0-9_:-]*')
    ..contains = [m1, m2, m3, m4, m5, m6, m7, m8, m9];
  m1
    ..className = ScopeName('variable')
    ..begin = RegexSource('[\$][\\w\\-:]+');
  m2
    ..className = ScopeName('built_in')
    ..variants = [m10, m11, m12, m13, m14, m15, m16, m17, m18];
  m3
    ..className = ScopeName('string')
    ..variants = [m19, m20];
  m4
    ..className = ScopeName('number')
    ..begin = RegexSource(
      '(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b',
    )
    ..relevance = 0;
  m5
    ..className = ScopeName('comment')
    ..begin = RegexSource('\\(:')
    ..end = RegexSource(':\\)')
    ..relevance = 10
    ..contains = [m21];
  m6
    ..className = ScopeName('meta')
    ..begin = RegexSource('%[\\w\\-:]+');
  m7
    ..className = ScopeName('title')
    ..begin = RegexSource(
      '\\bxquery version "[13]\\.[01]"\\s?(?:encoding ".+")?',
    )
    ..end = RegexSource(';');
  m8
    ..beginKeywords =
        'element attribute comment document processing-instruction'
    ..end = RegexSource('\\{')
    ..excludeEnd = true;
  m9
    ..begin = RegexSource('<([\\w._:-]+)(\\s+\\S*=(\'|").*(\'|"))?>')
    ..end = RegexSource('(\\/[\\w._:-]+>)')
    ..subLanguage = SubLanguageName('xml')
    ..contains = [m22, self];
  m10
    ..begin = RegexSource('\\barray:')
    ..end = RegexSource(
      '(?:append|filter|flatten|fold-(?:left|right)|for-each(?:-pair)?|get|head|insert-before|join|put|remove|reverse|size|sort|subarray|tail)\\b',
    );
  m11
    ..begin = RegexSource('\\bmap:')
    ..end = RegexSource(
      '(?:contains|entry|find|for-each|get|keys|merge|put|remove|size)\\b',
    );
  m12
    ..begin = RegexSource('\\bmath:')
    ..end = RegexSource(
      '(?:a(?:cos|sin|tan[2]?)|cos|exp(?:10)?|log(?:10)?|pi|pow|sin|sqrt|tan)\\b',
    );
  m13
    ..begin = RegexSource('\\bop:')
    ..end = RegexSource('\\(')
    ..excludeEnd = true;
  m14
    ..begin = RegexSource('\\bfn:')
    ..end = RegexSource('\\(')
    ..excludeEnd = true;
  m15
    ..begin = RegexSource(
      '[^</\$:\'"-]\\b(?:abs|accumulator-(?:after|before)|adjust-(?:date(?:Time)?|time)-to-timezone|analyze-string|apply|available-(?:environment-variables|system-properties)|avg|base-uri|boolean|ceiling|codepoints?-(?:equal|to-string)|collation-key|collection|compare|concat|contains(?:-token)?|copy-of|count|current(?:-)?(?:date(?:Time)?|time|group(?:ing-key)?|output-uri|merge-(?:group|key))?data|dateTime|days?-from-(?:date(?:Time)?|duration)|deep-equal|default-(?:collation|language)|distinct-values|document(?:-uri)?|doc(?:-available)?|element-(?:available|with-id)|empty|encode-for-uri|ends-with|environment-variable|error|escape-html-uri|exactly-one|exists|false|filter|floor|fold-(?:left|right)|for-each(?:-pair)?|format-(?:date(?:Time)?|time|integer|number)|function-(?:arity|available|lookup|name)|generate-id|has-children|head|hours-from-(?:dateTime|duration|time)|id(?:ref)?|implicit-timezone|in-scope-prefixes|index-of|innermost|insert-before|iri-to-uri|json-(?:doc|to-xml)|key|lang|last|load-xquery-module|local-name(?:-from-QName)?|(?:lower|upper)-case|matches|max|minutes-from-(?:dateTime|duration|time)|min|months?-from-(?:date(?:Time)?|duration)|name(?:space-uri-?(?:for-prefix|from-QName)?)?|nilled|node-name|normalize-(?:space|unicode)|not|number|one-or-more|outermost|parse-(?:ietf-date|json)|path|position|(?:prefix-from-)?QName|random-number-generator|regex-group|remove|replace|resolve-(?:QName|uri)|reverse|root|round(?:-half-to-even)?|seconds-from-(?:dateTime|duration|time)|snapshot|sort|starts-with|static-base-uri|stream-available|string-?(?:join|length|to-codepoints)?|subsequence|substring-?(?:after|before)?|sum|system-property|tail|timezone-from-(?:date(?:Time)?|time)|tokenize|trace|trans(?:form|late)|true|type-available|unordered|unparsed-(?:entity|text)?-?(?:public-id|uri|available|lines)?|uri-collection|xml-to-json|years?-from-(?:date(?:Time)?|duration)|zero-or-one)\\b',
    );
  m16
    ..begin = RegexSource('\\blocal:')
    ..end = RegexSource('\\(')
    ..excludeEnd = true;
  m17
    ..begin = RegexSource('\\bzip:')
    ..end = RegexSource(
      '(?:zip-file|(?:xml|html|text|binary)-entry| (?:update-)?entries)\\b',
    );
  m18
    ..begin = RegexSource('\\b(?:util|db|functx|app|xdmp|xmldb):')
    ..end = RegexSource('\\(')
    ..excludeEnd = true;
  m19
    ..begin = RegexSource('"')
    ..end = RegexSource('"')
    ..contains = [m23];
  m20
    ..begin = RegexSource('\'')
    ..end = RegexSource('\'')
    ..contains = [m24];
  m21
    ..className = ScopeName('doctag')
    ..begin = RegexSource('@\\w+');
  m22
    ..begin = RegexSource('\\{')
    ..end = RegexSource('\\}')
    ..subLanguage = SubLanguageName('xquery');
  m23
    ..begin = RegexSource('""')
    ..relevance = 0;
  m24
    ..begin = RegexSource('\'\'')
    ..relevance = 0;
  return m0;
}
